In [1]:
from ta.volatility import AverageTrueRange

import pandas as pd
import plotly.graph_objects as go
from plotly.subplots import make_subplots
from datetime import datetime
import numpy as np

import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd

from backtesting import Strategy
from backtesting import Backtest, set_bokeh_output
set_bokeh_output(notebook=False)

from datetime import timedelta

import sys
sys.path.append('../utils')
import Util
import importlib
importlib.reload(Util)

from enum import Enum
import time

from random import randint
import random

c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\_plotting.py:55: UserWarning: Jupyter Notebook detected. Setting Bokeh output to notebook. This may not work in Jupyter clients without JavaScript support, such as old IDEs. Reset with `backtesting.set_bokeh_output(notebook=False)`.
  warnings.warn('Jupyter Notebook detected. '

In [3]:
pair = 'CADCHF'

df_d1_raw = pd.read_csv(f"../Trading Data/{pair}_D1.csv",sep=',', parse_dates=['Date'], index_col='Date')
df_h4_raw = pd.read_csv(f"../Trading Data/{pair}_H4.csv",sep=',', parse_dates=['Date'], index_col='Date')
df_m15_raw = pd.read_csv(f"../Trading Data/{pair}_M15.csv",sep=',', parse_dates=['Date'], index_col='Date')

print(df_d1_raw)
print(df_h4_raw)
print(df_m15_raw)

               Open     High      Low    Close  Tickvol
Date
2010-09-23  0.95790  0.95845  0.94550  0.95260    81300
2010-09-24  0.95260  0.96180  0.94780  0.95980   103852
2010-09-27  0.96055  0.96420  0.95510  0.95655   115385
2010-09-28  0.95655  0.95765  0.94310  0.94775   126433
2010-09-29  0.94765  0.95425  0.94400  0.94620   115335
...             ...      ...      ...      ...      ...
2026-10-05  0.58075  0.58381  0.58046  0.58250    48951
2026-10-06  0.58249  0.58551  0.58186  0.58538    42990
2026-10-07  0.58540  0.58631  0.58206  0.58423    50257
2026-10-08  0.58424  0.58563  0.58294  0.58443    66525
2026-10-09  0.58444  0.58472  0.58121  0.58234    34325

[4185 rows x 5 columns]
                        Open     High      Low    Close  Tickvol
Date
2010-09-23 08:00:00  0.95790  0.95845  0.95285  0.95370    19153
2010-09-23 12:00:00  0.95370  0.95455  0.94550  0.95075    30860
2010-09-23 16:00:00  0.95060  0.95640  0.95035  0.95445    19947
2010-09-23 20:00:00  0.95445  0.95465  0.95180  0.95260    11340
2010-09-24 00:00:00  0.95260  0.95390  0.95190  0.95355    11213
...                      ...      ...      ...      ...      ...
2026-10-08 20:00:00  0.58464  0.58483  0.58294  0.58443     5859
2026-10-09 00:00:00  0.58444  0.58472  0.58406  0.58417     6568
2026-10-09 04:00:00  0.58416  0.58466  0.58397  0.58442     6073
2026-10-09 08:00:00  0.58441  0.58452  0.58339  0.58370     7289
2026-10-09 12:00:00  0.58370  0.58421  0.58121  0.58234    14395

[25035 rows x 5 columns]
                        Open     High      Low    Close  Tickvol
Date
2020-09-03 03:15:00  0.69834  0.69838  0.69820  0.69823      512
2020-09-03 03:30:00  0.69822  0.69835  0.69811  0.69826      473
2020-09-03 03:45:00  0.69823  0.69843  0.69817  0.69825      627
2020-09-03 04:00:00  0.69827  0.69835  0.69791  0.69801      516
2020-09-03 04:15:00  0.69800  0.69805  0.69785  0.69791      451
...                      ...      ...      ...      ...      ...
2026-10-09 13:45:00  0.58206  0.58244  0.58191  0.58214     2520
2026-10-09 14:00:00  0.58214  0.58265  0.58204  0.58244     1702
2026-10-09 14:15:00  0.58243  0.58249  0.58199  0.58230     1545
2026-10-09 14:30:00  0.58231  0.58286  0.58229  0.58267     1415
2026-10-09 14:45:00  0.58269  0.58279  0.58226  0.58234     1045

[150000 rows x 5 columns]

In [4]:
structure_d1_window = 2
structure_m15_window = 2

date_format = '%Y-%m-%d %H:%M'
# start_date = '2023-1-1 00:00'
# end_date = '2024-3-29 00:00'
start_date = datetime.strptime('2021-1-1 00:00', date_format)
end_date = datetime.strptime('2026-9-16 00:00', date_format)
# start_date = '2022-01-1 00:00'

timezone = "Europe/London"

# nombre de jours pour les high.low
define_key_level_window = 90

gap_look_ahead = 6

# nombre de candle au dessus/ en desous de key level après breakout
breakout_candles = 9

# nombre de jours à chercher key level
key_level_lookback_candle = 100

# vérifier si 30 candle dans ke passé pour valider un valid breakout,
# un valid breakout doit avoir {breakout_candles} candles au dessus du resistant level
breakout_candles_lookback = 30

start_trade_hour = 9
stop_trade_hour = 19

atr_multiplier = 0.7
min_touched = 3

In [5]:
# process h4 data
df_h4 = df_h4_raw.loc[start_date - timedelta(days=20) : end_date]
df_h4 = Util.implement_market_structure_states_fixed_pivots(df_h4, 5)
df_h4 = df_h4.loc[start_date : end_date]

indicator_atr_14 = AverageTrueRange(df_h4['High'], df_h4['Low'], df_h4['Close'], window=14)
df_h4['ATR'] = indicator_atr_14._atr

df_h4

,Open,High,Low,Close,Tickvol,is_swing_high,is_swing_low,market_state,ATR
Date,,,,,,,,,
2021-01-04 00:00:00,0.69378,0.69573,0.69310,0.69555,12960,False,False,BULLISH,0.000000
2021-01-04 04:00:00,0.69553,0.69625,0.69513,0.69527,9826,True,False,BULLISH,0.000000
2021-01-04 08:00:00,0.69525,0.69580,0.69311,0.69377,20631,False,False,BULLISH,0.000000
2021-01-04 12:00:00,0.69377,0.69405,0.69151,0.69293,23712,False,False,BULLISH,0.000000
2021-01-04 16:00:00,0.69296,0.69395,0.68858,0.68984,32860,False,False,BULLISH,0.000000
...,...,...,...,...,...,...,...,...,...
2026-09-15 08:00:00,0.58789,0.58839,0.58749,0.58791,6852,False,False,BULLISH,0.001281
2026-09-15 12:00:00,0.58792,0.58904,0.58735,0.58878,9087,False,False,BULLISH,0.001310
2026-09-15 16:00:00,0.58879,0.58880,0.58812,0.58812,4546,False,False,BULLISH,0.001265
2026-09-15 20:00:00,0.58812,0.58843,0.58662,0.58820,5083,False,False,BULLISH,0.001304
2026-09-16 00:00:00,0.58820,0.58835,0.58775,0.58776,3957,False,False,BULLISH,0.001253

In [6]:
resistants_list = Util.define_resistant_level_with_atr(df_h4, define_key_level_window, atr_multiplier=atr_multiplier, min_touched=min_touched)
supports_list = Util.define_support_level_with_atr(df_h4, define_key_level_window, atr_multiplier=atr_multiplier, min_touched=min_touched)

df_h4['support_point'] = df_h4.apply(lambda row: Util.support_pos(supports_list, row), axis=1)
df_h4['is_support'] = df_h4.apply(lambda row: Util.is_support(supports_list, row), axis=1)

df_h4['resistant_point'] = df_h4.apply(lambda row: Util.resistant_pos(resistants_list, row), axis=1)
df_h4['is_resistant'] = df_h4.apply(lambda row: Util.is_resistant(resistants_list, row), axis=1)

df_h4['valid_breakout_support_levels'] = Util.is_candles_above_support_level_list(df_h4, breakout_candles, key_level_lookback_candle)
df_h4['valid_breakout_resistant_levels'] = Util.is_candles_below_resistant_level_list(df_h4, breakout_candles, key_level_lookback_candle)

In [7]:
# process m15 data
df_m15 = df_m15_raw.loc[start_date - timedelta(hours=3): end_date]
df_m15 = Util.implement_market_structure_states_fixed_pivots(df_m15, n=structure_m15_window)

m15_h4_resistant_level_list = []
m15_is_resistants_list = []
m15_is_below_resistant_list = []

m15_h4_support_level_list = []
m15_is_supports_list = []
m15_is_above_support_list = []

index_list = []

indicator_atr_m15 = AverageTrueRange(df_m15['High'], df_m15['Low'], df_m15['Close'], window=14)
df_m15['ATR'] = indicator_atr_m15._atr

df_m15 = df_m15.loc[start_date : end_date]
for i in range(len(df_h4)):
    row = df_h4.iloc[i]
    start_date_h4 = row.name
    end_date_h4 = start_date_h4 + timedelta(hours=3, minutes=59)
    df_by_day = df_m15.loc[f'{start_date_h4}' : f'{end_date_h4}']

    for index2, row2 in df_by_day.iterrows():
        m15_h4_resistant_level_list.append(df_h4.iloc[i]['resistant_point'])
        m15_is_resistants_list.append(df_h4.iloc[i]['is_resistant'])
        m15_is_below_resistant_list.append(df_h4.iloc[i]['valid_breakout_resistant_levels'])
        # affect current market states of H4 candle because the result is market state of previous D1 candle

        m15_h4_support_level_list.append(df_h4.iloc[i]['support_point'])
        m15_is_supports_list.append(df_h4.iloc[i]['is_support'])
        m15_is_above_support_list.append(df_h4.iloc[i]['valid_breakout_support_levels'])

        # ajust to daylight saving time
        dst = pd.Timestamp(index2, tz=timezone).dst()
        if dst == timedelta(0):
            index2 = index2 - timedelta(hours=1)
            index_list.append(index2)
        else:
            index_list.append(index2)

df_m15['resistant_point'] = m15_h4_resistant_level_list
df_m15['is_resistant'] = m15_is_resistants_list
df_m15['valid_breakout_resistant_levels'] = m15_is_below_resistant_list

df_m15['support_point'] = m15_h4_support_level_list
df_m15['is_support'] = m15_is_supports_list
df_m15['valid_breakout_support_levels'] = m15_is_above_support_list

df_m15.index = index_list

df_m15

,Open,High,Low,Close,Tickvol,is_swing_high,is_swing_low,market_state,ATR,resistant_point,is_resistant,valid_breakout_resistant_levels,support_point,is_support,valid_breakout_support_levels
2021-01-03 23:00:00,0.69378,0.69450,0.69310,0.69425,1856,False,True,BEARISH,0.000000,NaN,False,"[0.578, 0.585]",NaN,False,[0.587]
2021-01-03 23:15:00,0.69425,0.69472,0.69424,0.69428,451,False,False,BEARISH,0.000000,NaN,False,"[0.578, 0.585]",NaN,False,[0.587]
2021-01-03 23:30:00,0.69429,0.69438,0.69412,0.69423,595,False,False,BEARISH,0.000000,NaN,False,"[0.578, 0.585]",NaN,False,[0.587]
2021-01-03 23:45:00,0.69422,0.69422,0.69372,0.69403,767,False,True,BEARISH,0.000000,NaN,False,"[0.578, 0.585]",NaN,False,[0.587]
2021-01-04 00:00:00,0.69403,0.69450,0.69382,0.69413,914,True,False,BEARISH,0.000000,NaN,False,"[0.578, 0.585]",NaN,False,[0.587]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2026-09-15 23:00:00,0.58770,0.58809,0.58770,0.58803,238,False,False,BEARISH,0.000351,NaN,False,[],NaN,False,[]
2026-09-15 23:15:00,0.58803,0.58809,0.58801,0.58808,144,False,False,BEARISH,0.000332,NaN,False,[],NaN,False,[]
2026-09-15 23:30:00,0.58805,0.58816,0.58805,0.58813,170,False,False,BEARISH,0.000316,NaN,False,[],NaN,False,[]
2026-09-15 23:45:00,0.58814,0.58820,0.58812,0.58820,147,False,False,BEARISH,0.000299,NaN,False,[],NaN,False,[]
2026-09-16 00:00:00,0.58820,0.58824,0.58816,0.58822,237,False,False,BEARISH,0.000283,NaN,False,[],NaN,False,[]

In [8]:
def is_existed(list, value):
    for i in range(len(list)):
        if list[i] == value:
            return True
    return False

In [9]:
# using m15 market structure for entry
def apply_total_signal(df, key_level_lookback_candle = 150, gap=1, breakout_candles_lookback = 30, start_trade_hour=8, stop_trade_hour=19):
    # Initialize the 'TotalSignal' column
    df_signal_list = []
    valid_support_levels_list = []
    valid_resistant_levels_list = []
    current_day = None

    # short variables
    is_resistant_level_touched = False
    is_below_resistant_levels = False
    high_tf_condition_short_satisfied = False
    high_tf_condition_short_candle = None
    m15_market_state_bearish = False

    # long variables
    is_support_level_touched = False
    is_above_support_levels = False
    high_tf_condition_long_satisfied = False
    high_tf_condition_long_candle = None
    m15_market_state_bullish = False

    # we want market structure to switch from bearish to bullish when htf conditions are met
    # if market structure is already bullish we need to wait
    previous_market_structure = None

    resistants_levels_touched = []
    supports_levels_touched = []

    for i in range(0, len(df)):
        current_bar_date = df.index[i]
        signal = 0
        # valid resistants levels are when valid breakout and levels touched
        valid_resistant_levels = []
        valid_support_levels = []

        if current_day != current_bar_date.date() or current_bar_date.time().hour >= stop_trade_hour:
            current_day = current_bar_date.date()
            # short
            high_tf_condition_short_satisfied = False
            resistants_levels_touched = []
            is_resistant_level_touched = False
            valid_breakout_resistant_levels = []
            is_below_resistant_levels = False

            # long
            high_tf_condition_long_satisfied = False
            supports_levels_touched = []
            is_support_level_touched = False
            valid_breakout_support_levels = []
            is_above_support_levels = False

        # short
        c_m15_ms_bearish = df['market_state'].iloc[i] == 'BEARISH'

        # h4 key level conditions
        resistants_levels = Util.get_resistant_list(df, i, key_level_lookback_candle, gap, Util.TimeFrame.M15)
        for level in resistants_levels:
            if df['High'].iloc[i-1] > level:
                is_resistant_level_touched = True
                if not is_existed(resistants_levels_touched, level):
                    resistants_levels_touched.append(level)
        
        # Combine conditions
        if (is_resistant_level_touched and
            not high_tf_condition_short_satisfied):
            high_tf_condition_short_satisfied = True
            high_tf_condition_short_candle = current_bar_date
            previous_market_structure = df['market_state'].iloc[i]
            print(f"{current_bar_date} {i}")

        if (high_tf_condition_short_satisfied == True and
            c_m15_ms_bearish and
            high_tf_condition_short_candle < current_bar_date and
            previous_market_structure == 'BULLISH'):
            m15_market_state_bearish = True

        # breakout_candles_below candle needs to be below resistant level for the breakout to be valid
        valid_breakout_resistant_levels = Util.get_valid_breakout_resistant_level(df, i, breakout_candles_lookback)
        
        for valid_level in valid_breakout_resistant_levels:
            for level_touched in resistants_levels_touched:
                if valid_level == level_touched:
                    valid_resistant_levels.append(valid_level)
                    is_below_resistant_levels = True

        c_time_trade = start_trade_hour <= current_bar_date.hour and current_bar_date.hour <= stop_trade_hour
        if c_time_trade:
            if (high_tf_condition_short_satisfied == True and
                m15_market_state_bearish and
                is_below_resistant_levels):
                signal = 1

        # long
        c_m15_ms_bullish = df['market_state'].iloc[i] == 'BULLISH'
        
        # h4 support level conditions
        supports_levels = Util.get_support_list(df, i, key_level_lookback_candle, gap, Util.TimeFrame.M15)
        for level in supports_levels:
            if df['Low'].iloc[i-1] < level:
                is_support_level_touched = True
                if not is_existed(supports_levels_touched, level):
                    supports_levels_touched.append(level)

        # Combine conditions
        if (is_support_level_touched and
            not high_tf_condition_long_satisfied):
            high_tf_condition_long_satisfied = True
            m15_market_state_bullish = False
            high_tf_condition_long_candle = current_bar_date
            previous_market_structure = df['market_state'].iloc[i]
            # print(f"high_tf_condition_long_satisfied {current_bar_date} {i}")

        if (high_tf_condition_long_satisfied and
            c_m15_ms_bullish and
            high_tf_condition_long_candle < current_bar_date and
            previous_market_structure == 'BEARISH'):
            # print(f"m15_market_state_bullish {current_bar_date} {i}")
            m15_market_state_bullish = True

        # breakout_candles_above candle needs to be above support level for the breakout to be valid
        valid_breakout_support_levels = Util.get_valid_breakout_support_level(df, i, breakout_candles_lookback)
        for valid_level in valid_breakout_support_levels:
            for level_touched in supports_levels_touched:
                if valid_level == level_touched:
                    valid_support_levels.append(valid_level)
                    is_above_support_levels = True

        c_time_trade = start_trade_hour <= current_bar_date.hour and current_bar_date.hour <= stop_trade_hour
        if c_time_trade:
            if (high_tf_condition_long_satisfied == True and
                m15_market_state_bullish and
                is_above_support_levels):
                print(f"signal {current_bar_date} {i}")
                signal = 2

        if previous_market_structure != df['market_state'].iloc[i]:
            if df['market_state'].iloc[i] == 'BULLISH':
                m15_market_state_bearish = False
            if df['market_state'].iloc[i] == 'BEARISH':
                m15_market_state_bullish = False
            previous_market_structure = df['market_state'].iloc[i]    

        df_signal_list.append(signal)
        valid_resistant_levels_list.append(valid_resistant_levels)
        valid_support_levels_list.append(valid_support_levels)

    return df_signal_list, valid_resistant_levels_list, valid_support_levels_list

df_m15['TotalSignal'], df_m15['valid_resistant_levels'], df_m15['valid_support_levels'] = apply_total_signal(df=df_m15, key_level_lookback_candle=key_level_lookback_candle, gap=gap_look_ahead,
                                                                            breakout_candles_lookback=breakout_candles_lookback, start_trade_hour=start_trade_hour, stop_trade_hour=stop_trade_hour)

2021-01-03 23:00:00 0
2021-01-03 23:15:00 1
2021-01-03 23:30:00 2
2021-01-03 23:45:00 3
2021-01-04 00:00:00 4
2021-01-26 18:00:00 1600
2021-01-26 19:00:00 1604
2021-01-26 19:15:00 1605
2021-01-26 19:30:00 1606
2021-01-26 19:45:00 1607
2021-01-26 20:00:00 1608
2021-01-26 20:15:00 1609
2021-01-26 20:30:00 1610
2021-01-26 20:45:00 1611
2021-01-26 21:00:00 1612
2021-01-26 21:15:00 1613
2021-01-26 21:30:00 1614
2021-01-26 21:45:00 1615
2021-01-26 22:00:00 1616
2021-01-26 22:15:00 1617
2021-01-26 22:30:00 1618
2021-01-26 22:45:00 1619
2021-01-26 23:00:00 1620
2021-01-26 23:15:00 1621
2021-01-26 23:30:00 1622
2021-01-26 23:45:00 1623
2021-01-27 00:00:00 1624
2021-01-27 19:00:00 1700
2021-01-27 19:15:00 1701
2021-01-27 19:30:00 1702
2021-01-27 19:45:00 1703
2021-01-27 20:00:00 1704
2021-01-27 20:15:00 1705
2021-01-27 20:30:00 1706
2021-01-29 13:15:00 1869
2021-01-29 19:00:00 1892
2021-01-29 19:15:00 1893
2021-01-29 19:30:00 1894
2021-01-29 19:45:00 1895
2021-01-29 20:00:00 1896
2021-01-29 20:15:00 1897
2021-01-29 20:30:00 1898
2021-01-29 20:45:00 1899
2021-01-29 21:00:00 1900
2021-01-29 21:15:00 1901
2021-01-29 21:30:00 1902
2021-01-29 21:45:00 1903
2021-01-31 23:00:00 1904
2021-01-31 23:15:00 1905
2021-01-31 23:30:00 1906
2021-01-31 23:45:00 1907
2021-02-01 00:00:00 1908
2021-02-01 19:00:00 1984
2021-02-01 19:15:00 1985
2021-02-01 19:30:00 1986
2021-02-01 19:45:00 1987
2021-02-01 20:00:00 1988
2021-02-01 20:15:00 1989
2021-02-01 20:30:00 1990
2021-02-01 20:45:00 1991
2021-02-01 21:00:00 1992
2021-02-01 21:15:00 1993
2021-02-01 21:30:00 1994
2021-02-01 21:45:00 1995
2021-02-01 22:00:00 1996
2021-02-01 22:15:00 1997
2021-02-01 22:30:00 1998
2021-02-01 22:45:00 1999
2021-02-01 23:00:00 2000
2021-02-01 23:15:00 2001
2021-02-01 23:30:00 2002
2021-02-01 23:45:00 2003
2021-02-02 00:00:00 2004
2021-02-02 19:00:00 2080
2021-02-02 19:15:00 2081
2021-02-02 19:30:00 2082
2021-02-02 19:45:00 2083
2021-02-02 20:00:00 2084
2021-02-02 20:15:00 2085
2021-02-02 20:30:00 2086
2021-02-02 20:45:00 2087
2021-02-02 21:00:00 2088
2021-02-02 21:15:00 2089
2021-02-02 21:30:00 2090
2021-02-02 21:45:00 2091
2021-02-02 22:00:00 2092
2021-02-02 22:15:00 2093
2021-02-02 22:30:00 2094
2021-02-02 22:45:00 2095
2021-02-02 23:00:00 2096
2021-02-02 23:15:00 2097
2021-02-02 23:30:00 2098
2021-02-02 23:45:00 2099
2021-02-03 00:00:00 2100
2021-02-03 19:00:00 2176
2021-02-03 19:15:00 2177
2021-02-03 19:30:00 2178
2021-02-03 19:45:00 2179
2021-02-03 20:00:00 2180
2021-02-03 20:15:00 2181
2021-02-03 20:30:00 2182
2021-02-03 20:45:00 2183
2021-02-03 21:00:00 2184
2021-02-03 21:15:00 2185
2021-02-03 21:30:00 2186
2021-02-03 21:45:00 2187
2021-02-03 22:00:00 2188
2021-02-03 22:15:00 2189
2021-02-03 22:30:00 2190
2021-02-03 22:45:00 2191
2021-02-03 23:00:00 2192
2021-02-03 23:15:00 2193
2021-02-03 23:30:00 2194
2021-02-03 23:45:00 2195
2021-02-04 00:00:00 2196
2021-02-04 19:00:00 2272
2021-02-04 19:15:00 2273
2021-02-04 19:30:00 2274
2021-02-04 19:45:00 2275
2021-02-04 20:00:00 2276
2021-02-04 20:15:00 2277
2021-02-04 20:30:00 2278
2021-02-04 20:45:00 2279
2021-02-04 21:00:00 2280
2021-02-04 21:15:00 2281
2021-02-04 21:30:00 2282
2021-02-04 21:45:00 2283
2021-02-04 22:00:00 2284
2021-02-04 22:15:00 2285
2021-02-04 22:30:00 2286
2021-02-04 22:45:00 2287
2021-02-04 23:00:00 2288
2021-02-04 23:15:00 2289
2021-02-04 23:30:00 2290
2021-02-04 23:45:00 2291
2021-02-05 00:00:00 2292
2021-02-05 19:00:00 2368
2021-02-05 19:15:00 2369
2021-02-05 19:30:00 2370
2021-02-05 19:45:00 2371
2021-02-05 20:00:00 2372
2021-02-05 20:15:00 2373
2021-02-05 20:30:00 2374
2021-02-05 20:45:00 2375
2021-02-05 21:00:00 2376
2021-02-05 21:15:00 2377
2021-02-05 21:30:00 2378
2021-02-05 21:45:00 2379
2021-02-07 23:00:00 2380
2021-02-07 23:15:00 2381
2021-02-07 23:30:00 2382
2021-02-07 23:45:00 2383
2021-02-08 00:00:00 2384
2021-02-08 19:00:00 2460
2021-02-08 19:15:00 2461
2021-02-08 19:30:00 2462
2021-02-08 19:45:00 2463
2021-02-08 20:00:00 2464
2021-02-08 20:15:00 2465
2021-02-08 20:30:00 2466
2021-02-08 20:45:00 2467
2021-02-08 21:00:00 2468
2021-02-08 21:15:00 2469
2021-02-08 21:30:00 2470
2021-02-08 21:45:00 2471
2021-02-08 22:00:00 2472
2021-02-08 22:15:00 2473
2021-02-08 22:30:00 2474
2021-02-08 22:45:00 2475
2021-02-08 23:00:00 2476
2021-02-08 23:15:00 2477
2021-02-08 23:30:00 2478
2021-02-08 23:45:00 2479
2021-02-09 00:00:00 2480
2021-02-09 19:00:00 2556
2021-02-09 19:15:00 2557
2021-02-09 19:30:00 2558
2021-02-09 19:45:00 2559
2021-02-09 20:00:00 2560
2021-02-09 20:15:00 2561
2021-02-09 20:30:00 2562
2021-02-09 20:45:00 2563
2021-02-09 21:00:00 2564
2021-02-09 21:15:00 2565
2021-02-09 21:30:00 2566
2021-02-09 21:45:00 2567
2021-02-09 22:00:00 2568
2021-02-09 22:15:00 2569
2021-02-09 22:30:00 2570
2021-02-09 22:45:00 2571
2021-02-09 23:00:00 2572
2021-02-09 23:15:00 2573
2021-02-09 23:30:00 2574
2021-02-09 23:45:00 2575
2021-02-10 00:00:00 2576
2021-02-10 19:00:00 2652
2021-02-10 19:15:00 2653
2021-02-10 19:30:00 2654
2021-02-10 19:45:00 2655
2021-02-10 20:00:00 2656
2021-02-10 20:15:00 2657
2021-02-10 20:30:00 2658
2021-02-10 20:45:00 2659
2021-02-10 21:00:00 2660
2021-02-10 21:15:00 2661
2021-02-10 21:30:00 2662
2021-02-10 21:45:00 2663
2021-02-10 22:00:00 2664
2021-02-10 22:15:00 2665
2021-02-10 22:30:00 2666
2021-02-10 22:45:00 2667
2021-02-10 23:00:00 2668
2021-02-10 23:15:00 2669
2021-02-10 23:30:00 2670
2021-02-10 23:45:00 2671
2021-02-11 00:00:00 2672
2021-02-11 19:00:00 2748
2021-02-11 19:15:00 2749
2021-02-11 19:30:00 2750
2021-02-11 19:45:00 2751
2021-02-11 20:00:00 2752
2021-02-11 20:15:00 2753
2021-02-11 20:30:00 2754
2021-02-11 20:45:00 2755
2021-02-11 21:00:00 2756
2021-02-11 21:15:00 2757
2021-02-11 21:30:00 2758
2021-02-11 21:45:00 2759
2021-02-11 22:00:00 2760
2021-02-11 22:15:00 2761
2021-02-11 22:30:00 2762
2021-02-11 22:45:00 2763
2021-02-11 23:00:00 2764
2021-02-11 23:15:00 2765
2021-02-11 23:30:00 2766
2021-02-11 23:45:00 2767
2021-02-12 00:00:00 2768
2021-02-12 19:00:00 2844
2021-02-12 19:15:00 2845
2021-02-12 19:30:00 2846
2021-02-12 19:45:00 2847
2021-02-12 20:00:00 2848
2021-02-12 20:15:00 2849
2021-02-12 20:30:00 2850
2021-02-12 20:45:00 2851
2021-02-12 21:00:00 2852
2021-02-12 21:15:00 2853
2021-02-12 21:30:00 2854
2021-02-12 21:45:00 2855
2021-02-14 23:00:00 2856
2021-02-14 23:15:00 2857
2021-02-14 23:30:00 2858
2021-02-14 23:45:00 2859
2021-02-15 00:00:00 2860
2021-02-15 19:00:00 2936
2021-02-15 19:15:00 2937
2021-02-15 19:30:00 2938
2021-02-15 19:45:00 2939
2021-02-15 20:00:00 2940
2021-02-15 20:15:00 2941
2021-02-15 20:30:00 2942
2021-02-15 20:45:00 2943
2021-02-15 21:00:00 2944
2021-02-15 21:15:00 2945
2021-02-15 21:30:00 2946
2021-02-15 21:45:00 2947
2021-02-15 22:00:00 2948
2021-02-15 22:15:00 2949
2021-02-15 22:30:00 2950
2021-02-15 22:45:00 2951
2021-02-15 23:00:00 2952
2021-02-15 23:15:00 2953
2021-02-15 23:30:00 2954
2021-02-15 23:45:00 2955
2021-02-16 00:00:00 2956
2021-02-16 19:00:00 3032
2021-02-16 19:15:00 3033
2021-02-16 19:30:00 3034
2021-02-16 19:45:00 3035
2021-02-16 20:00:00 3036
2021-02-16 20:15:00 3037
2021-02-16 20:30:00 3038
2021-02-16 20:45:00 3039
2021-02-16 21:00:00 3040
2021-02-16 21:15:00 3041
2021-02-16 21:30:00 3042
2021-02-16 21:45:00 3043
2021-02-16 22:00:00 3044
2021-02-16 22:15:00 3045
2021-02-16 22:30:00 3046
2021-02-16 22:45:00 3047
2021-02-16 23:00:00 3048
2021-02-16 23:15:00 3049
2021-02-16 23:30:00 3050
2021-02-16 23:45:00 3051
2021-02-17 00:00:00 3052
2021-02-17 19:00:00 3128
2021-02-17 19:15:00 3129
2021-02-17 19:30:00 3130
2021-02-17 19:45:00 3131
2021-02-17 20:00:00 3132
2021-02-17 20:15:00 3133
2021-02-17 20:30:00 3134
2021-02-17 20:45:00 3135
2021-02-17 21:00:00 3136
2021-02-17 21:15:00 3137
2021-02-17 21:30:00 3138
2021-02-17 21:45:00 3139
2021-02-17 22:00:00 3140
2021-02-17 22:15:00 3141
2021-02-17 22:30:00 3142
2021-02-17 22:45:00 3143
2021-02-17 23:00:00 3144
2021-02-17 23:15:00 3145
2021-02-17 23:30:00 3146
2021-02-17 23:45:00 3147
2021-02-18 00:00:00 3148
2021-03-18 20:45:00 5135
2021-03-18 21:00:00 5136
2021-03-18 21:15:00 5137
2021-03-18 21:30:00 5138
2021-03-18 21:45:00 5139
2021-03-18 22:00:00 5140
2021-03-18 22:15:00 5141
2021-03-18 22:30:00 5142
2021-03-18 22:45:00 5143
2021-03-18 23:00:00 5144
2021-03-18 23:15:00 5145
2021-03-18 23:30:00 5146
2021-03-18 23:45:00 5147
2021-03-19 00:00:00 5148
2021-03-19 19:00:00 5224
2021-03-19 19:15:00 5225
2021-03-19 19:30:00 5226
2021-03-19 19:45:00 5227
2021-03-19 20:00:00 5228
2021-03-19 20:15:00 5229
2021-03-19 20:30:00 5230
2021-03-19 20:45:00 5231
2021-03-21 23:00:00 5232
2021-03-21 23:15:00 5233
2021-03-21 23:30:00 5234
2021-03-21 23:45:00 5235
2021-03-22 00:00:00 5236
2021-03-23 13:15:00 5385
2021-03-23 19:00:00 5408
2021-03-23 19:15:00 5409
2021-03-23 19:30:00 5410
2021-03-23 19:45:00 5411
2021-03-23 20:00:00 5412
2021-03-23 20:15:00 5413
2021-03-23 20:30:00 5414
2021-03-23 20:45:00 5415
2021-03-23 21:00:00 5416
2021-03-23 21:15:00 5417
2021-03-23 21:30:00 5418
2021-03-23 21:45:00 5419
2021-03-23 22:00:00 5420
2021-03-23 22:15:00 5421
2021-03-23 22:30:00 5422
2021-03-23 22:45:00 5423
2021-03-23 23:00:00 5424
2021-03-23 23:15:00 5425
2021-03-23 23:30:00 5426
2021-03-23 23:45:00 5427
2021-03-24 00:00:00 5428
2021-03-24 19:00:00 5504
2021-03-24 19:15:00 5505
2021-03-24 19:30:00 5506
2021-03-24 19:45:00 5507
2021-03-24 20:00:00 5508
2021-03-24 20:15:00 5509
2021-03-24 20:30:00 5510
2021-03-24 20:45:00 5511
2021-03-24 21:00:00 5512
2021-03-24 21:15:00 5513
2021-03-24 21:30:00 5514
2021-03-24 21:45:00 5515
2021-03-24 22:00:00 5516
2021-03-24 22:15:00 5517
2021-03-24 22:30:00 5518
2021-03-24 22:45:00 5519
2021-03-24 23:00:00 5520
2021-03-24 23:15:00 5521
2021-03-24 23:30:00 5522
2021-03-24 23:45:00 5523
2021-03-25 00:00:00 5524
2021-03-25 19:00:00 5600
2021-03-25 19:15:00 5601
2021-03-25 19:30:00 5602
2021-03-25 19:45:00 5603
2021-03-25 20:00:00 5604
2021-03-25 20:15:00 5605
2021-03-25 20:30:00 5606
2021-03-25 20:45:00 5607
2021-03-25 21:00:00 5608
2021-03-25 21:15:00 5609
2021-03-25 21:30:00 5610
2021-03-25 21:45:00 5611
2021-03-25 22:00:00 5612
2021-03-25 22:15:00 5613
2021-03-25 22:30:00 5614
2021-03-25 22:45:00 5615
2021-03-25 23:00:00 5616
2021-03-25 23:15:00 5617
2021-03-25 23:30:00 5618
2021-03-25 23:45:00 5619
2021-03-26 00:00:00 5620
2021-03-26 19:00:00 5696
2021-03-26 19:15:00 5697
2021-03-26 19:30:00 5698
2021-03-26 19:45:00 5699
2021-03-26 20:00:00 5700
2021-03-26 20:15:00 5701
2021-03-26 20:30:00 5702
2021-03-26 20:45:00 5703
2021-03-29 00:00:00 5704
2021-03-29 19:00:00 5780
2021-03-29 19:15:00 5781
2021-03-29 19:30:00 5782
2021-03-29 19:45:00 5783
2021-03-29 20:00:00 5784
2021-03-29 20:15:00 5785
2021-03-29 20:30:00 5786
2021-03-29 20:45:00 5787
2021-03-29 21:00:00 5788
2021-03-29 21:15:00 5789
2021-03-29 21:30:00 5790
2021-03-29 21:45:00 5791
2021-03-29 22:00:00 5792
2021-03-29 22:15:00 5793
2021-03-29 22:30:00 5794
2021-03-29 22:45:00 5795
2021-03-29 23:00:00 5796
2021-03-29 23:15:00 5797
2021-03-29 23:30:00 5798
2021-03-29 23:45:00 5799
2021-03-30 00:00:00 5800
2021-03-30 19:00:00 5876
2021-03-30 19:15:00 5877
2021-03-30 19:30:00 5878
2021-03-30 19:45:00 5879
2021-03-30 20:00:00 5880
2021-03-30 20:15:00 5881
2021-03-30 20:30:00 5882
2021-03-30 20:45:00 5883
2021-03-30 21:00:00 5884
2021-03-30 21:15:00 5885
2021-03-30 21:30:00 5886
2021-03-30 21:45:00 5887
2021-03-30 22:00:00 5888
2021-03-30 22:15:00 5889
2021-03-30 22:30:00 5890
2021-03-30 22:45:00 5891
2021-03-30 23:00:00 5892
2021-03-30 23:15:00 5893
2021-03-30 23:30:00 5894
2021-03-30 23:45:00 5895
2021-03-31 00:00:00 5896
2021-03-31 19:00:00 5972
2021-03-31 19:15:00 5973
2021-03-31 19:30:00 5974
2021-03-31 19:45:00 5975
2021-03-31 20:00:00 5976
2021-03-31 20:15:00 5977
2021-03-31 20:30:00 5978
2021-03-31 20:45:00 5979
2021-03-31 21:00:00 5980
2021-03-31 21:15:00 5981
2021-03-31 21:30:00 5982
2021-03-31 21:45:00 5983
2021-03-31 22:00:00 5984
2021-03-31 22:15:00 5985
2021-03-31 22:30:00 5986
2021-03-31 22:45:00 5987
2021-03-31 23:00:00 5988
2021-03-31 23:15:00 5989
2021-03-31 23:30:00 5990
2021-03-31 23:45:00 5991
2021-04-01 00:00:00 5992
2021-04-01 19:00:00 6068
2021-04-01 19:15:00 6069
2021-04-01 19:30:00 6070
2021-04-01 19:45:00 6071
2021-04-01 20:00:00 6072
2021-04-01 20:15:00 6073
2021-04-01 20:30:00 6074
2021-04-01 20:45:00 6075
2021-04-01 21:00:00 6076
2021-04-01 21:15:00 6077
2021-04-01 21:30:00 6078
2021-04-01 21:45:00 6079
2021-04-01 22:00:00 6080
2021-04-01 22:15:00 6081
2021-04-01 22:30:00 6082
2021-04-01 22:45:00 6083
2021-04-01 23:00:00 6084
2021-04-01 23:15:00 6085
2021-04-01 23:30:00 6086
2021-04-01 23:45:00 6087
2021-04-02 00:00:00 6088
2021-04-02 19:00:00 6164
2021-04-02 19:15:00 6165
2021-04-02 19:30:00 6166
2021-04-02 19:45:00 6167
2021-04-02 20:00:00 6168
2021-04-02 20:15:00 6169
2021-04-02 20:30:00 6170
2021-04-02 20:45:00 6171
2021-04-02 21:00:00 6172
2021-04-02 21:15:00 6173
2021-04-02 21:30:00 6174
2021-04-02 21:45:00 6175
2021-04-05 00:00:00 6176
2021-04-05 19:00:00 6252
2021-04-05 19:15:00 6253
2021-04-05 19:30:00 6254
2021-04-05 19:45:00 6255
2021-04-05 20:00:00 6256
2021-04-05 20:15:00 6257
2021-04-05 20:30:00 6258
2021-04-05 20:45:00 6259
2021-04-05 21:00:00 6260
2021-04-05 21:15:00 6261
2021-04-05 21:30:00 6262
2021-04-05 21:45:00 6263
2021-04-05 22:00:00 6264
2021-04-05 22:15:00 6265
2021-04-05 22:30:00 6266
2021-04-05 22:45:00 6267
2021-04-05 23:00:00 6268
2021-04-05 23:15:00 6269
2021-04-05 23:30:00 6270
2021-04-05 23:45:00 6271
2021-04-06 00:00:00 6272
2021-04-06 19:00:00 6348
2021-04-06 19:15:00 6349
2021-04-06 19:30:00 6350
2021-04-06 19:45:00 6351
signal 2021-04-08 13:00:00 6516
signal 2021-04-08 13:15:00 6517
signal 2021-04-08 13:30:00 6518
signal 2021-04-08 13:45:00 6519
signal 2021-04-08 14:00:00 6520
signal 2021-04-09 09:45:00 6599
signal 2021-04-09 10:00:00 6600
signal 2021-04-09 10:15:00 6601
signal 2021-04-09 10:30:00 6602
signal 2021-04-09 10:45:00 6603
signal 2021-04-09 11:00:00 6604
signal 2021-04-09 11:15:00 6605
signal 2021-04-09 11:30:00 6606
signal 2021-04-09 11:45:00 6607
signal 2021-04-09 12:00:00 6608
signal 2021-04-09 12:15:00 6609
signal 2021-04-09 12:30:00 6610
signal 2021-04-09 12:45:00 6611
signal 2021-04-09 13:00:00 6612
signal 2021-04-09 13:15:00 6613
signal 2021-04-09 13:30:00 6614
signal 2021-04-09 13:45:00 6615
signal 2021-04-09 14:00:00 6616
signal 2021-04-09 14:15:00 6617
signal 2021-04-09 14:30:00 6618
signal 2021-04-09 14:45:00 6619
signal 2021-04-09 15:00:00 6620
signal 2021-04-09 15:15:00 6621
signal 2021-04-09 15:30:00 6622
signal 2021-04-09 15:45:00 6623
signal 2021-04-09 16:00:00 6624
signal 2021-04-09 16:15:00 6625
signal 2021-04-09 16:30:00 6626
signal 2021-04-09 16:45:00 6627
signal 2021-04-09 17:00:00 6628
signal 2021-04-09 17:15:00 6629
signal 2021-04-09 17:30:00 6630
signal 2021-04-09 17:45:00 6631
signal 2021-04-09 18:00:00 6632
signal 2021-04-09 18:15:00 6633
signal 2021-04-09 18:30:00 6634
signal 2021-04-09 18:45:00 6635
signal 2021-04-13 09:00:00 6780
signal 2021-04-13 09:15:00 6781
signal 2021-04-13 09:30:00 6782
signal 2021-04-13 10:45:00 6787
signal 2021-04-13 11:00:00 6788
signal 2021-04-13 11:15:00 6789
signal 2021-04-13 11:30:00 6790
signal 2021-04-13 11:45:00 6791
signal 2021-04-13 12:00:00 6792
signal 2021-04-13 14:15:00 6801
signal 2021-04-13 14:30:00 6802
signal 2021-04-13 14:45:00 6803
signal 2021-04-13 15:00:00 6804
signal 2021-04-13 15:15:00 6805
signal 2021-04-13 15:30:00 6806
signal 2021-04-13 15:45:00 6807
signal 2021-04-13 16:00:00 6808
signal 2021-04-13 16:15:00 6809
signal 2021-04-13 16:30:00 6810
signal 2021-04-13 16:45:00 6811
signal 2021-04-13 17:00:00 6812
signal 2021-04-13 17:15:00 6813
signal 2021-04-13 17:30:00 6814
signal 2021-04-13 17:45:00 6815
signal 2021-04-13 18:00:00 6816
signal 2021-04-13 18:15:00 6817
signal 2021-04-13 18:30:00 6818
signal 2021-04-13 18:45:00 6819
2021-04-16 09:45:00 7071
2021-04-16 19:00:00 7108
2021-04-16 19:15:00 7109
2021-04-16 19:30:00 7110
2021-04-16 19:45:00 7111
2021-04-16 20:00:00 7112
2021-04-16 20:15:00 7113
2021-04-16 20:30:00 7114
2021-04-16 20:45:00 7115
2021-04-16 21:00:00 7116
2021-04-16 21:15:00 7117
2021-04-16 21:30:00 7118
2021-04-16 21:45:00 7119
2021-04-19 00:00:00 7120
2021-04-21 15:15:00 7373
2021-04-21 19:00:00 7388
2021-04-21 19:15:00 7389
2021-04-21 19:30:00 7390
2021-04-21 19:45:00 7391
2021-04-21 20:00:00 7392
2021-04-21 20:15:00 7393
2021-04-22 16:00:00 7472
2021-04-22 19:00:00 7484
2021-04-22 19:15:00 7485
2021-04-22 19:30:00 7486
2021-04-22 19:45:00 7487
2021-04-22 20:00:00 7488
2021-04-22 20:15:00 7489
2021-04-22 20:30:00 7490
2021-04-22 20:45:00 7491
2021-04-22 21:00:00 7492
2021-04-23 02:45:00 7515
2021-04-26 11:30:00 7638
2021-04-26 19:00:00 7668
2021-04-26 19:15:00 7669
2021-04-26 19:30:00 7670
2021-04-26 19:45:00 7671
2021-04-26 20:00:00 7672
2021-04-26 20:15:00 7673
2021-04-26 20:30:00 7674
2021-04-26 20:45:00 7675
2021-04-26 21:00:00 7676
2021-04-26 21:15:00 7677
2021-04-26 21:30:00 7678
2021-04-26 21:45:00 7679
2021-04-26 22:00:00 7680
2021-04-26 22:15:00 7681
2021-04-26 22:30:00 7682
2021-04-26 22:45:00 7683
2021-04-26 23:00:00 7684
2021-04-26 23:15:00 7685
2021-04-26 23:30:00 7686
2021-04-26 23:45:00 7687
2021-04-27 00:00:00 7688
2021-04-27 19:00:00 7764
2021-04-27 19:15:00 7765
2021-04-27 19:30:00 7766
2021-04-27 19:45:00 7767
2021-04-27 20:00:00 7768
2021-04-27 20:15:00 7769
2021-04-27 20:30:00 7770
2021-04-27 20:45:00 7771
2021-04-27 21:00:00 7772
2021-04-27 21:15:00 7773
2021-04-27 21:30:00 7774
2021-04-27 21:45:00 7775
2021-04-27 22:00:00 7776
2021-04-27 22:15:00 7777
2021-04-27 22:30:00 7778
2021-04-27 22:45:00 7779
2021-04-27 23:00:00 7780
2021-04-27 23:15:00 7781
2021-04-27 23:30:00 7782
2021-04-27 23:45:00 7783
2021-04-28 00:00:00 7784
2021-04-28 19:00:00 7860
2021-04-28 19:15:00 7861
2021-04-28 19:30:00 7862
2021-04-28 19:45:00 7863
2021-04-28 20:00:00 7864
2021-04-28 20:15:00 7865
2021-04-28 20:30:00 7866
2021-04-28 20:45:00 7867
2021-04-28 21:00:00 7868
2021-04-28 21:15:00 7869
2021-04-28 21:30:00 7870
2021-04-28 21:45:00 7871
2021-04-28 22:00:00 7872
2021-04-28 22:15:00 7873
2021-04-28 22:30:00 7874
2021-04-28 22:45:00 7875
2021-04-28 23:00:00 7876
2021-04-28 23:15:00 7877
2021-04-28 23:30:00 7878
2021-04-28 23:45:00 7879
2021-04-29 00:00:00 7880
2021-04-29 19:00:00 7956
2021-04-29 19:15:00 7957
2021-04-29 19:30:00 7958
2021-04-29 19:45:00 7959
2021-04-29 20:00:00 7960
2021-04-29 20:15:00 7961
2021-04-29 20:30:00 7962
2021-04-29 20:45:00 7963
2021-04-29 21:00:00 7964
2021-04-29 21:15:00 7965
2021-04-29 21:30:00 7966
2021-04-29 21:45:00 7967
2021-04-29 22:00:00 7968
2021-04-29 22:15:00 7969
2021-04-29 22:30:00 7970
2021-04-29 22:45:00 7971
2021-04-29 23:00:00 7972
2021-04-29 23:15:00 7973
2021-04-29 23:30:00 7974
2021-04-29 23:45:00 7975
2021-04-30 00:00:00 7976
2021-04-30 19:00:00 8052
2021-04-30 19:15:00 8053
2021-04-30 19:30:00 8054
2021-04-30 19:45:00 8055
2021-04-30 20:00:00 8056
2021-04-30 20:15:00 8057
2021-04-30 20:30:00 8058
2021-04-30 20:45:00 8059
2021-04-30 21:00:00 8060
2021-04-30 21:15:00 8061
2021-04-30 21:30:00 8062
2021-04-30 21:45:00 8063
2021-05-03 00:00:00 8064
2021-05-03 19:00:00 8140
2021-05-03 19:15:00 8141
2021-05-03 19:30:00 8142
2021-05-03 19:45:00 8143
2021-05-03 20:00:00 8144
2021-05-03 20:15:00 8145
2021-05-03 20:30:00 8146
2021-05-03 20:45:00 8147
2021-05-03 21:00:00 8148
2021-05-03 21:15:00 8149
2021-05-03 21:30:00 8150
2021-05-03 21:45:00 8151
2021-05-03 22:00:00 8152
2021-05-03 22:15:00 8153
2021-05-03 22:30:00 8154
2021-05-03 22:45:00 8155
2021-05-03 23:00:00 8156
2021-05-03 23:15:00 8157
2021-05-03 23:30:00 8158
2021-05-03 23:45:00 8159
2021-05-04 00:00:00 8160
2021-05-04 19:00:00 8236
2021-05-04 19:15:00 8237
2021-05-04 19:30:00 8238
2021-05-04 19:45:00 8239
2021-05-04 20:00:00 8240
2021-05-04 20:15:00 8241
2021-05-04 20:30:00 8242
2021-05-04 20:45:00 8243
2021-05-04 21:00:00 8244
2021-05-04 21:15:00 8245
2021-05-04 21:30:00 8246
2021-05-04 21:45:00 8247
2021-05-04 22:00:00 8248
2021-05-04 22:15:00 8249
2021-05-04 22:30:00 8250
2021-05-04 22:45:00 8251
2021-05-04 23:00:00 8252
2021-05-04 23:15:00 8253
2021-05-04 23:30:00 8254
2021-05-04 23:45:00 8255
2021-05-05 00:00:00 8256

In [10]:
len(df_m15[df_m15.TotalSignal != 0])

4363

In [11]:
df_m15['pointpos'] = df_m15.apply(lambda row: Util.pointpos(row), axis=1)

In [12]:
start_date_chart = '2023-1-1 00:00'
end_date_chart = '2023-6-30 00:00'
dfpl = df_m15.loc[start_date_chart : end_date_chart]#.set_index("Gmt time")

# Create a plot with 2 rows
fig = make_subplots(rows=1, cols=1)

# Add candlestick plot on the first row
fig.add_trace(go.Candlestick(x=dfpl.index,
                             open=dfpl['Open'],
                             high=dfpl['High'],
                             low=dfpl['Low'],
                             close=dfpl['Close']),
              row=1, col=1)

# Add markers for entry point m15
fig.add_trace(go.Scatter(x=dfpl.index, y=dfpl['pointpos'], mode="markers",
                         marker=dict(size=12, color="MediumPurple"),
                         name="entry"),
              row=1, col=1)

fig.update_layout(width=1500, height=800, sliders=[])
fig.show()

In [13]:
start_date_chart = '2023-1-1 00:00'
end_date_chart = '2023-12-30 00:00'
dfpl = df_h4.loc[start_date_chart : end_date_chart]#.set_index("Gmt time")

# Create a plot with 2 rows
fig = make_subplots(rows=1, cols=1)

# Add candlestick plot on the first row
fig.add_trace(go.Candlestick(x=dfpl.index,
                             open=dfpl['Open'],
                             high=dfpl['High'],
                             low=dfpl['Low'],
                             close=dfpl['Close']),
              row=1, col=1)

#Add markers for trade entry points on the same subplot
fig.add_trace(go.Scatter(x=dfpl.index, y=dfpl['support_point'], mode="markers",
                         marker=dict(size=8, color="green"),
                         name="support point"),
              row=1, col=1)

#Add markers for trade entry points on the same subplot
fig.add_trace(go.Scatter(x=dfpl.index, y=dfpl['resistant_point'], mode="markers",
                         marker=dict(size=8, color="red"),
                         name="resistant point"),
              row=1, col=1)

fig.update_layout(width=1200, height=800, sliders=[])
fig.show()

In [14]:
class KeyLevelChochStrat(Strategy):
    mysize = 0.5
    slcoef = 2
    TPcoef = 2
    risk_percent = 0.01
    last_swing_low = None
    last_swing_high = None
    previous_swing_low = None
    previous_swing_high = None
    entry_gap_multiplier = 0.8
    last_trade_index = 0
    dfopt = None

    stoploss_info_list = []
    valid_resistant_level = None
    valid_support_level = None

    setup_duration_gap = 60
    stoploss_window = 150
    
    def init(self):
        self.current_day = None
        self.order_placed_time = None
        self.setup_duration = None
        
        self.stoploss_info_list = []
        self.valid_resistant_level = None
        self.valid_support_level = None

        super().init()

    def reset_order(self):
        # delete placed order at the end of the day if not executed
        if self.order_placed_time:
            for order in self.orders:
                order_executed= False
                for trade in self.trades:
                    if trade.tag == order.tag:
                        order_executed = True

                if order_executed == False:
                    order.cancel()

        self.order_placed_time = None
        self.setup_duration = None
        self.valid_resistant_level = None
        self.valid_support_level = None

    def get_highest_high(self):
        return self.data.High[len(self.data.High) - self.stoploss_window : len(self.data.High)].max()

    def get_lowest_low(self):
        return self.data.Low[len(self.data.Low) - self.stoploss_window  : len(self.data.Low)].min()

    def is_entry_in_valid_short_zone(self, valid_resistant_list):
        return self.data.Close[-1] < max(valid_resistant_list) + self.data['ATR'][-1] * self.entry_gap_multiplier

    def is_entry_in_valid_long_zone(self, valid_support_list):
        return self.data.Close[-1] > min(valid_support_list) - self.data['ATR'][-1] * self.entry_gap_multiplier

    def add_stoploss_info_list(self, info):
        is_added = False
        for stoploss_info in self.stoploss_info_list:
            if stoploss_info[0] == info[0] and stoploss_info[1] == info[1]:
                is_added = True
                stoploss_info[2] = info[2]

        if is_added == False:
            self.stoploss_info_list.append(info)

    def get_stoploss_info(self, key_level_type, key_level_value):
        for stoploss_info in self.stoploss_info_list:
            if stoploss_info[0] == key_level_type and stoploss_info[1] == key_level_value:
                return stoploss_info
        return None

    def dynamic_stoploss(self):
        # delete placed order at the end of the day if not executed
        if self.order_placed_time:
            for order in self.orders:
                order_executed= False
                for trade in self.trades:
                    if trade.tag == order.tag:
                        order_executed = True
                        if order.stop is not None:
                            # in long trade, short order is for sl and inverse for short trade
                            # so we identify short order for long trade to identify sl
                            if order.is_short:
                                self.add_stoploss_info_list([Util.KeyLevel.SUPPORT, self.valid_support_level, order.stop])
                            else:
                                self.add_stoploss_info_list([Util.KeyLevel.RESISTANT, self.valid_resistant_level, order.stop])


                if order_executed == False:
                    order.cancel()
                    if order.is_short:
                        sl = abs(order.stop - self.get_highest_high())
                        tp = order.stop - self.TPcoef * sl
                        position_size = int((self.risk_percent * self.equity) / sl)
                        self.sell(sl = self.get_highest_high(), tp = tp, size=position_size, stop=order.stop)
                    else:
                        sl = abs(order.stop - self.get_lowest_low())
                        tp = order.stop + self.TPcoef * sl
                        position_size = int((self.risk_percent * self.equity) / sl)
                        order = self.buy(sl = self.get_lowest_low(), tp = tp, size=position_size, stop=order.stop)

    def get_tag(self):
        return f"{self.order_placed_time}"

    def wait_3_candles_before_new_trade(self):
        return self.last_trade_index + 3
    
    def next(self):
        super().next()
        index = len(self.data.index)

        # when an order is placed, it will be valable for 12h
        if self.setup_duration is not None and index >= self.setup_duration:
            self.reset_order()

        # place sl to the lowest/highest
        self.dynamic_stoploss()

        if len(self.trades) > 0:
            self.last_trade_index = index

        if len(self.orders)==0 and index >= self.wait_3_candles_before_new_trade():
            if self.data['TotalSignal'][-1]==1:
                valid_resistant_list = Util.get_valid_resistant_level(self.dfopt, index, breakout_candles_lookback)
                if len(valid_resistant_list) > 0:
                    valid_resistant_level = max(valid_resistant_list)
                    is_entry_in_valid_zone = self.is_entry_in_valid_short_zone(valid_resistant_list)
                    planned_entry_price = 0
                    sl = 0

                    if is_entry_in_valid_zone: 
                        planned_entry_price = self.data.Close[-1]
                        sl = abs(planned_entry_price - self.get_highest_high())
                    else :
                        planned_entry_price = valid_resistant_level + self.data['ATR'][-1] * self.entry_gap_multiplier
                        sl = abs(planned_entry_price - self.get_highest_high())
    
                    sl1 = planned_entry_price + sl
                    stoploss_info = self.get_stoploss_info(Util.KeyLevel.RESISTANT, valid_resistant_level)
                    if stoploss_info is None or sl1 > stoploss_info[2]:
                        tp = self.TPcoef * sl
                        position_size = int((self.risk_percent * self.equity) / sl)
                        tp1 = planned_entry_price - tp

                        self.valid_resistant_level = valid_resistant_level
                        self.setup_duration = len(self.data.index) + self.setup_duration_gap
                        self.order_placed_time = self.data.index[-1]

                        if is_entry_in_valid_zone: 
                            self.sell(sl=sl1, tp=tp1, size=position_size, tag=self.get_tag())
                            # print(f"short {self.data.index[-1]} sl = {sl1} & sgnal = {self.signal1[-1]} & valid_resistant_level = {valid_resistant_level} & entry_price = {planned_entry_price}")
                        else:
                            self.sell(sl=sl1, tp=tp1, size=position_size, stop=planned_entry_price, tag=self.get_tag())
                            # print(f"short {self.data.index[-1]} sl = {sl1} & sgnal = {self.signal1[-1]} & valid_resistant_level = {valid_resistant_level} & planned_entry_price = {planned_entry_price}")

            if self.data['TotalSignal'][-1]==2:
                valid_support_list = Util.get_valid_support_level(self.dfopt, index, breakout_candles_lookback)
                if len(valid_support_list) > 0:
                    valid_support_level = min(valid_support_list)
                    is_entry_in_valid_zone = self.is_entry_in_valid_long_zone(valid_support_list)
                    planned_entry_price = 0
                    sl = 0
                    
                    if is_entry_in_valid_zone: 
                        planned_entry_price = self.data.Close[-1]
                        sl = abs(planned_entry_price - self.get_lowest_low())
                    else :
                        planned_entry_price = valid_support_level - self.data['ATR'][-1] * self.entry_gap_multiplier
                        sl = abs(planned_entry_price - self.get_lowest_low())

                    sl1 = planned_entry_price - sl
                    stoploss_info = self.get_stoploss_info(Util.KeyLevel.SUPPORT, valid_support_level)
                    # print(f"{stoploss_info} {valid_support_level}")
                    if stoploss_info is None or sl1 < stoploss_info[2]:
                        tp = self.TPcoef * sl
                        position_size = int((self.risk_percent * self.equity) / sl)
                        tp1 = planned_entry_price + tp

                        self.valid_support_level = valid_support_level
                        self.setup_duration = len(self.data.index) + self.setup_duration_gap
                        self.order_placed_time = self.data.index[-1]

                        if is_entry_in_valid_zone: 
                            self.buy(sl=sl1, tp=tp1, size=position_size, tag=self.get_tag())
                            # print(f"long {self.data.index[-1]} sl = {sl1} & sgnal = {self.signal1[-1]} & valid_support_level = {valid_support_level} & entry_price = {planned_entry_price}")
                        else:
                            self.buy(sl=sl1, tp=tp1, size=position_size, stop=planned_entry_price, tag=self.get_tag())
                            # print(f"long {self.data.index[-1]} sl = {sl1} & sgnal = {self.signal1[-1]} & valid_support_level = {valid_support_level} & planned_entry_price = {planned_entry_price}")

In [17]:
start_date_chart = '2021-1-1 00:00'
end_date_chart = '2026-12-30 00:00'
global_dfopt = df_m15.loc[start_date_chart : end_date_chart]

bt = Backtest(global_dfopt, KeyLevelChochStrat, cash=10000, margin=0.005, finalize_trades=True) #0.0002
stats = bt.run(dfopt=global_dfopt)

print(stats)
bt.plot()

Start                     2021-01-03 23:00:00
End                       2026-09-16 00:00:00
Duration                   2081 days 01:00:00
Exposure Time [%]                    15.55392
Equity Final [$]                   8695.12261
Equity Peak [$]                    10013.6544
Return [%]                          -13.04877
Buy & Hold Return [%]                -15.2726
Return (Ann.) [%]                    -2.17143
Volatility (Ann.) [%]                 5.31732
CAGR [%]                             -2.42421
Sharpe Ratio                         -0.40837
Sortino Ratio                        -0.53798
Calmar Ratio                         -0.09497
Alpha [%]                           -12.70911
Beta                                  0.02224
Max. Drawdown [%]                   -22.86328
Avg. Drawdown [%]                   -22.86328
Max. Drawdown Duration     2055 days 06:00:00
Avg. Drawdown Duration     2055 days 06:00:00
# Trades                                   92
Win Rate [%]                         28.26087
Best Trade [%]                        2.72551
Worst Trade [%]                      -0.96681
Avg. Trade [%]                       -0.02561
Max. Trade Duration          48 days 10:30:00
Avg. Trade Duration           3 days 11:31:00
Profit Factor                         0.90845
Expectancy [%]                       -0.02364
SQN                                  -1.14779
Kelly Criterion                      -0.08213
_strategy                 KeyLevelChochStr...
_equity_curve                             ...
_trades                        Size  Entry...
dtype: object

c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\_plotting.py:141: UserWarning: Data contains too many candlesticks to plot; downsampling to '8h'. See `Backtest.plot(resample=...)`
  warnings.warn(f"Data contains too many candlesticks to plot; downsampling to {freq!r}. "

GridPlot(id='p1829', ...)

In [18]:
# add some sl tp management

class RandomStrat(Strategy):
    mysize = 0.5
    slcoef = 2
    TPcoef = 2
    risk_percent = 0.01
    trades_list = None
    stoploss_window = 150

    def is_signal(self, date):
        for i in range(0, len(self.trades_list)):
            if self.trades_list[i] == date:
                return True
        return False

    def get_highest_high(self):
        return self.data.High[len(self.data.High) - self.stoploss_window : len(self.data.High)].max()
    
    def get_lowest_low(self):
        return self.data.Low[len(self.data.Low) - self.stoploss_window : len(self.data.Low)].min()
    
    def init(self):
        super().init()

    def get_sl(self):
        return round(random.uniform(self.data['ATR'][-1]*1,self.data['ATR'][-1]*2.5), 5)

    def next(self):
        super().next()
        if self.is_signal(self.data.index[-1]) and len(self.trades) == 0 and len(self.closed_trades) < 92:
            direction = randint(1,2)
            if direction == 1:
                planned_entry_price = self.data.Close[-1]
                sl = abs(planned_entry_price - self.get_lowest_low())
                if sl == 0:
                    sl = self.get_sl()
                tp = self.TPcoef * sl

                sl1 = planned_entry_price - sl
                tp1 = planned_entry_price + tp
                position_size = int((self.risk_percent * self.equity) / sl)
                # max_affordable_size = int((self.equity * 0.99) / planned_entry_price)
                # print(f'{position_size} {max_affordable_size}')

                self.buy(sl=sl1, tp=tp1, size=position_size)
            else:
                planned_entry_price = self.data.Close[-1]
                sl = abs(planned_entry_price - self.get_highest_high())
                if sl == 0:
                    sl = self.get_sl()
                tp = self.TPcoef * sl

                sl1 = planned_entry_price + sl
                tp1 = planned_entry_price - tp
                position_size = int((self.risk_percent * self.equity) / sl)
                # max_affordable_size = int((self.equity * 0.99) / planned_entry_price)
                # print(f'{position_size} {max_affordable_size}')

                self.sell(sl=sl1, tp=tp1, size=position_size)

In [24]:
trades_list = []
while len(trades_list) != 125:
    random_index = randint(0, len(df_m15))
    candle = df_m15.iloc[random_index]
    # exclu Saturday and Sunday
    if candle.name.weekday() < 5:
        if 9 <= candle.name.hour and candle.name.hour <= 19:
            trades_list.append(candle.name)
trades_list.sort()

bt = Backtest(df_m15, RandomStrat, cash=10000, margin=0.005, finalize_trades=True) #0.0002
stats = bt.run(trades_list=trades_list)

print(stats)

bt.plot()

c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\backtesting.py:1009: UserWarning: time=113983: Broker canceled the order due to insufficient margin (equity=9335.49, margin_available=9335.49).
  warnings.warn(

Start                     2021-01-03 23:00:00
End                       2026-09-16 00:00:00
Duration                   2081 days 01:00:00
Exposure Time [%]                    23.00327
Equity Final [$]                   9688.82734
Equity Peak [$]                   10318.47783
Return [%]                           -3.11173
Buy & Hold Return [%]                -15.2726
Return (Ann.) [%]                     -0.4951
Volatility (Ann.) [%]                 5.73493
CAGR [%]                             -0.55329
Sharpe Ratio                         -0.08633
Sortino Ratio                        -0.12881
Calmar Ratio                         -0.03814
Alpha [%]                            -3.61108
Beta                                  -0.0327
Max. Drawdown [%]                   -12.98034
Avg. Drawdown [%]                    -1.31898
Max. Drawdown Duration     1013 days 13:00:00
Avg. Drawdown Duration       75 days 21:28:00
# Trades                                   92
Win Rate [%]                          32.6087
Best Trade [%]                         7.5931
Worst Trade [%]                      -1.29996
Avg. Trade [%]                        0.02121
Max. Trade Duration         171 days 20:00:00
Avg. Trade Duration           5 days 05:53:00
Profit Factor                         1.09484
Expectancy [%]                        0.02625
SQN                                  -0.23771
Kelly Criterion                      -0.01766
_strategy                 RandomStrat(trad...
_equity_curve                             ...
_trades                         Size  Entr...
dtype: object

c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\_plotting.py:141: UserWarning: Data contains too many candlesticks to plot; downsampling to '8h'. See `Backtest.plot(resample=...)`
  warnings.warn(f"Data contains too many candlesticks to plot; downsampling to {freq!r}. "

GridPlot(id='p3533', ...)

In [25]:
i = 0
expectancy_list = []
winrate_list = []
number_trades = []

while len(expectancy_list) < 1000:
    trades_list = []
    while len(trades_list) != 125:
        random_index = randint(0, len(df_m15)-1)
        candle = df_m15.iloc[random_index -1]
        # exclu Saturday and Sunday
        if candle.name.weekday() < 5:
            if 9 <= candle.name.hour and candle.name.hour <= 19:
                trades_list.append(candle.name)
    trades_list.sort()

    bt = Backtest(df_m15, RandomStrat, cash=10000, margin=0.0009, finalize_trades=True) #0.0002
    stats = bt.run(trades_list=trades_list)
    if stats['# Trades'] == 92:
        expectancy_list.append(stats['Expectancy [%]'])
        winrate_list.append(stats['Win Rate [%]'])
        number_trades.append(stats['# Trades'])
        print(f'{i} {len(expectancy_list)} {stats['Expectancy [%]']} Done')
    i += 1

print(expectancy_list)

0 1 -0.00881334090899309 Done
1 2 -0.11712201901315354 Done
3 3 -0.12399877640231036 Done
7 4 -0.04261260222988561 Done
10 5 -0.14737783748654315 Done
11 6 -0.041967979694688656 Done
12 7 0.0013183713930174585 Done
15 8 -0.03552873677597092 Done
16 9 -0.0223855980882275 Done
17 10 0.08997040131637164 Done
19 11 -0.16236075345679168 Done
20 12 -0.0214471486341899 Done
21 13 0.0471007810727827 Done
22 14 -0.0796222904500601 Done
26 15 0.05238179137494241 Done
31 16 -0.05688316436611959 Done
32 17 -0.03278968068854319 Done
33 18 -0.13326357278840065 Done
34 19 -0.05219414041847477 Done
35 20 -0.17113116009130022 Done
36 21 -0.13044348689360938 Done
37 22 -0.06761674724225979 Done
38 23 -0.03947140349411491 Done
39 24 -0.1302455097809352 Done
44 25 -0.09280146318316039 Done
45 26 0.0014824108019892786 Done
46 27 0.04256199380299511 Done
47 28 0.0007727761368052789 Done
50 29 -0.09244627828403786 Done
51 30 -0.08400287891881374 Done
52 31 0.18716682567957577 Done
55 32 0.03652986485078688 Done
56 33 -0.04399258144889188 Done
57 34 0.14125184409869887 Done
58 35 0.03386975708797711 Done
60 36 -0.21135847647455103 Done
61 37 0.07537064493319293 Done
64 38 -0.052470799689653375 Done
65 39 0.07729719007589918 Done
66 40 -0.13641689648446076 Done
67 41 0.012726732546647598 Done
68 42 -0.1319726625389971 Done
69 43 -0.07753584285086514 Done
71 44 -0.018286963686738468 Done
73 45 0.04204712154689587 Done
74 46 0.025844351461520747 Done
75 47 -0.16902085693340554 Done
77 48 0.12259968716078992 Done
78 49 -0.06785526362699125 Done
81 50 -0.0998691998662014 Done
83 51 -0.016617396764245663 Done
84 52 -0.04047902864850172 Done
85 53 -0.14100075909124704 Done
86 54 0.01804163460218099 Done
87 55 -0.14028334658685232 Done
88 56 -0.07493823720345048 Done
89 57 -0.06555904132292655 Done
90 58 0.08166174385342562 Done
91 59 -0.07855246791164877 Done
93 60 -0.004121815364063873 Done
95 61 -0.06099618339032491 Done
97 62 -0.05491015206959525 Done
99 63 -0.045910064219388716 Done
104 64 -0.016635970097535504 Done
105 65 -0.2529903653774764 Done
106 66 -0.09080082460808767 Done
108 67 -0.05282319608632101 Done
113 68 -0.06100348960070013 Done
115 69 -0.08482146488006466 Done
116 70 -0.11627625197241111 Done
117 71 0.023013439109765447 Done
118 72 0.09652665790412819 Done
120 73 -0.032639164075234324 Done
122 74 0.10084681268765894 Done
126 75 -0.1044566761439465 Done
128 76 -0.1287391875303552 Done
129 77 -0.0654875836039686 Done
131 78 -0.05879780955717569 Done
132 79 0.0042053157976195766 Done
133 80 -0.05054820582066428 Done
134 81 -0.04445781483184492 Done
136 82 0.010563360595004366 Done
137 83 -0.14861220763110702 Done
140 84 0.07415273452226358 Done
141 85 -0.11002015052041611 Done
142 86 -0.20983589245024475 Done
143 87 0.03153834960708088 Done
144 88 -0.09233828203559682 Done
145 89 0.045171827828508655 Done
146 90 -0.06042344747321407 Done
147 91 -0.038834996647062255 Done
148 92 -0.08876253002931206 Done
151 93 -0.023981851542869883 Done
152 94 -0.19265838801331026 Done
153 95 -0.06161931194462721 Done
155 96 -0.08344832302785782 Done
157 97 0.0009325857617956968 Done
158 98 -0.18325147072787382 Done
159 99 -0.22058966610788072 Done
163 100 -0.17793812388127028 Done
165 101 -0.04594807995539123 Done
166 102 -0.056184724377079165 Done
169 103 -0.04600527394303147 Done
174 104 -0.0771359024334804 Done
176 105 0.0034111795168000002 Done
177 106 0.006622565951385242 Done
179 107 -0.010949756082496926 Done
180 108 -0.1342971028144321 Done
184 109 -0.06150823366493737 Done
185 110 -0.11773577089187205 Done
187 111 -0.02199912317420908 Done
188 112 0.03989311771065755 Done
190 113 -0.1622300744557333 Done
191 114 0.07927388486207937 Done
192 115 -0.10184953609945094 Done
195 116 -0.024986207366453145 Done
196 117 -0.058416403155337526 Done
197 118 -0.12955775814313542 Done
198 119 0.04052625405265394 Done
199 120 -0.09560639207003709 Done
201 121 -0.03574289585267401 Done
202 122 0.13523534715582544 Done
203 123 -0.2052228482429419 Done
204 124 0.014252282512226157 Done
205 125 0.05709079952825421 Done
206 126 -0.2188958872076169 Done
209 127 -0.043382220173106584 Done
210 128 -0.05185299590157394 Done
211 129 0.07710135651396516 Done
213 130 0.0734220409845653 Done
214 131 -0.040464750460556705 Done
215 132 -0.08482332965757569 Done
218 133 -0.021836267077402542 Done
219 134 -0.003945886751755725 Done
220 135 0.043697587450007874 Done
222 136 0.086076941404801 Done
223 137 -0.05958664209746915 Done
226 138 0.033590760723968854 Done
229 139 0.026751688617174134 Done
234 140 -0.1569918214274844 Done
235 141 -0.20483027250327532 Done
237 142 0.04227682114588441 Done
238 143 -0.0646078251804843 Done
239 144 -0.1113542183615239 Done
241 145 -0.06526027169376189 Done
243 146 -0.08803965958849375 Done
244 147 0.018708455425264538 Done
245 148 -0.1284044810598687 Done
247 149 -0.028441238284331826 Done
249 150 -0.05113520070710671 Done
250 151 -0.03203554684057687 Done
251 152 -0.17997132536448876 Done
253 153 0.07613503466869617 Done
254 154 0.04083208888805037 Done
255 155 -0.035738376405424474 Done
256 156 -0.03620741382342329 Done
257 157 -0.1485924840832045 Done
258 158 -0.0673717737707202 Done
260 159 -0.06101822665798828 Done
263 160 -0.208119689332329 Done
264 161 -0.07760406107141696 Done
265 162 -0.03713797110330479 Done
266 163 -0.03913231857647106 Done
268 164 -0.06746232491604554 Done
269 165 -0.025266982165747156 Done
270 166 -0.08859461256413968 Done
273 167 -0.05809890827332397 Done
276 168 -0.04465895480278884 Done
277 169 -0.1258564275792369 Done
281 170 -0.14443188142945085 Done
284 171 -0.04688106295181194 Done
290 172 0.00334317106443747 Done
292 173 -0.10924803463274264 Done
293 174 -0.1835223803606099 Done
294 175 0.053799389057126515 Done
295 176 -0.11226466678650893 Done
297 177 -0.18655650567925902 Done
301 178 -0.10335088678389837 Done
302 179 -0.20676019974870985 Done
303 180 -0.14379584784236402 Done
304 181 -0.04067676618734569 Done
306 182 -0.0504894963125661 Done
308 183 -0.1381447025413511 Done
309 184 -0.14471378601801016 Done
311 185 -0.034886407563892455 Done
314 186 -0.012084049382841543 Done
315 187 -0.023652716232612683 Done
316 188 0.09569433193896161 Done
318 189 -0.0347900060634174 Done
319 190 -0.11107761651281761 Done
321 191 -0.04671472046029987 Done
324 192 -0.11842552524427105 Done
326 193 -0.11275427475728111 Done
327 194 0.024756881176913253 Done
328 195 -0.03195063385142863 Done
329 196 -0.045423253862757015 Done
330 197 -0.12516471608984533 Done
331 198 -0.1496989762175748 Done
332 199 0.03965249995771621 Done
334 200 0.08341918158614386 Done
336 201 -0.038315481207816464 Done
337 202 0.11951570064329783 Done
339 203 -0.003314184231284851 Done
340 204 0.02755776810054685 Done
341 205 0.021512886820221587 Done
342 206 -0.13731277186121896 Done
343 207 -0.0915085615566703 Done
347 208 -0.061282836286499165 Done
349 209 -0.007103059399784458 Done
351 210 0.058208909276357516 Done
352 211 -0.13869054340190223 Done
354 212 0.07350526068605576 Done
355 213 0.01089989863898722 Done
356 214 0.03841449620690204 Done
359 215 0.12745164514862828 Done
360 216 -0.017306136515369684 Done
361 217 0.02362753922402797 Done
362 218 -0.08093351362891579 Done
364 219 -0.02435393980246474 Done
365 220 -0.0770283110774825 Done
367 221 -0.12518720679359122 Done
369 222 -0.0872014499188633 Done
370 223 0.01663828416673469 Done
371 224 0.009682476197029864 Done
374 225 -0.04544301415165493 Done
375 226 -0.08335957714121404 Done
377 227 -0.059877718750479626 Done
378 228 -0.17239412465373405 Done
379 229 -0.0202104704615173 Done
380 230 -0.13627526840287668 Done
381 231 -0.02654855602805998 Done
383 232 -0.03477516338670543 Done
386 233 0.07591540089442232 Done
388 234 -0.008883558000339522 Done
390 235 -0.05014742248784968 Done
392 236 0.03129990271109533 Done
399 237 -0.14394669780897823 Done
400 238 -0.00011158828637116896 Done
401 239 -0.04414138537609826 Done
402 240 -0.05129673235597895 Done
404 241 -0.017655050774782684 Done
406 242 0.0009694692274919461 Done
407 243 -0.013323779358692545 Done
408 244 -0.22193821161602725 Done
411 245 0.022997200557015766 Done
413 246 0.006501789730329984 Done
414 247 0.03799180613437944 Done
415 248 -0.06252210950048429 Done
416 249 -0.03322514813777006 Done
418 250 -0.16177759681243367 Done
420 251 -0.06598600668543989 Done
421 252 0.10125948143133384 Done
422 253 0.08192395369528596 Done
425 254 0.007508104352370859 Done
426 255 -0.008256474151947378 Done
428 256 -0.08366725045324395 Done
429 257 0.020721212151248496 Done
430 258 0.052480726659445934 Done
431 259 0.0814788068343554 Done
433 260 -0.07849396171615129 Done
435 261 -0.14304009834266826 Done
436 262 -0.044361016661581903 Done
437 263 -0.13270682832906602 Done
440 264 -0.022080238075473876 Done
441 265 -0.06598219915746907 Done
442 266 -0.049700713640862204 Done
443 267 0.008771839838842362 Done
445 268 0.00033082548668138197 Done
446 269 -0.07417690199887216 Done
448 270 -0.013296167490668274 Done
449 271 -0.10689538371302086 Done
450 272 -0.007860267477946426 Done
454 273 0.03532811989215012 Done
455 274 -0.0506150955645612 Done
456 275 -0.15281740438312943 Done
460 276 0.08282214433843194 Done
461 277 -0.13781794864151362 Done
462 278 -0.09890930399349275 Done
465 279 0.0282578669867872 Done
469 280 -0.08141947911848399 Done
470 281 0.014118815465424334 Done
472 282 0.05400536039980863 Done
475 283 0.010112794594507746 Done
477 284 -0.0032271281120136008 Done
480 285 -0.11403196950100418 Done
481 286 0.0053717234647549204 Done
482 287 -0.1356423684227816 Done
486 288 0.058640283958626326 Done
487 289 0.05991110498021479 Done
489 290 -0.11022332744814141 Done
490 291 -0.277442104297038 Done
491 292 -0.0808310552263191 Done
494 293 0.039833959362628575 Done
495 294 -0.11197489338072104 Done
496 295 -0.030787060575466135 Done
497 296 0.013702009728312817 Done
499 297 -0.1285496433853344 Done
500 298 0.025212301019472694 Done
501 299 -0.15908278448367813 Done
503 300 0.026659346005429393 Done
504 301 -0.0014017007996472068 Done
505 302 -0.04188001847663887 Done
507 303 -0.21493053758733033 Done
508 304 -0.23598098438706658 Done
509 305 -0.12729986657119552 Done
512 306 -0.008728937588492951 Done
514 307 0.03560796074355458 Done
515 308 -0.07688809733792402 Done
516 309 -0.1158415965725019 Done
519 310 -0.0987115566729278 Done
520 311 0.024607358062684978 Done
523 312 -0.1368299219340178 Done
524 313 -0.13403384825334141 Done
525 314 0.004550918578176592 Done
526 315 -0.17293712907881462 Done
528 316 -0.015698205222487053 Done
530 317 -0.027113836590586644 Done
531 318 -0.07940314734445306 Done
535 319 -0.10005245882874866 Done
536 320 0.02277578759269203 Done
538 321 -0.08382529605761024 Done
539 322 -0.13006639781508372 Done
540 323 -0.05066166356794194 Done
541 324 -0.11938252648830816 Done
542 325 -0.0939283593335383 Done
544 326 0.15743101005210097 Done
545 327 -0.031516632201792155 Done
546 328 -0.10095138787260996 Done
549 329 -0.07757926042284943 Done
552 330 -0.07833906142746551 Done
554 331 -0.055840971877305315 Done
556 332 -0.10331650431323433 Done
557 333 -0.07730534042029423 Done
559 334 0.057794192605441524 Done
560 335 -0.061531542171732206 Done
561 336 -0.033620044428020954 Done
562 337 -0.1354971512566847 Done
563 338 -0.10923954443259454 Done
564 339 -0.0781450683532098 Done
566 340 -0.04429370149473569 Done
568 341 -0.0687140751505969 Done
570 342 -0.08379011864717241 Done
572 343 -0.08264967632314481 Done
575 344 -0.04997322099747964 Done
576 345 0.01676642842917686 Done
577 346 0.035352600659270116 Done
579 347 0.13799797520651974 Done
580 348 -0.1044552146073749 Done
584 349 -0.03730394876610409 Done
586 350 -0.11311727937987781 Done
587 351 -0.08712309573219192 Done
589 352 -0.09734672282103198 Done
593 353 -0.21819606519181772 Done
594 354 0.05061386654755131 Done
600 355 2.1827658101402708e-05 Done
601 356 -0.019550377215388094 Done
605 357 0.0033752671089283593 Done
606 358 -0.028675780704861015 Done
608 359 0.02008744812997374 Done
609 360 0.06124513323578194 Done
612 361 0.0765876316994684 Done
614 362 0.0852948738308572 Done
615 363 0.08718295080954706 Done
617 364 0.0771639047757547 Done
618 365 -0.03409524546946992 Done
619 366 -0.07424946886827068 Done
621 367 -0.1076355633464036 Done
622 368 0.006795820380810889 Done
625 369 -0.087938066962085 Done
627 370 -0.05363967143734209 Done
629 371 -0.1444647819141902 Done
630 372 -0.11989981437262863 Done
631 373 -0.1064270140231825 Done
635 374 -0.06523078786232193 Done
636 375 0.06164663995939296 Done
639 376 -0.040741853819188115 Done
640 377 -0.03722256098533202 Done
643 378 -0.07719344749876175 Done
645 379 -0.10827700961349163 Done
648 380 0.013192128957235262 Done
649 381 -0.049385425830141896 Done
650 382 -0.09936587524964939 Done
654 383 -0.05051332267221066 Done
655 384 -0.01829355326637935 Done
656 385 0.03645278967628992 Done
657 386 0.01459140967338281 Done
659 387 -0.16457171241779536 Done
660 388 0.05118541808894749 Done
663 389 -0.06654321925096661 Done
664 390 -0.061145452950431764 Done
666 391 0.0028185352992966396 Done
668 392 -0.14865600220204245 Done
669 393 -0.1515789109198448 Done
670 394 0.020775805630951615 Done
675 395 -0.05002096977446533 Done
676 396 0.02905543296086673 Done
677 397 -0.11944915973448975 Done
678 398 -0.085117255578093 Done
680 399 -0.149151525092181 Done
682 400 0.016525016943218288 Done
683 401 -0.07809857646037859 Done
686 402 0.04885834558025589 Done
688 403 -0.07525940280118672 Done
689 404 -0.024202750927794444 Done
691 405 -0.14516055946822884 Done
692 406 -0.15300362111077354 Done
693 407 -0.17874398140669945 Done
694 408 -0.1970003052376046 Done
696 409 -0.040546928687328246 Done
697 410 -0.04719785677912799 Done
699 411 0.009809370989944074 Done
700 412 0.0061333669740457905 Done
701 413 0.02768187548070272 Done
702 414 0.000573129147193029 Done
703 415 -0.016539711859772654 Done
706 416 -0.03377097641947305 Done
708 417 -0.15291813541759014 Done
709 418 -0.036217864496511556 Done
713 419 -0.08283863300404236 Done
715 420 -0.12484153426775267 Done
718 421 0.04529443347224959 Done
719 422 0.013253463761072082 Done
720 423 -0.17845059962659518 Done
721 424 -0.1319262369648412 Done
722 425 -0.07052653661543624 Done
725 426 -0.026393885022053268 Done
726 427 -0.019989777239349298 Done
727 428 -0.08165353904335514 Done
728 429 -0.07167018525018899 Done
730 430 -0.025856093165855413 Done
731 431 0.024707890425650622 Done
732 432 0.009755336332542431 Done
734 433 -0.11720272103530617 Done
735 434 -0.011095319715648859 Done
736 435 0.0004190145606664941 Done
738 436 -0.06654411525587225 Done
739 437 0.13310913255648146 Done
740 438 -0.03140663148530065 Done
741 439 -0.0042390961205798165 Done
742 440 -0.08937193028559752 Done
744 441 -0.04349112021701844 Done
745 442 -0.0021677704642622166 Done
751 443 -0.026045519794059387 Done
752 444 0.11973708463210272 Done
753 445 -0.008583562743550963 Done
754 446 -0.031003790523455005 Done
755 447 -0.1694248582082529 Done
756 448 -0.0704745847702719 Done
757 449 0.08861485031491054 Done
760 450 -0.028779044608464543 Done
761 451 -0.11099234585386279 Done
762 452 0.019201383834312854 Done
763 453 -0.14111837517684936 Done
764 454 0.06390572080795592 Done
767 455 -0.19523769846088154 Done
768 456 0.016171441996780812 Done
769 457 -0.06146234696669757 Done
770 458 -0.12973106787746919 Done
771 459 -0.020555941950689792 Done
773 460 -0.0888315499499481 Done
775 461 -0.05748184992559492 Done
776 462 -0.15382449593581102 Done
777 463 -0.09442743848850729 Done
780 464 -0.07627968482892954 Done
781 465 0.04088919433202945 Done
784 466 -0.14626136604576767 Done
786 467 0.02485459203553014 Done
789 468 -0.11893590320691684 Done
791 469 -0.07538294319963221 Done
792 470 -0.18263091862412223 Done
794 471 0.07843415745314032 Done
795 472 0.024068038017534207 Done
796 473 -0.01172678871918894 Done
798 474 0.11008224266552487 Done
800 475 -0.1631844750334707 Done
801 476 -0.17929310138580004 Done
805 477 -0.0434466949832392 Done
806 478 -0.001582302097932753 Done
808 479 -0.13804759365083208 Done
810 480 -0.04693266372301738 Done
814 481 0.02330474483896715 Done
817 482 -0.04674129418238186 Done
818 483 -0.07667717337526704 Done
819 484 0.011941757402925498 Done
823 485 0.10153502432605874 Done
824 486 -0.1354000933691618 Done
825 487 -0.04069579377333548 Done
826 488 -0.04342472218166579 Done
828 489 0.0233217572690678 Done
829 490 0.05121942401660702 Done
830 491 0.021838629919804595 Done
833 492 0.04030128109816897 Done
834 493 -0.0856622368873444 Done
836 494 -0.06680290867330688 Done
838 495 -0.10038892834283177 Done
839 496 -0.10909917539058231 Done
840 497 -0.0879534364250669 Done
841 498 0.01803486343831769 Done
843 499 -0.11176072564521455 Done
845 500 -0.19104299210528486 Done
848 501 -0.032981562940971904 Done
850 502 -0.1647614331943105 Done
851 503 -0.05234089959265713 Done
852 504 -0.10174734223463155 Done
854 505 -0.07934498491700957 Done
855 506 0.012719629036411894 Done
856 507 -0.047930260408300854 Done
857 508 -0.11524684877274739 Done
859 509 -0.192277061507847 Done
860 510 0.06972166616057779 Done
862 511 -0.029150646795513654 Done
864 512 -0.03791128988380224 Done
867 513 0.05223685325648848 Done
871 514 -0.18856899056095688 Done
874 515 -0.09025913312110487 Done
875 516 0.007612826847699324 Done
876 517 -0.11579056011080126 Done
879 518 0.05763482715173214 Done
880 519 -0.015177116924299384 Done
882 520 0.0510947345473876 Done
883 521 -0.00786866825056612 Done
885 522 0.025131298901769496 Done
886 523 -0.02436412248301615 Done
887 524 -0.009880092491173208 Done
888 525 0.11466445147834028 Done
889 526 -0.09117346519688808 Done
891 527 -0.05066379168121836 Done
893 528 0.18810983553975655 Done
894 529 -0.09348204513093829 Done
895 530 -0.10037375185736029 Done
896 531 -0.07972822410097405 Done
897 532 -0.09353007935065298 Done
898 533 -0.025674399126221128 Done
899 534 -0.054018990908738636 Done
900 535 -0.08686684018094698 Done
901 536 0.0378494382683754 Done
902 537 -0.07602638709309796 Done
903 538 0.005614453256515333 Done
905 539 -0.09297768345637579 Done
906 540 -0.027897299216418467 Done
909 541 -0.10920209512608856 Done
911 542 -0.016334585608004333 Done
912 543 0.19796365037874597 Done
914 544 -0.07869542434072875 Done
917 545 0.013554499588774738 Done
919 546 -0.13413131100053693 Done
921 547 -0.08233523352858335 Done
922 548 -0.030411252158177787 Done
923 549 0.07091628039542135 Done
924 550 -0.054723153582031274 Done
925 551 0.08801331564544788 Done
926 552 -0.09599479562572517 Done
927 553 -0.09671150631507784 Done
928 554 -0.07706865425984781 Done
929 555 0.07337923214382855 Done
931 556 0.21408115114562226 Done
932 557 -0.16930196007667828 Done
934 558 -0.017628183716319176 Done
935 559 -0.13887902527113444 Done
936 560 -0.04419022514231927 Done
938 561 -0.2572151751526606 Done
939 562 -0.07029069008063035 Done
940 563 -0.027826403066859837 Done
941 564 -0.17601417025223617 Done
943 565 0.07536318072096371 Done
947 566 -0.011083582663529639 Done
948 567 0.012985152872767726 Done
952 568 -0.09849149549840217 Done
953 569 -0.012919092818739654 Done
955 570 -0.14209487980790633 Done
956 571 0.011664560523128876 Done
958 572 -0.18090284817755348 Done
959 573 -0.11243906933545808 Done
960 574 -0.08983015270815305 Done
964 575 -0.032710483142076634 Done
965 576 -0.015337967077153793 Done
966 577 0.040728536455715135 Done
968 578 -0.18523782536677075 Done
969 579 0.015135474594789975 Done
970 580 -0.16323574629971452 Done
971 581 -0.12569068278992718 Done
972 582 0.007571687593069616 Done
973 583 -0.1079024604861641 Done
974 584 -0.08072870348734358 Done
975 585 -0.1763355344733287 Done
976 586 -0.06552290353239237 Done
980 587 -0.04178509759890225 Done
981 588 0.07187219318164205 Done
984 589 -0.09885791183940401 Done
986 590 0.03191172826500233 Done
987 591 0.02502425830028219 Done
990 592 0.06149402650754988 Done
992 593 -0.11590088891593295 Done
993 594 -0.030959310079003387 Done
994 595 -0.11928202367447666 Done

In [26]:
print(len(expectancy_list))

p95 = np.percentile(expectancy_list, 95)                  # ngưỡng phân vị 95
print(f"p95 = {p95}")
# max_expectancy = max(expectancy_list_2)
print(f"max = {max(expectancy_list)}")
mean_expectancy = np.mean(expectancy_list)
print(f"mean = {mean_expectancy}")
print(f"min = {min(expectancy_list)}")
print(f"gap = {-0.02364 - mean_expectancy}")

df_result = pd.DataFrame({'expectancy' : expectancy_list})
rank = (df_result['expectancy'] <= -0.02364).mean() * 100 
print(f"rank = {rank}")
p_value = ((df_result['expectancy'] >= -0.02364).sum() + 1) / (len(df_result['expectancy']) + 1)
print(f"p_value = {p_value}")

print(len(winrate_list))

p95_winrate = np.percentile(winrate_list, 95)                  # ngưỡng phân vị 95
print(f"p95 = {p95_winrate}")
# max_expectancy = max(expectancy_list_2)
print(f"max = {max(winrate_list)}")
mean_winrate = np.mean(winrate_list)
print(f"mean = {mean_winrate}")
print(f"min = {min(winrate_list)}")
print(f"gap = {28.26087 - mean_winrate}")

1000
p95 = 0.08755884672572535
max = 0.21408115114562226
mean = -0.042938653049123275
min = -0.277442104297038
gap = 0.019298653049123274
rank = 60.699999999999996
p_value = 0.3936063936063936
1000
p95 = 39.130434782608695
max = 48.91304347826087
mean = 31.058695652173917
min = 17.391304347826086
gap = -2.797825652173916