In [1]:
from ta.volatility import AverageTrueRange

import pandas as pd
import plotly.graph_objects as go
from plotly.subplots import make_subplots
from datetime import datetime
import numpy as np

import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd

from backtesting import Strategy
from backtesting import Backtest, set_bokeh_output
set_bokeh_output(notebook=False)

from datetime import timedelta

import sys
sys.path.append('../utils')
import Util
import importlib
importlib.reload(Util)

from enum import Enum
import time

from random import randint
import random

c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\_plotting.py:55: UserWarning: Jupyter Notebook detected. Setting Bokeh output to notebook. This may not work in Jupyter clients without JavaScript support, such as old IDEs. Reset with `backtesting.set_bokeh_output(notebook=False)`.
  warnings.warn('Jupyter Notebook detected. '

In [2]:
pair = 'CADCHF'

df_d1_raw = pd.read_csv(f"../Trading Data/{pair}_D1.csv",sep=',', parse_dates=['Date'], index_col='Date')
df_h4_raw = pd.read_csv(f"../Trading Data/{pair}_H4.csv",sep=',', parse_dates=['Date'], index_col='Date')
df_m15_raw = pd.read_csv(f"../Trading Data/{pair}_M15.csv",sep=',', parse_dates=['Date'], index_col='Date')

print(df_d1_raw)
print(df_h4_raw)
print(df_m15_raw)

               Open     High      Low    Close  Tickvol
Date
2010-09-23  0.95790  0.95845  0.94550  0.95260    81300
2010-09-24  0.95260  0.96180  0.94780  0.95980   103852
2010-09-27  0.96055  0.96420  0.95510  0.95655   115385
2010-09-28  0.95655  0.95765  0.94310  0.94775   126433
2010-09-29  0.94765  0.95425  0.94400  0.94620   115335
...             ...      ...      ...      ...      ...
2026-10-05  0.58075  0.58381  0.58046  0.58250    48951
2026-10-06  0.58249  0.58551  0.58186  0.58538    42990
2026-10-07  0.58540  0.58631  0.58206  0.58423    50257
2026-10-08  0.58424  0.58563  0.58294  0.58443    66525
2026-10-09  0.58444  0.58472  0.58121  0.58234    34325

[4185 rows x 5 columns]
                        Open     High      Low    Close  Tickvol
Date
2010-09-23 08:00:00  0.95790  0.95845  0.95285  0.95370    19153
2010-09-23 12:00:00  0.95370  0.95455  0.94550  0.95075    30860
2010-09-23 16:00:00  0.95060  0.95640  0.95035  0.95445    19947
2010-09-23 20:00:00  0.95445  0.95465  0.95180  0.95260    11340
2010-09-24 00:00:00  0.95260  0.95390  0.95190  0.95355    11213
...                      ...      ...      ...      ...      ...
2026-10-08 20:00:00  0.58464  0.58483  0.58294  0.58443     5859
2026-10-09 00:00:00  0.58444  0.58472  0.58406  0.58417     6568
2026-10-09 04:00:00  0.58416  0.58466  0.58397  0.58442     6073
2026-10-09 08:00:00  0.58441  0.58452  0.58339  0.58370     7289
2026-10-09 12:00:00  0.58370  0.58421  0.58121  0.58234    14395

[25035 rows x 5 columns]
                        Open     High      Low    Close  Tickvol
Date
2020-09-03 03:15:00  0.69834  0.69838  0.69820  0.69823      512
2020-09-03 03:30:00  0.69822  0.69835  0.69811  0.69826      473
2020-09-03 03:45:00  0.69823  0.69843  0.69817  0.69825      627
2020-09-03 04:00:00  0.69827  0.69835  0.69791  0.69801      516
2020-09-03 04:15:00  0.69800  0.69805  0.69785  0.69791      451
...                      ...      ...      ...      ...      ...
2026-10-09 13:45:00  0.58206  0.58244  0.58191  0.58214     2520
2026-10-09 14:00:00  0.58214  0.58265  0.58204  0.58244     1702
2026-10-09 14:15:00  0.58243  0.58249  0.58199  0.58230     1545
2026-10-09 14:30:00  0.58231  0.58286  0.58229  0.58267     1415
2026-10-09 14:45:00  0.58269  0.58279  0.58226  0.58234     1045

[150000 rows x 5 columns]

In [3]:
structure_d1_window = 2
structure_m15_window = 2

date_format = '%Y-%m-%d %H:%M'
# start_date = '2023-1-1 00:00'
# end_date = '2024-3-29 00:00'
start_date = datetime.strptime('2021-1-1 00:00', date_format)
end_date = datetime.strptime('2026-9-16 00:00', date_format)
# start_date = '2022-01-1 00:00'

timezone = "Europe/London"

# nombre de jours pour les high.low
define_key_level_window = 90

gap_look_ahead = 6

# nombre de candle au dessus/ en desous de key level après breakout
breakout_candles = 9

# nombre de jours à chercher key level
key_level_lookback_candle = 100

# vérifier si 30 candle dans ke passé pour valider un valid breakout,
# un valid breakout doit avoir {breakout_candles} candles au dessus du resistant level
breakout_candles_lookback = 30

start_trade_hour = 9
stop_trade_hour = 19

atr_multiplier = 0.7
min_touched = 3

In [4]:
# process D1 data
df_d1 = df_d1_raw.loc[start_date - timedelta(days=30) : end_date]

df_d1 = Util.implement_market_structure_states_fixed_pivots(df_d1, n=structure_d1_window)
df_d1["state_changed"] = df_d1["market_state"] != df_d1[
    "market_state"
].shift(1)
for state in df_d1[df_d1["state_changed"]][["Close", "market_state"]].iterrows():
    print(state)
df_d1 = df_d1.loc[start_date : end_date]

(Timestamp('2020-12-02 00:00:00'), Close           0.69255
market_state        NaN
Name: 2020-12-02 00:00:00, dtype: object)
(Timestamp('2020-12-03 00:00:00'), Close           0.69245
market_state        NaN
Name: 2020-12-03 00:00:00, dtype: object)
(Timestamp('2020-12-04 00:00:00'), Close           0.69728
market_state        NaN
Name: 2020-12-04 00:00:00, dtype: object)
(Timestamp('2020-12-07 00:00:00'), Close           0.6955
market_state       NaN
Name: 2020-12-07 00:00:00, dtype: object)
(Timestamp('2020-12-08 00:00:00'), Close           0.69335
market_state        NaN
Name: 2020-12-08 00:00:00, dtype: object)
(Timestamp('2020-12-09 00:00:00'), Close           0.6932
market_state       NaN
Name: 2020-12-09 00:00:00, dtype: object)
(Timestamp('2020-12-10 00:00:00'), Close           0.69495
market_state        NaN
Name: 2020-12-10 00:00:00, dtype: object)
(Timestamp('2020-12-11 00:00:00'), Close           0.6964
market_state       NaN
Name: 2020-12-11 00:00:00, dtype: object)
(Timestamp('2020-12-14 00:00:00'), Close           0.69455
market_state        NaN
Name: 2020-12-14 00:00:00, dtype: object)
(Timestamp('2020-12-15 00:00:00'), Close           0.6973
market_state       NaN
Name: 2020-12-15 00:00:00, dtype: object)
(Timestamp('2020-12-16 00:00:00'), Close           0.69432
market_state        NaN
Name: 2020-12-16 00:00:00, dtype: object)
(Timestamp('2020-12-17 00:00:00'), Close           0.6945
market_state       NaN
Name: 2020-12-17 00:00:00, dtype: object)
(Timestamp('2020-12-18 00:00:00'), Close           0.69001
market_state        NaN
Name: 2020-12-18 00:00:00, dtype: object)
(Timestamp('2020-12-21 00:00:00'), Close           0.6891
market_state       NaN
Name: 2020-12-21 00:00:00, dtype: object)
(Timestamp('2020-12-22 00:00:00'), Close           0.68877
market_state        NaN
Name: 2020-12-22 00:00:00, dtype: object)
(Timestamp('2020-12-23 00:00:00'), Close           0.69097
market_state        NaN
Name: 2020-12-23 00:00:00, dtype: object)
(Timestamp('2020-12-24 00:00:00'), Close           0.69163
market_state        NaN
Name: 2020-12-24 00:00:00, dtype: object)
(Timestamp('2020-12-25 00:00:00'), Close           0.68953
market_state        NaN
Name: 2020-12-25 00:00:00, dtype: object)
(Timestamp('2020-12-28 00:00:00'), Close           0.6916
market_state       NaN
Name: 2020-12-28 00:00:00, dtype: object)
(Timestamp('2020-12-29 00:00:00'), Close           0.6891
market_state       NaN
Name: 2020-12-29 00:00:00, dtype: object)
(Timestamp('2020-12-30 00:00:00'), Close           0.6909
market_state       NaN
Name: 2020-12-30 00:00:00, dtype: object)
(Timestamp('2020-12-31 00:00:00'), Close           0.6948
market_state       NaN
Name: 2020-12-31 00:00:00, dtype: object)
(Timestamp('2021-01-04 00:00:00'), Close           0.68895
market_state        NaN
Name: 2021-01-04 00:00:00, dtype: object)
(Timestamp('2021-01-05 00:00:00'), Close           0.69295
market_state        NaN
Name: 2021-01-05 00:00:00, dtype: object)
(Timestamp('2021-01-06 00:00:00'), Close           0.69274
market_state        NaN
Name: 2021-01-06 00:00:00, dtype: object)
(Timestamp('2021-01-07 00:00:00'), Close           0.69736
market_state        NaN
Name: 2021-01-07 00:00:00, dtype: object)
(Timestamp('2021-01-08 00:00:00'), Close           0.69721
market_state        NaN
Name: 2021-01-08 00:00:00, dtype: object)
(Timestamp('2021-01-11 00:00:00'), Close           0.69613
market_state        NaN
Name: 2021-01-11 00:00:00, dtype: object)
(Timestamp('2021-01-12 00:00:00'), Close           0.69725
market_state        NaN
Name: 2021-01-12 00:00:00, dtype: object)
(Timestamp('2021-01-13 00:00:00'), Close           0.69834
market_state        NaN
Name: 2021-01-13 00:00:00, dtype: object)
(Timestamp('2021-01-14 00:00:00'), Close           0.70235
market_state        NaN
Name: 2021-01-14 00:00:00, dtype: object)
(Timestamp('2021-01-15 00:00:00'), Close           0.69931
market_state        NaN
Name: 2021-01-15 00:00:00, dtype: object)
(Timestamp('2021-01-18 00:00:00'), Close           0.69805
market_state        NaN
Name: 2021-01-18 00:00:00, dtype: object)
(Timestamp('2021-01-19 00:00:00'), Close           0.69744
market_state        NaN
Name: 2021-01-19 00:00:00, dtype: object)
(Timestamp('2021-01-20 00:00:00'), Close           0.7035
market_state       NaN
Name: 2021-01-20 00:00:00, dtype: object)
(Timestamp('2021-01-21 00:00:00'), Close           0.69997
market_state        NaN
Name: 2021-01-21 00:00:00, dtype: object)
(Timestamp('2021-01-22 00:00:00'), Close           0.69465
market_state    BEARISH
Name: 2021-01-22 00:00:00, dtype: object)
(Timestamp('2021-02-17 00:00:00'), Close            0.7069
market_state    BULLISH
Name: 2021-02-17 00:00:00, dtype: object)
(Timestamp('2021-04-08 00:00:00'), Close           0.73526
market_state    BEARISH
Name: 2021-04-08 00:00:00, dtype: object)
(Timestamp('2021-04-29 00:00:00'), Close           0.74027
market_state    BULLISH
Name: 2021-04-29 00:00:00, dtype: object)
(Timestamp('2021-05-25 00:00:00'), Close           0.74198
market_state    BEARISH
Name: 2021-05-25 00:00:00, dtype: object)
(Timestamp('2021-08-09 00:00:00'), Close             0.732
market_state    BULLISH
Name: 2021-08-09 00:00:00, dtype: object)
(Timestamp('2021-08-19 00:00:00'), Close           0.71621
market_state    BEARISH
Name: 2021-08-19 00:00:00, dtype: object)
(Timestamp('2021-09-27 00:00:00'), Close           0.73314
market_state    BULLISH
Name: 2021-09-27 00:00:00, dtype: object)
(Timestamp('2021-10-28 00:00:00'), Close            0.7382
market_state    BEARISH
Name: 2021-10-28 00:00:00, dtype: object)
(Timestamp('2021-11-15 00:00:00'), Close           0.73869
market_state    BULLISH
Name: 2021-11-15 00:00:00, dtype: object)
(Timestamp('2021-11-26 00:00:00'), Close           0.72067
market_state    BEARISH
Name: 2021-11-26 00:00:00, dtype: object)
(Timestamp('2021-12-31 00:00:00'), Close           0.72117
market_state    BULLISH
Name: 2021-12-31 00:00:00, dtype: object)
(Timestamp('2022-01-21 00:00:00'), Close           0.72367
market_state    BEARISH
Name: 2022-01-21 00:00:00, dtype: object)
(Timestamp('2022-03-11 00:00:00'), Close           0.73258
market_state    BULLISH
Name: 2022-03-11 00:00:00, dtype: object)
(Timestamp('2022-03-31 00:00:00'), Close           0.73769
market_state    BEARISH
Name: 2022-03-31 00:00:00, dtype: object)
(Timestamp('2022-04-18 00:00:00'), Close           0.74928
market_state    BULLISH
Name: 2022-04-18 00:00:00, dtype: object)
(Timestamp('2022-05-19 00:00:00'), Close            0.7582
market_state    BEARISH
Name: 2022-05-19 00:00:00, dtype: object)
(Timestamp('2022-07-04 00:00:00'), Close           0.74715
market_state    BULLISH
Name: 2022-07-04 00:00:00, dtype: object)
(Timestamp('2022-07-22 00:00:00'), Close           0.74353
market_state    BEARISH
Name: 2022-07-22 00:00:00, dtype: object)
(Timestamp('2022-08-23 00:00:00'), Close           0.74372
market_state    BULLISH
Name: 2022-08-23 00:00:00, dtype: object)
(Timestamp('2022-09-09 00:00:00'), Close           0.73651
market_state    BEARISH
Name: 2022-09-09 00:00:00, dtype: object)
(Timestamp('2022-10-19 00:00:00'), Close           0.72957
market_state    BULLISH
Name: 2022-10-19 00:00:00, dtype: object)
(Timestamp('2022-11-09 00:00:00'), Close           0.72734
market_state    BEARISH
Name: 2022-11-09 00:00:00, dtype: object)
(Timestamp('2023-01-05 00:00:00'), Close            0.6894
market_state    BULLISH
Name: 2023-01-05 00:00:00, dtype: object)
(Timestamp('2023-01-18 00:00:00'), Close           0.67821
market_state    BEARISH
Name: 2023-01-18 00:00:00, dtype: object)
(Timestamp('2023-03-02 00:00:00'), Close            0.6924
market_state    BULLISH
Name: 2023-03-02 00:00:00, dtype: object)
(Timestamp('2023-03-06 00:00:00'), Close           0.68368
market_state    BEARISH
Name: 2023-03-06 00:00:00, dtype: object)
(Timestamp('2023-04-03 00:00:00'), Close           0.67929
market_state    BULLISH
Name: 2023-04-03 00:00:00, dtype: object)
(Timestamp('2023-04-12 00:00:00'), Close           0.66637
market_state    BEARISH
Name: 2023-04-12 00:00:00, dtype: object)
(Timestamp('2023-05-05 00:00:00'), Close           0.66539
market_state    BULLISH
Name: 2023-05-05 00:00:00, dtype: object)
(Timestamp('2023-06-28 00:00:00'), Close           0.67628
market_state    BEARISH
Name: 2023-06-28 00:00:00, dtype: object)
(Timestamp('2023-08-31 00:00:00'), Close            0.6537
market_state    BULLISH
Name: 2023-08-31 00:00:00, dtype: object)
(Timestamp('2023-10-11 00:00:00'), Close           0.66328
market_state    BEARISH
Name: 2023-10-11 00:00:00, dtype: object)
(Timestamp('2023-12-15 00:00:00'), Close           0.65007
market_state    BULLISH
Name: 2023-12-15 00:00:00, dtype: object)
(Timestamp('2023-12-27 00:00:00'), Close           0.63778
market_state    BEARISH
Name: 2023-12-27 00:00:00, dtype: object)
(Timestamp('2024-01-18 00:00:00'), Close           0.64323
market_state    BULLISH
Name: 2024-01-18 00:00:00, dtype: object)
(Timestamp('2024-02-27 00:00:00'), Close           0.64929
market_state    BEARISH
Name: 2024-02-27 00:00:00, dtype: object)
(Timestamp('2024-03-18 00:00:00'), Close           0.65553
market_state    BULLISH
Name: 2024-03-18 00:00:00, dtype: object)
(Timestamp('2024-04-15 00:00:00'), Close           0.66134
market_state    BEARISH
Name: 2024-04-15 00:00:00, dtype: object)
(Timestamp('2024-05-17 00:00:00'), Close           0.66751
market_state    BULLISH
Name: 2024-05-17 00:00:00, dtype: object)
(Timestamp('2024-05-30 00:00:00'), Close           0.66008
market_state    BEARISH
Name: 2024-05-30 00:00:00, dtype: object)
(Timestamp('2024-06-24 00:00:00'), Close           0.65377
market_state    BULLISH
Name: 2024-06-24 00:00:00, dtype: object)
(Timestamp('2024-07-12 00:00:00'), Close            0.6552
market_state    BEARISH
Name: 2024-07-12 00:00:00, dtype: object)
(Timestamp('2024-08-15 00:00:00'), Close           0.63527
market_state    BULLISH
Name: 2024-08-15 00:00:00, dtype: object)
(Timestamp('2024-08-20 00:00:00'), Close           0.62647
market_state    BEARISH
Name: 2024-08-20 00:00:00, dtype: object)
(Timestamp('2024-09-25 00:00:00'), Close            0.6304
market_state    BULLISH
Name: 2024-09-25 00:00:00, dtype: object)
(Timestamp('2024-10-31 00:00:00'), Close           0.61982
market_state    BEARISH
Name: 2024-10-31 00:00:00, dtype: object)
(Timestamp('2024-11-06 00:00:00'), Close           0.62796
market_state    BULLISH
Name: 2024-11-06 00:00:00, dtype: object)
(Timestamp('2024-11-27 00:00:00'), Close           0.62785
market_state    BEARISH
Name: 2024-11-27 00:00:00, dtype: object)
(Timestamp('2024-12-30 00:00:00'), Close           0.62923
market_state    BULLISH
Name: 2024-12-30 00:00:00, dtype: object)
(Timestamp('2025-02-20 00:00:00'), Close           0.63267
market_state    BEARISH
Name: 2025-02-20 00:00:00, dtype: object)
(Timestamp('2025-03-25 00:00:00'), Close           0.61822
market_state    BULLISH
Name: 2025-03-25 00:00:00, dtype: object)
(Timestamp('2025-04-03 00:00:00'), Close           0.60929
market_state    BEARISH
Name: 2025-04-03 00:00:00, dtype: object)
(Timestamp('2025-04-22 00:00:00'), Close           0.59733
market_state    BULLISH
Name: 2025-04-22 00:00:00, dtype: object)
(Timestamp('2025-06-23 00:00:00'), Close           0.59153
market_state    BEARISH
Name: 2025-06-23 00:00:00, dtype: object)
(Timestamp('2025-07-28 00:00:00'), Close           0.58463
market_state    BULLISH
Name: 2025-07-28 00:00:00, dtype: object)
(Timestamp('2025-08-15 00:00:00'), Close           0.58349
market_state    BEARISH
Name: 2025-08-15 00:00:00, dtype: object)
(Timestamp('2025-10-08 00:00:00'), Close            0.5744
market_state    BULLISH
Name: 2025-10-08 00:00:00, dtype: object)
(Timestamp('2025-10-15 00:00:00'), Close           0.56698
market_state    BEARISH
Name: 2025-10-15 00:00:00, dtype: object)
(Timestamp('2025-10-29 00:00:00'), Close           0.57343
market_state    BULLISH
Name: 2025-10-29 00:00:00, dtype: object)
(Timestamp('2025-11-13 00:00:00'), Close           0.56423
market_state    BEARISH
Name: 2025-11-13 00:00:00, dtype: object)
(Timestamp('2025-12-04 00:00:00'), Close           0.57523
market_state    BULLISH
Name: 2025-12-04 00:00:00, dtype: object)
(Timestamp('2025-12-23 00:00:00'), Close           0.57493
market_state    BEARISH
Name: 2025-12-23 00:00:00, dtype: object)
(Timestamp('2026-03-02 00:00:00'), Close           0.56871
market_state    BULLISH
Name: 2026-03-02 00:00:00, dtype: object)
(Timestamp('2026-04-01 00:00:00'), Close           0.57218
market_state    BEARISH
Name: 2026-04-01 00:00:00, dtype: object)
(Timestamp('2026-04-22 00:00:00'), Close           0.57389
market_state    BULLISH
Name: 2026-04-22 00:00:00, dtype: object)
(Timestamp('2026-05-06 00:00:00'), Close           0.57101
market_state    BEARISH
Name: 2026-05-06 00:00:00, dtype: object)
(Timestamp('2026-06-05 00:00:00'), Close           0.57084
market_state    BULLISH
Name: 2026-06-05 00:00:00, dtype: object)
(Timestamp('2026-07-02 00:00:00'), Close           0.56666
market_state    BEARISH
Name: 2026-07-02 00:00:00, dtype: object)
(Timestamp('2026-07-13 00:00:00'), Close            0.5756
market_state    BULLISH
Name: 2026-07-13 00:00:00, dtype: object)
(Timestamp('2026-07-30 00:00:00'), Close           0.57487
market_state    BEARISH
Name: 2026-07-30 00:00:00, dtype: object)
(Timestamp('2026-08-11 00:00:00'), Close           0.58244
market_state    BULLISH
Name: 2026-08-11 00:00:00, dtype: object)

In [5]:
# process h4 data
df_h4 = df_h4_raw.loc[start_date - timedelta(days=20) : end_date]
df_h4 = Util.implement_market_structure_states_fixed_pivots(df_h4, 5)
df_h4 = df_h4.loc[start_date : end_date]

h4_d1_direction_list = []
for i in range(len(df_d1)):
    row = df_d1.iloc[i]
    start_date_daily = row.name
    end_date_daily = start_date_daily + timedelta(hours=23, minutes=59)
    df_by_day = df_h4.loc[f'{start_date_daily}' : f'{end_date_daily}']

    for index2, row2 in df_by_day.iterrows():
        h4_d1_direction_list.append(df_d1.iloc[i-1]['market_state'])

df_h4['market_state_d1'] = h4_d1_direction_list

indicator_atr_14 = AverageTrueRange(df_h4['High'], df_h4['Low'], df_h4['Close'], window=14)
df_h4['ATR'] = indicator_atr_14._atr

df_h4

,Open,High,Low,Close,Tickvol,is_swing_high,is_swing_low,market_state,market_state_d1,ATR
Date,,,,,,,,,,
2021-01-04 00:00:00,0.69378,0.69573,0.69310,0.69555,12960,False,False,BULLISH,BULLISH,0.000000
2021-01-04 04:00:00,0.69553,0.69625,0.69513,0.69527,9826,True,False,BULLISH,BULLISH,0.000000
2021-01-04 08:00:00,0.69525,0.69580,0.69311,0.69377,20631,False,False,BULLISH,BULLISH,0.000000
2021-01-04 12:00:00,0.69377,0.69405,0.69151,0.69293,23712,False,False,BULLISH,BULLISH,0.000000
2021-01-04 16:00:00,0.69296,0.69395,0.68858,0.68984,32860,False,False,BULLISH,BULLISH,0.000000
...,...,...,...,...,...,...,...,...,...,...
2026-09-15 08:00:00,0.58789,0.58839,0.58749,0.58791,6852,False,False,BULLISH,BULLISH,0.001281
2026-09-15 12:00:00,0.58792,0.58904,0.58735,0.58878,9087,False,False,BULLISH,BULLISH,0.001310
2026-09-15 16:00:00,0.58879,0.58880,0.58812,0.58812,4546,False,False,BULLISH,BULLISH,0.001265
2026-09-15 20:00:00,0.58812,0.58843,0.58662,0.58820,5083,False,False,BULLISH,BULLISH,0.001304
2026-09-16 00:00:00,0.58820,0.58835,0.58775,0.58776,3957,False,False,BULLISH,BULLISH,0.001253

In [20]:
# process m15 data
df_m15 = df_m15_raw.loc[start_date - timedelta(hours=3): end_date]
df_m15 = Util.implement_market_structure_states_fixed_pivots(df_m15, n=structure_m15_window)

m15_daily_direction_list = []

index_list = []

indicator_atr_m15 = AverageTrueRange(df_m15['High'], df_m15['Low'], df_m15['Close'], window=14)
df_m15['ATR'] = indicator_atr_m15._atr

df_m15 = df_m15.loc[start_date : end_date]
for i in range(len(df_h4)):
    row = df_h4.iloc[i]
    start_date_h4 = row.name
    end_date_h4 = start_date_h4 + timedelta(hours=3, minutes=59)
    df_by_day = df_m15.loc[f'{start_date_h4}' : f'{end_date_h4}']

    for index2, row2 in df_by_day.iterrows():
        # affect current market states of H4 candle because the result is market state of previous D1 candle
        m15_daily_direction_list.append(df_h4.iloc[i]['market_state_d1'])

        # ajust to daylight saving time
        dst = pd.Timestamp(index2, tz=timezone).dst()
        if dst == timedelta(0):
            index2 = index2 - timedelta(hours=1)
            index_list.append(index2)
        else:
            index_list.append(index2)

df_m15['market_state_d1'] = m15_daily_direction_list

df_m15.index = index_list

df_m15

,Open,High,Low,Close,Tickvol,is_swing_high,is_swing_low,market_state,ATR,market_state_d1
2021-01-03 23:00:00,0.69378,0.69450,0.69310,0.69425,1856,False,True,BEARISH,0.000000,BULLISH
2021-01-03 23:15:00,0.69425,0.69472,0.69424,0.69428,451,False,False,BEARISH,0.000000,BULLISH
2021-01-03 23:30:00,0.69429,0.69438,0.69412,0.69423,595,False,False,BEARISH,0.000000,BULLISH
2021-01-03 23:45:00,0.69422,0.69422,0.69372,0.69403,767,False,True,BEARISH,0.000000,BULLISH
2021-01-04 00:00:00,0.69403,0.69450,0.69382,0.69413,914,True,False,BEARISH,0.000000,BULLISH
...,...,...,...,...,...,...,...,...,...,...
2026-09-15 23:00:00,0.58770,0.58809,0.58770,0.58803,238,False,False,BEARISH,0.000351,BULLISH
2026-09-15 23:15:00,0.58803,0.58809,0.58801,0.58808,144,False,False,BEARISH,0.000332,BULLISH
2026-09-15 23:30:00,0.58805,0.58816,0.58805,0.58813,170,False,False,BEARISH,0.000316,BULLISH
2026-09-15 23:45:00,0.58814,0.58820,0.58812,0.58820,147,False,False,BEARISH,0.000299,BULLISH
2026-09-16 00:00:00,0.58820,0.58824,0.58816,0.58822,237,False,False,BEARISH,0.000283,BULLISH

In [21]:
# using m15 market structure for entry
def apply_total_signal(df, start_trade_hour=9, stop_trade_hour=19):
    # Initialize the 'TotalSignal' column
    df_signal_list = []

    for i in range(0, len(df)):
        current_bar_date = df.index[i]
        signal = 0

        # short
        # d1 trending conditions
        c_short_daily_direction = df['market_state_d1'].iloc[i-1] == 'BEARISH'
        if c_short_daily_direction:
            c_m15_ms_bearish = df['market_state'].iloc[i] == 'BEARISH'

            c_time_trade = start_trade_hour <= current_bar_date.hour and current_bar_date.hour <= stop_trade_hour
            if c_time_trade and c_m15_ms_bearish:
                signal = 1

        # long
        c_long_daily_direction = df['market_state_d1'].iloc[i-1] == 'BULLISH'
        if c_long_daily_direction:
            c_m15_ms_bullish = df['market_state'].iloc[i] == 'BULLISH'

            c_time_trade = start_trade_hour <= current_bar_date.hour and current_bar_date.hour <= stop_trade_hour
            if c_time_trade and c_m15_ms_bullish:
                signal = 2

        df_signal_list.append(signal)

    return df_signal_list

df_m15['TotalSignal'] = apply_total_signal(df=df_m15, start_trade_hour=9, stop_trade_hour=19)

In [22]:
len(df_m15[df_m15.TotalSignal != 0])

31820

In [9]:
df_m15['pointpos'] = df_m15.apply(lambda row: Util.pointpos(row), axis=1)

In [10]:
start_date_chart = '2022-10-1 00:00'
end_date_chart = '2022-10-30 00:00'
dfpl = df_m15.loc[start_date_chart : end_date_chart]#.set_index("Gmt time")

# Create a plot with 2 rows
fig = make_subplots(rows=1, cols=1)

# Add candlestick plot on the first row
fig.add_trace(go.Candlestick(x=dfpl.index,
                             open=dfpl['Open'],
                             high=dfpl['High'],
                             low=dfpl['Low'],
                             close=dfpl['Close']),
              row=1, col=1)

# Add markers for entry point m15
fig.add_trace(go.Scatter(x=dfpl.index, y=dfpl['pointpos'], mode="markers",
                         marker=dict(size=12, color="MediumPurple"),
                         name="entry"),
              row=1, col=1)

fig.update_layout(width=1500, height=800, sliders=[])
fig.show()

In [13]:
class ChochStrat(Strategy):
    mysize = 0.5
    slcoef = 2
    TPcoef = 2
    risk_percent = 0.01
    setup_duration_gap = 60
    stoploss_window = 150
    
    def init(self):
        self.current_day = None
        self.setup_duration = None
        self.order_placed_time = None

        super().init()

    def reset_order(self, current_bar_date):
        self.current_day = current_bar_date

        # delete placed order at the end of the day if not executed
        for order in self.orders:
            order_executed= False
            for trade in self.trades:
                if trade.tag == order.tag:
                    order_executed = True

            if order_executed == False:
                order.cancel()

        self.order_placed_time = None
        
    def get_tag(self):
        return f"{self.order_placed_time}"

    def get_highest_high(self):
            return self.data.High[len(self.data.High) - self.stoploss_window : len(self.data.High)].max()
        
    def get_lowest_low(self):
        return self.data.Low[len(self.data.Low) - self.stoploss_window : len(self.data.Low)].min()

    def get_sl(self):
        return round(random.uniform(self.data['ATR'][-1]*1,self.data['ATR'][-1]*2.5), 5)
    
    def next(self):
        super().next()

        current_bar_date = self.data.index[-1].date()
        if self.current_day != current_bar_date:
            self.reset_order(current_bar_date)

        if len(self.trades)==0:
            if self.data['TotalSignal'][-1]==1:
                planned_entry_price = self.data.Close[-1]
                sl = abs(planned_entry_price - self.get_highest_high())
                if sl == 0:
                    sl = self.get_sl()
                tp = self.TPcoef * sl

                sl1 = planned_entry_price + sl
                tp1 = planned_entry_price - tp
                position_size = int((self.risk_percent * self.equity) / sl)

                self.sell(sl=sl1, tp=tp1, size=position_size)
                
            if self.data['TotalSignal'][-1]==2:
                planned_entry_price = self.data.Close[-1]
                sl = abs(planned_entry_price - self.get_lowest_low())
                if sl == 0:
                    sl = self.get_sl()
                tp = self.TPcoef * sl

                sl1 = planned_entry_price - sl
                tp1 = planned_entry_price + tp
                position_size = int((self.risk_percent * self.equity) / sl)

                self.buy(sl=sl1, tp=tp1, size=position_size)

In [23]:
start_date_chart = '2021-1-1 00:00'
end_date_chart = '2026-12-30 00:00'
global_dfopt = df_m15.loc[start_date_chart : end_date_chart]

bt = Backtest(global_dfopt, ChochStrat, cash=10000, margin=0.005, finalize_trades=True) #0.0002
stats = bt.run()

print(stats)
bt.plot()

Start                     2021-01-03 23:00:00
End                       2026-09-16 00:00:00
Duration                   2081 days 01:00:00
Exposure Time [%]                    94.09357
Equity Final [$]                   8731.09324
Equity Peak [$]                    10536.8987
Return [%]                          -12.68907
Buy & Hold Return [%]                -15.2726
Return (Ann.) [%]                      -2.108
Volatility (Ann.) [%]                 8.77061
CAGR [%]                             -2.35348
Sharpe Ratio                         -0.24035
Sortino Ratio                        -0.32936
Calmar Ratio                         -0.09595
Alpha [%]                           -16.71578
Beta                                 -0.26366
Max. Drawdown [%]                    -21.9693
Avg. Drawdown [%]                    -1.09482
Max. Drawdown Duration      860 days 10:00:00
Avg. Drawdown Duration       31 days 01:07:00
# Trades                                  234
Win Rate [%]                         32.05128
Best Trade [%]                        8.09297
Worst Trade [%]                      -3.04855
Avg. Trade [%]                       -0.04031
Max. Trade Duration         196 days 14:45:00
Avg. Trade Duration           8 days 08:20:00
Profit Factor                         0.91382
Expectancy [%]                       -0.03398
SQN                                  -0.62061
Kelly Criterion                      -0.02881
_strategy                          ChochStrat
_equity_curve                             ...
_trades                          Size  Ent...
dtype: object

c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\_plotting.py:141: UserWarning: Data contains too many candlesticks to plot; downsampling to '8h'. See `Backtest.plot(resample=...)`
  warnings.warn(f"Data contains too many candlesticks to plot; downsampling to {freq!r}. "

GridPlot(id='p2113', ...)

In [24]:
# add some sl tp management

class RandomStrat(Strategy):
    mysize = 0.5
    slcoef = 2
    TPcoef = 2
    risk_percent = 0.01
    trades_list = None
    stoploss_window = 150

    def is_signal(self, date):
        for i in range(0, len(self.trades_list)):
            if self.trades_list[i] == date:
                return True
        return False

    def get_highest_high(self):
        return self.data.High[len(self.data.High) - self.stoploss_window : len(self.data.High)].max()
    
    def get_lowest_low(self):
        return self.data.Low[len(self.data.Low) - self.stoploss_window : len(self.data.Low)].min()
    
    def init(self):
        super().init()

    def get_sl(self):
        return round(random.uniform(self.data['ATR'][-1]*1,self.data['ATR'][-1]*2.5), 5)
    
    def next(self):
        super().next()
        if self.is_signal(self.data.index[-1]) and len(self.trades) == 0 and len(self.closed_trades) < 234:
            if self.data['market_state_d1'][-1] == 'BULLISH':
                planned_entry_price = self.data.Close[-1]
                sl = abs(planned_entry_price - self.get_lowest_low())
                if sl == 0:
                    sl = self.get_sl()
                tp = self.TPcoef * sl

                sl1 = planned_entry_price - sl
                tp1 = planned_entry_price + tp
                position_size = int((self.risk_percent * self.equity) / sl)
                # max_affordable_size = int((self.equity * 0.99) / planned_entry_price)
                # print(f'{position_size} {max_affordable_size}')

                self.buy(sl=sl1, tp=tp1, size=position_size)
            else:
                planned_entry_price = self.data.Close[-1]
                sl = abs(planned_entry_price - self.get_highest_high())
                if sl == 0:
                    sl = self.get_sl()
                tp = self.TPcoef * sl

                sl1 = planned_entry_price + sl
                tp1 = planned_entry_price - tp
                position_size = int((self.risk_percent * self.equity) / sl)
                # max_affordable_size = int((self.equity * 0.99) / planned_entry_price)
                # print(f'{position_size} {max_affordable_size}')

                self.sell(sl=sl1, tp=tp1, size=position_size)

In [30]:
trades_list = []
while len(trades_list) != 600:
    random_index = randint(0, len(df_m15))
    candle = df_m15.iloc[random_index]
    # exclu Saturday and Sunday
    if candle.name.weekday() < 5:
        if 9 <= candle.name.hour and candle.name.hour <= 19:
            trades_list.append(candle.name)
trades_list.sort()

bt = Backtest(df_m15, RandomStrat, cash=10000, margin=0.005, finalize_trades=True) #0.0002
stats = bt.run(trades_list=trades_list)

print(stats)

bt.plot()

c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\backtesting.py:1009: UserWarning: time=807: Broker canceled the order due to insufficient margin (equity=9703.38, margin_available=9703.38).
  warnings.warn(

Start                     2021-01-03 23:00:00
End                       2026-09-16 00:00:00
Duration                   2081 days 01:00:00
Exposure Time [%]                    64.52222
Equity Final [$]                   9564.74182
Equity Peak [$]                   11222.58449
Return [%]                           -4.35258
Buy & Hold Return [%]                -15.2726
Return (Ann.) [%]                    -0.69628
Volatility (Ann.) [%]                 8.59014
CAGR [%]                             -0.77802
Sharpe Ratio                         -0.08106
Sortino Ratio                        -0.11445
Calmar Ratio                         -0.02966
Alpha [%]                            -6.96727
Beta                                  -0.1712
Max. Drawdown [%]                   -23.47404
Avg. Drawdown [%]                      -0.841
Max. Drawdown Duration     1791 days 15:45:00
Avg. Drawdown Duration       32 days 04:00:00
# Trades                                  233
Win Rate [%]                         33.04721
Best Trade [%]                        4.27849
Worst Trade [%]                      -1.99368
Avg. Trade [%]                        0.03537
Max. Trade Duration         160 days 00:30:00
Avg. Trade Duration           5 days 17:00:00
Profit Factor                         1.13051
Expectancy [%]                         0.0396
SQN                                  -0.20721
Kelly Criterion                      -0.00966
_strategy                 RandomStrat(trad...
_equity_curve                             ...
_trades                          Size  Ent...
dtype: object

c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\_plotting.py:141: UserWarning: Data contains too many candlesticks to plot; downsampling to '8h'. See `Backtest.plot(resample=...)`
  warnings.warn(f"Data contains too many candlesticks to plot; downsampling to {freq!r}. "

GridPlot(id='p3817', ...)

In [32]:
i = 0
expectancy_list = []
winrate_list = []
number_trades = []

while len(expectancy_list) < 500:
    trades_list = []
    while len(trades_list) != 600:
        random_index = randint(0, len(df_m15)-1)
        candle = df_m15.iloc[random_index -1]
        # exclu Saturday and Sunday
        if candle.name.weekday() < 5:
            if 9 <= candle.name.hour and candle.name.hour <= 19:
                trades_list.append(candle.name)
    trades_list.sort()

    bt = Backtest(df_m15, RandomStrat, cash=10000, margin=0.0009, finalize_trades=True) #0.0002
    stats = bt.run(trades_list=trades_list)
    if 180 <= stats['# Trades'] and stats['# Trades'] <= 270:
        expectancy_list.append(stats['Expectancy [%]'])
        winrate_list.append(stats['Win Rate [%]'])
        number_trades.append(stats['# Trades'])
        print(f'{i} {len(expectancy_list)} {stats['Expectancy [%]']} Done')
    i += 1

print(expectancy_list)

0 1 0.050220507471271186 Done
2 2 -0.001521351082180007 Done
3 3 -0.06566401575893804 Done
4 4 0.06075720663367665 Done
5 5 -0.09612224510169602 Done
7 6 0.009802922382075295 Done
9 7 -0.04734929748127309 Done
11 8 -0.1092235254054327 Done
12 9 -0.049608930209815466 Done
13 10 0.01662147960172789 Done
14 11 -0.11524222453097407 Done
15 12 -0.04545623736332913 Done
18 13 0.010142832592884782 Done
22 14 -0.048656933916812924 Done
24 15 -0.11389735418414139 Done
25 16 -0.16728799584692672 Done
26 17 -0.001787512057427388 Done
27 18 0.02642987541424742 Done
28 19 0.002640076342742507 Done
31 20 -0.046539237573314914 Done
32 21 -0.03455648065241288 Done
35 22 -0.01258852796316783 Done
39 23 -0.01557646708352738 Done
40 24 -0.07956836385312262 Done
41 25 -0.02668661904793349 Done
42 26 -0.03241301349355602 Done
43 27 -0.022453827660389728 Done
45 28 -0.04994536491183281 Done
46 29 -0.05779246663549775 Done
47 30 -0.08390557692338503 Done
48 31 -0.02916422338686836 Done
49 32 0.05619289659355286 Done
50 33 -0.04237768389274823 Done
52 34 -0.002436275406422503 Done
55 35 -0.01657758634052051 Done
56 36 -0.04756479407493178 Done
58 37 -0.0071069445925027695 Done
59 38 -0.08505842174945392 Done
60 39 -0.015675433909760485 Done
61 40 -0.027334654718368528 Done
62 41 -0.010617108069670724 Done
63 42 0.010882365186501363 Done
64 43 -0.07132685345929649 Done
65 44 -0.07136587908221352 Done
68 45 -0.03621248304933653 Done
69 46 -0.002264067434741913 Done
71 47 -0.010212123916766446 Done
72 48 -0.012017270502897828 Done
73 49 -0.05790822737873515 Done
74 50 0.02664014907933942 Done
75 51 0.011823981001293093 Done
76 52 -0.09701198527032659 Done
77 53 -0.05407176039850047 Done
78 54 -0.0960433302815289 Done
79 55 -0.09508274804837595 Done
80 56 0.0783546784734317 Done
81 57 0.02148285891265327 Done
82 58 0.024998283487395863 Done
83 59 -0.03326615403531695 Done
84 60 -0.04326222966792982 Done
85 61 -0.01061046678628578 Done
87 62 -0.02670100175183212 Done
88 63 -0.06550759589684955 Done
89 64 -0.0433567324986082 Done
90 65 -0.0859004764256134 Done
91 66 -0.010056820057294412 Done
92 67 0.040404783940668994 Done
93 68 -0.1243957504649393 Done
96 69 -0.05241348952399505 Done
99 70 -0.0289570841607025 Done
100 71 -0.033033850817745236 Done
102 72 0.024095453975522194 Done
103 73 -0.04484110050899431 Done
104 74 0.019539493761014434 Done
108 75 -0.02974799476720653 Done
110 76 -0.002101270694882939 Done
111 77 -0.031388283447269974 Done
113 78 -0.018371253445126846 Done
116 79 -0.10776979119263472 Done
117 80 0.0010756887737737645 Done
118 81 -0.06360437602240945 Done
119 82 -0.06505841720122377 Done
120 83 -0.010616153288291888 Done
121 84 0.0021597712306758443 Done
122 85 0.09844439100744437 Done
124 86 -0.01272585929787194 Done
125 87 -0.06468996209427752 Done
127 88 -0.0697703639298586 Done
129 89 -0.10004746067893877 Done
130 90 -0.027668684187957652 Done
131 91 -0.10819266238784987 Done
132 92 0.007778570128708552 Done
135 93 -0.05525626338731386 Done
137 94 -0.05907981425687969 Done
139 95 -0.0602428951808947 Done
141 96 -0.037217980734909346 Done
142 97 -0.036968758542270296 Done
143 98 -0.036290393507302725 Done
144 99 -0.0675357300221289 Done
145 100 0.025479754679972516 Done
146 101 -0.045510849123910777 Done
147 102 0.02406108473882085 Done
148 103 -0.02510222486631716 Done
150 104 -0.10103356126104418 Done
151 105 -0.024524162280005892 Done
152 106 0.029879972116670928 Done
153 107 0.08454254897137747 Done
154 108 -0.06413924903093157 Done
155 109 0.03637293120622244 Done
156 110 -0.09530509399176852 Done
157 111 -0.037962770225486185 Done
158 112 -0.054054249193205825 Done
159 113 -0.061249944250639544 Done
160 114 -0.07567482112965927 Done
161 115 0.007832861415735949 Done
162 116 0.004312799215316466 Done
164 117 -0.027854890843284724 Done
165 118 -0.08486017303348863 Done
166 119 -0.07158842886199163 Done
168 120 -0.06977160077755121 Done
169 121 -0.06707440464474926 Done
172 122 -0.0005134641895951578 Done
173 123 0.007296401998209336 Done
174 124 -0.03719001848146992 Done
176 125 -0.005564639971853368 Done
177 126 -0.04493276576667522 Done
179 127 0.022032665036542165 Done
180 128 0.050939231217827306 Done
181 129 -0.05711598336596266 Done
182 130 -0.04127705418661227 Done
184 131 -0.09159694586894085 Done
185 132 -0.009547898097716659 Done
186 133 -0.06703767701803498 Done
187 134 -0.04062343442658814 Done
188 135 -0.07675975482179499 Done
189 136 -0.05156975958750944 Done
190 137 -0.07581276166675838 Done
191 138 -0.05112541866680585 Done
192 139 -0.004251011414792356 Done
193 140 -0.07521155906060085 Done
194 141 -0.012212520145312114 Done
195 142 -0.047145970795398236 Done
197 143 0.017889791878955803 Done
198 144 0.023389039944691624 Done
199 145 -0.017805685407497416 Done
200 146 -0.06436963502656685 Done
201 147 -0.11189561264329163 Done
202 148 -0.06331552179109645 Done
204 149 -0.015417809443730588 Done
206 150 -0.05269030010858515 Done
208 151 -0.006656971012083837 Done
210 152 -0.008268138010991535 Done
211 153 -0.010155403727735584 Done
212 154 0.016651265090123844 Done
213 155 -0.10074755184897098 Done
215 156 -0.08431902306069225 Done
216 157 -0.07291272353978098 Done
218 158 0.046230854622388726 Done
219 159 -0.07761722354513252 Done
221 160 0.0009592317861448451 Done
222 161 -0.04702166459346148 Done
223 162 -0.04106579267679092 Done
224 163 0.014980037818836575 Done
226 164 -0.06083037895699457 Done
227 165 0.013031786562095655 Done
228 166 -0.025067358231435296 Done
229 167 0.06168017453688924 Done
230 168 -0.10960766187169117 Done
231 169 -0.019370891415316723 Done
232 170 -0.04862737600658486 Done
233 171 -0.007866813462515675 Done
234 172 -0.0020416443982417616 Done
235 173 -0.05417193725144495 Done
237 174 -0.11961891995678013 Done
238 175 -0.07262867413061465 Done
240 176 -0.023029303469365055 Done
241 177 -0.024072336919904062 Done
242 178 -0.055261307135483065 Done
243 179 0.025380846492541204 Done
244 180 0.06881907219605984 Done
245 181 -0.15910937092984892 Done
246 182 -0.11461986125657793 Done
248 183 -0.06566003438840619 Done
249 184 -0.08750707038711168 Done
251 185 0.0012299436240885337 Done
252 186 0.04714280901825909 Done
253 187 -0.008397154805242002 Done
254 188 0.014043539833623582 Done
255 189 -0.013380225179047706 Done
256 190 -0.02561088133824667 Done
257 191 -0.02072267150891213 Done
259 192 -0.08411394775722289 Done
260 193 -0.01925294637305009 Done
261 194 -0.005735181295962852 Done
262 195 -0.07650007350263391 Done
263 196 -0.0004668670317619245 Done
264 197 0.00057119208680353 Done
265 198 -0.06011183236221943 Done
266 199 -0.09975637107799495 Done
267 200 -0.04414674402748516 Done
269 201 0.051774260883920786 Done
270 202 0.011599029507533302 Done
271 203 0.015307679732045899 Done
272 204 0.07367679076102526 Done
273 205 -0.0924962311899829 Done
277 206 -0.012275605693357616 Done
278 207 -0.04623781178720935 Done
279 208 -0.02189207377089403 Done
280 209 -0.03785141386033957 Done
282 210 0.004493480320354459 Done
283 211 0.006272514877033689 Done
284 212 0.01576211227977746 Done
285 213 0.06141599167731588 Done
286 214 0.018858378012379034 Done
289 215 -0.035376259487346545 Done
290 216 -0.06385302970088391 Done
291 217 -0.03163962372182155 Done
292 218 -0.07377125387093046 Done
293 219 -0.07641971128870247 Done
294 220 -0.08254288830518139 Done
295 221 -0.05116138902922094 Done
296 222 -0.023941351729621085 Done
298 223 -0.02502634816319602 Done
300 224 -0.05754024629261397 Done
301 225 -0.04255267687748244 Done
302 226 -0.054836078601841476 Done
304 227 -0.023378567320791868 Done
305 228 -0.025823752199712367 Done
306 229 -0.04844931482604548 Done
308 230 0.015147039035128205 Done
309 231 0.033328491993218405 Done
311 232 0.014428554045031933 Done
313 233 0.0036516231625657604 Done
314 234 -0.060102479269445175 Done
316 235 0.02001873991065596 Done
317 236 0.0027224238043558617 Done
318 237 -0.010935735791386493 Done
319 238 -0.047908505684645414 Done
321 239 0.013801454418446138 Done
322 240 -0.05554946642987311 Done
323 241 -0.013566546979805602 Done
324 242 -0.08794419897563754 Done
326 243 -0.06860934619552746 Done
328 244 0.015843389173106497 Done
329 245 0.01552212529179857 Done
331 246 -0.062215033998001976 Done
333 247 -0.028171848504272505 Done
334 248 -0.08480931824370136 Done
335 249 0.04262225862092421 Done
336 250 -0.12491644157104512 Done
338 251 -0.031307127043011466 Done
339 252 -0.012400719456122984 Done
340 253 -0.00022579459190095688 Done
341 254 0.01234726644216186 Done
342 255 -0.09481209040964265 Done
343 256 -0.16861427761198983 Done
344 257 -0.058928382832326806 Done
345 258 -0.050439308955159495 Done
347 259 -0.042641868134593156 Done
348 260 -0.007935273945430784 Done
349 261 0.04471906751476538 Done
351 262 -0.05667963014856599 Done
354 263 0.027327689575205986 Done
355 264 -0.013489133084605719 Done
357 265 -0.059219241993651334 Done
358 266 -0.10475408298174081 Done
359 267 -0.06669870980167299 Done
360 268 -0.0016276003234129328 Done
361 269 0.007631155601687405 Done
364 270 0.016141235497513277 Done
365 271 -0.00410418832810807 Done
366 272 -0.055788006371049303 Done
367 273 0.0029148288349391508 Done
368 274 -0.07334232804554124 Done
371 275 -0.061248106222910555 Done
373 276 0.002978209039007571 Done
374 277 0.0511444235177758 Done
375 278 0.028933529988005052 Done
376 279 -0.05677363693710754 Done
378 280 0.030400969201042682 Done
379 281 -0.07656155558675633 Done
380 282 -0.008752382968652246 Done
381 283 -0.013459107840787816 Done
383 284 -0.00495792465454686 Done
384 285 -0.0052393786904955265 Done
385 286 0.0459181821111864 Done
386 287 0.024988896932231167 Done
387 288 -0.03767330046616294 Done
388 289 -0.0393425055774284 Done
389 290 -0.04391432709151018 Done
390 291 -0.08019560243475327 Done
391 292 0.02331565130734139 Done
392 293 -0.01414120807671189 Done
394 294 0.0017944932978604187 Done
395 295 -0.013630848009084281 Done
396 296 -0.08653030192908596 Done
398 297 0.06662530948285178 Done
399 298 -0.0652870275906111 Done
400 299 -0.03488977177389037 Done
402 300 -0.056768882251481904 Done
403 301 -0.04019074444520836 Done
404 302 -0.007199627154256971 Done
405 303 -0.05590879424022116 Done
406 304 -0.029356421725194284 Done
407 305 -0.05503556734999609 Done
410 306 -0.047647761136339936 Done
411 307 -0.09535838445704702 Done
412 308 -0.0280275681401365 Done
414 309 0.05643510418044524 Done
415 310 -0.11060228821439189 Done
416 311 -0.0294103139794813 Done
417 312 -0.021849608891730456 Done
418 313 0.011016713782519946 Done
419 314 -0.030875287158733444 Done
421 315 0.03178116519982054 Done
422 316 -0.12475162019285962 Done
423 317 -0.02551205347650265 Done
424 318 -0.06425487932566612 Done
425 319 -0.037762173462108244 Done
426 320 -0.008578679142430953 Done
428 321 0.04363325275475422 Done
430 322 0.0017077151798723356 Done
431 323 -0.12668221502575738 Done
434 324 -0.07737453560209197 Done
435 325 -0.04200142280968046 Done
437 326 -0.10900182736880912 Done
438 327 0.0004448023543698516 Done
439 328 0.05001227572488555 Done
440 329 -0.06807371214304436 Done
441 330 -0.10371705868827674 Done
442 331 0.0522162163047139 Done
443 332 -0.1115993968987307 Done
444 333 -0.038614596063695966 Done
445 334 -0.004896374614656493 Done
446 335 -0.08738423762160538 Done
449 336 0.029202922446086632 Done
452 337 -0.06578318717049499 Done
454 338 -0.06587291148109406 Done
455 339 -0.05511969775722835 Done
456 340 -0.04750019273570258 Done
457 341 0.008864766718526708 Done
458 342 -0.06555548313975065 Done
459 343 -0.04774192873976046 Done
460 344 -0.06282095601214699 Done
461 345 -0.06044854972818493 Done
462 346 -0.05307590496071591 Done
463 347 -0.07936462567355662 Done
464 348 0.029838025767643446 Done
465 349 0.009970645234336393 Done
466 350 -0.09126819614987977 Done
467 351 -0.03988743299677741 Done
468 352 -0.032708752165963376 Done
469 353 -0.0903780051371126 Done
470 354 -0.11676084893174012 Done
471 355 0.011242981783764809 Done
472 356 -0.04260998214080095 Done
473 357 -0.1462612278016148 Done
474 358 -0.005137072669615844 Done
475 359 -0.01588828797836814 Done
476 360 -0.03616139600122456 Done
478 361 -0.11045078894968516 Done
479 362 -0.06585975834555889 Done
480 363 -0.06186785309005394 Done
481 364 -0.012350048235856606 Done
483 365 -0.009244215310350476 Done
484 366 -0.04500690397061191 Done
485 367 0.02194475314391561 Done
487 368 -0.12366677177821916 Done
488 369 -0.03075429930541993 Done
489 370 -0.026732285530970123 Done
490 371 -0.06629241331382586 Done
491 372 -0.019392842353332124 Done
493 373 -0.014715198312267207 Done
494 374 -0.021769974591372112 Done
496 375 -0.09843221224232054 Done
497 376 -0.02467064186386799 Done
498 377 -0.08868036926644429 Done
500 378 -0.031661285001792834 Done
501 379 -0.08280475931535522 Done
502 380 -0.037141860931452275 Done
503 381 -0.03378651013668811 Done
504 382 -0.00330707583459508 Done
505 383 -0.08150849152523347 Done
506 384 0.03180688802759303 Done
507 385 -0.052397004690490565 Done
508 386 -0.003904954172134738 Done
509 387 0.03354924958168944 Done
510 388 -0.06745335372647648 Done
511 389 -0.024997401348454937 Done
514 390 0.047252365828216986 Done
516 391 -0.04609415751423718 Done
517 392 -0.06586389296535305 Done
518 393 0.010461777643235907 Done
519 394 -0.018770179696920505 Done
520 395 0.007878904326209813 Done
521 396 0.12851216308562807 Done
522 397 -0.017874391877343927 Done
523 398 0.021436788298772356 Done
524 399 0.016182278601810172 Done
525 400 0.012200227390686661 Done
526 401 -0.05572677323470994 Done
529 402 -0.00458348807272763 Done
530 403 -0.05900686645995836 Done
531 404 -0.038378909434485665 Done
532 405 -0.03577768862170085 Done
534 406 -0.08779627832109858 Done
535 407 -0.012278754047790455 Done
537 408 -0.0026424911653293416 Done
539 409 0.005469391538066055 Done
540 410 -0.05328622342341391 Done
541 411 -0.04676399467803104 Done
542 412 -0.0749545063233541 Done
545 413 -0.050970170107206565 Done
546 414 -0.09658837596761394 Done
547 415 0.043443045127604225 Done
548 416 -0.07296279044203065 Done
549 417 0.06896451465177617 Done
550 418 0.015985509507262866 Done
551 419 0.05022555661274925 Done
552 420 -0.006821730503836295 Done
553 421 -0.0017019023807175013 Done
554 422 -0.004264632299943643 Done
555 423 -0.11121650500193207 Done
556 424 -0.07687233827074978 Done
557 425 0.014021286767376037 Done
558 426 -0.008542538272471948 Done
559 427 -0.023424581162241137 Done
560 428 0.029180596256934928 Done
561 429 -0.057379224032894624 Done
562 430 0.06820454831514855 Done
563 431 0.024433653350722402 Done
564 432 -0.07311950976948069 Done
566 433 -0.11192012734175202 Done
567 434 -0.04669171841827563 Done
568 435 0.05287815247037112 Done
569 436 0.009432783027012774 Done
570 437 0.025729531712600808 Done
573 438 -0.11734314395405501 Done
574 439 -0.06719790631981805 Done
575 440 0.012419935411383644 Done
576 441 0.003756843271866643 Done
577 442 -0.02517352672311098 Done
578 443 -0.015868694177308962 Done
580 444 -0.002081116021079796 Done
582 445 -0.04126659100426549 Done
584 446 0.05357705519193535 Done
585 447 -0.09336783115660087 Done
587 448 0.013309830274650975 Done
588 449 0.012705917029366657 Done
589 450 -0.020344878327887294 Done
590 451 -0.09599078735343855 Done
592 452 -0.05899271601996511 Done
593 453 0.008165853822427788 Done
594 454 0.023517969211788795 Done
595 455 -0.045727690735445116 Done
596 456 -0.04928985035974404 Done
598 457 -0.028880970484935466 Done
599 458 -0.05812780411558361 Done
600 459 -0.06131553561129255 Done
601 460 -0.03365535831024371 Done
602 461 0.004850933303615254 Done
604 462 0.02917204133750281 Done
605 463 -0.006595853024218005 Done
606 464 0.050663106795313426 Done
607 465 0.040666520243604676 Done
608 466 -0.03639509926234705 Done
610 467 -0.035015531302036974 Done
612 468 -0.04710790040789363 Done
613 469 0.0793606590937203 Done
614 470 -0.1051735173112864 Done
615 471 -0.02516273637467533 Done
616 472 -0.06698655479351578 Done
617 473 0.03162264079473007 Done
618 474 0.033050573479808464 Done
619 475 0.00787711296079499 Done
620 476 -0.09460768202430837 Done
621 477 -0.014424137856746639 Done
623 478 -0.05221580351964097 Done
624 479 -0.014402732472053868 Done
625 480 -0.019765983417678684 Done
626 481 -0.01121524597353521 Done
627 482 -0.06926664819895535 Done
628 483 -0.013535796740854868 Done
629 484 -0.052028459813138535 Done
630 485 -0.03786055270617284 Done
632 486 -0.05336751571203353 Done
633 487 -0.02826593541833867 Done
634 488 -0.06857038643519259 Done
635 489 -0.005745325224232151 Done
636 490 -0.04116662382435599 Done
637 491 -0.05640234073864815 Done
643 492 -0.057513323902666426 Done
644 493 -0.006702200672973405 Done
645 494 0.0008443249637806582 Done
646 495 -0.08491580535674775 Done
647 496 0.01439395558141705 Done
649 497 -0.023768645816852594 Done
650 498 -0.0663417357209702 Done
651 499 -0.01737228460407548 Done
652 500 0.024537615375816446 Done

In [33]:
print(len(expectancy_list))

p95 = np.percentile(expectancy_list, 95)                  # ngưỡng phân vị 95
print(f"p95 = {p95}")
# max_expectancy = max(expectancy_list_2)
print(f"max = {max(expectancy_list)}")
mean_expectancy = np.mean(expectancy_list)
print(f"mean = {mean_expectancy}")
print(f"min = {min(expectancy_list)}")
print(f"gap = {-0.06797 - mean_expectancy}")

df_result = pd.DataFrame({'expectancy' : expectancy_list})
rank = (df_result['expectancy'] <= -0.06797).mean() * 100 
print(f"rank = {rank}")
p_value = ((df_result['expectancy'] >= -0.06797).sum() + 1) / (len(df_result['expectancy']) + 1)
print(f"p_value = {p_value}")

print(len(winrate_list))

p95_winrate = np.percentile(winrate_list, 95)                  # ngưỡng phân vị 95
print(f"p95 = {p95_winrate}")
# max_expectancy = max(expectancy_list_2)
print(f"max = {max(winrate_list)}")
mean_winrate = np.mean(winrate_list)
print(f"mean = {mean_winrate}")
print(f"min = {min(winrate_list)}")
print(f"gap = {33.21799 - mean_winrate}")

500
p95 = 0.04739036132305029
max = 0.12851216308562807
mean = -0.029739524904357485
min = -0.16861427761198983
gap = -0.03823047509564252
rank = 19.0
p_value = 0.810379241516966
500
p95 = 36.603147620092116
max = 40.97560975609756
mean = 31.984061928438823
min = 23.504273504273502
gap = 1.2339280715611771