In [21]:
from ta.volatility import AverageTrueRange

import pandas as pd
import plotly.graph_objects as go
from plotly.subplots import make_subplots
from datetime import datetime
import numpy as np

import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd

from backtesting import Strategy
from backtesting import Backtest, set_bokeh_output
set_bokeh_output(notebook=False)

from datetime import timedelta

import sys
sys.path.append('../utils')
import Util
import importlib
importlib.reload(Util)

from enum import Enum
import time

from random import randint
import random

In [2]:
pair = 'GBPJPY'

df_d1_raw = pd.read_csv(f"../Trading Data/{pair}_D1.csv",sep=',', parse_dates=['Date'], index_col='Date')
df_h4_raw = pd.read_csv(f"../Trading Data/{pair}_H4.csv",sep=',', parse_dates=['Date'], index_col='Date')
df_m15_raw = pd.read_csv(f"../Trading Data/{pair}_M15.csv",sep=',', parse_dates=['Date'], index_col='Date')

print(df_d1_raw)
print(df_h4_raw)
print(df_m15_raw)

               Open     High      Low    Close  Tickvol
Date
2010-09-10  129.605  130.065  128.995  129.255   172229
2010-09-13  129.565  130.115  128.780  129.090   215859
2010-09-14  129.105  129.430  127.640  129.015   226170
2010-09-15  129.015  134.070  128.555  133.975   252317
2010-09-16  133.975  134.260  132.970  134.150   222443
...             ...      ...      ...      ...      ...
2026-09-18  208.323  211.276  208.233  210.095   364707
2026-09-21  210.296  210.762  209.676  210.321   243731
2026-09-22  210.321  210.892  209.513  210.080   333200
2026-09-23  210.080  210.176  209.422  209.564   273936
2026-09-24  209.566  210.105  208.768  209.848   199988

[4183 rows x 5 columns]
                        Open     High      Low    Close  Tickvol
Date
2010-09-10 04:00:00  129.605  129.630  128.995  129.385    25539
2010-09-10 08:00:00  129.380  129.985  129.275  129.785    44503
2010-09-10 12:00:00  129.785  130.065  129.425  129.570    54127
2010-09-10 16:00:00  129.580  129.770  129.120  129.135    39740
2010-09-10 20:00:00  129.130  129.335  129.120  129.255     8320
...                      ...      ...      ...      ...      ...
2026-09-23 20:00:00  209.580  209.701  209.431  209.564    16661
2026-09-24 00:00:00  209.566  209.638  208.768  209.072    51880
2026-09-24 04:00:00  209.072  209.859  209.019  209.838    38121
2026-09-24 08:00:00  209.840  210.067  209.417  209.996    62442
2026-09-24 12:00:00  209.997  210.105  209.846  209.848    47545

[25029 rows x 5 columns]
                        Open     High      Low    Close  Tickvol
Date
2020-08-19 16:15:00  139.383  139.441  139.350  139.420    13401
2020-08-19 16:30:00  139.420  139.504  139.397  139.493     2033
2020-08-19 16:45:00  139.495  139.495  139.427  139.441     1798
2020-08-19 17:00:00  139.441  139.441  139.324  139.329     2242
2020-08-19 17:15:00  139.331  139.352  139.272  139.272     2696
...                      ...      ...      ...      ...      ...
2026-09-24 18:45:00  209.996  210.001  209.932  209.961     2550
2026-09-24 19:00:00  209.961  209.998  209.888  209.938     4040
2026-09-24 19:15:00  209.939  209.960  209.918  209.954     3388
2026-09-24 19:30:00  209.953  209.959  209.902  209.931     3296
2026-09-24 19:45:00  209.932  209.954  209.914  209.945     3174

[150000 rows x 5 columns]

In [3]:
structure_d1_window = 2
structure_m15_window = 2

date_format = '%Y-%m-%d %H:%M'
# start_date = '2023-1-1 00:00'
# end_date = '2024-3-29 00:00'
start_date = datetime.strptime('2021-1-1 00:00', date_format)
end_date = datetime.strptime('2026-9-16 00:00', date_format)
# start_date = '2022-01-1 00:00'

timezone = "Europe/London"

# nombre de jours pour les high.low
define_key_level_window = 90

gap_look_ahead = 6

# nombre de candle au dessus/ en desous de key level après breakout
breakout_candles = 9

# nombre de jours à chercher key level
key_level_lookback_candle = 100

# vérifier si 30 candle dans ke passé pour valider un valid breakout,
# un valid breakout doit avoir {breakout_candles} candles au dessus du resistant level
breakout_candles_lookback = 30

start_trade_hour = 9
stop_trade_hour = 19

atr_multiplier = 0.7
min_touched = 3

In [4]:
# process h4 data
df_h4 = df_h4_raw.loc[start_date - timedelta(days=20) : end_date]
df_h4 = Util.implement_market_structure_states_fixed_pivots(df_h4, 5)
df_h4 = df_h4.loc[start_date : end_date]

indicator_atr_14 = AverageTrueRange(df_h4['High'], df_h4['Low'], df_h4['Close'], window=14)
df_h4['ATR'] = indicator_atr_14._atr

df_h4

,Open,High,Low,Close,Tickvol,is_swing_high,is_swing_low,market_state,ATR
Date,,,,,,,,,
2021-01-04 00:00:00,140.944,141.304,140.776,141.005,37352,True,False,BULLISH,0.000000
2021-01-04 04:00:00,141.007,141.043,140.847,140.938,20550,False,False,BULLISH,0.000000
2021-01-04 08:00:00,140.936,141.064,140.412,140.757,47343,False,False,BULLISH,0.000000
2021-01-04 12:00:00,140.758,140.861,140.188,140.226,55445,False,False,BULLISH,0.000000
2021-01-04 16:00:00,140.227,140.233,139.687,139.870,55631,False,False,BULLISH,0.000000
...,...,...,...,...,...,...,...,...,...
2026-09-15 08:00:00,208.652,209.090,208.514,208.655,56407,False,False,BEARISH,0.567701
2026-09-15 12:00:00,208.655,209.211,208.607,209.168,74480,False,False,BULLISH,0.570294
2026-09-15 16:00:00,209.167,209.224,208.885,209.066,38410,False,False,BULLISH,0.553773
2026-09-15 20:00:00,209.064,209.082,208.872,209.019,18776,False,False,BULLISH,0.529218
2026-09-16 00:00:00,209.018,209.394,208.982,209.259,52853,False,False,BULLISH,0.520845

In [5]:
resistants_list = Util.define_resistant_level_with_atr(df_h4, define_key_level_window, atr_multiplier=atr_multiplier, min_touched=min_touched)
supports_list = Util.define_support_level_with_atr(df_h4, define_key_level_window, atr_multiplier=atr_multiplier, min_touched=min_touched)

df_h4['support_point'] = df_h4.apply(lambda row: Util.support_pos(supports_list, row), axis=1)
df_h4['is_support'] = df_h4.apply(lambda row: Util.is_support(supports_list, row), axis=1)

df_h4['resistant_point'] = df_h4.apply(lambda row: Util.resistant_pos(resistants_list, row), axis=1)
df_h4['is_resistant'] = df_h4.apply(lambda row: Util.is_resistant(resistants_list, row), axis=1)

df_h4['valid_breakout_support_levels'] = Util.is_candles_above_support_level_list(df_h4, breakout_candles, key_level_lookback_candle)
df_h4['valid_breakout_resistant_levels'] = Util.is_candles_below_resistant_level_list(df_h4, breakout_candles, key_level_lookback_candle)

In [27]:
# process m15 data
df_m15 = df_m15_raw.loc[start_date - timedelta(hours=3): end_date]
df_m15 = Util.implement_market_structure_states_fixed_pivots(df_m15, n=structure_m15_window)

m15_h4_resistant_level_list = []
m15_is_resistants_list = []
m15_is_below_resistant_list = []

m15_h4_support_level_list = []
m15_is_supports_list = []
m15_is_above_support_list = []

index_list = []

indicator_atr_m15 = AverageTrueRange(df_m15['High'], df_m15['Low'], df_m15['Close'], window=14)
df_m15['ATR'] = indicator_atr_m15._atr

df_m15 = df_m15.loc[start_date : end_date]
for i in range(len(df_h4)):
    row = df_h4.iloc[i]
    start_date_h4 = row.name
    end_date_h4 = start_date_h4 + timedelta(hours=3, minutes=59)
    df_by_day = df_m15.loc[f'{start_date_h4}' : f'{end_date_h4}']

    for index2, row2 in df_by_day.iterrows():
        m15_h4_resistant_level_list.append(df_h4.iloc[i]['resistant_point'])
        m15_is_resistants_list.append(df_h4.iloc[i]['is_resistant'])
        m15_is_below_resistant_list.append(df_h4.iloc[i]['valid_breakout_resistant_levels'])
        # affect current market states of H4 candle because the result is market state of previous D1 candle

        m15_h4_support_level_list.append(df_h4.iloc[i]['support_point'])
        m15_is_supports_list.append(df_h4.iloc[i]['is_support'])
        m15_is_above_support_list.append(df_h4.iloc[i]['valid_breakout_support_levels'])

        # ajust to daylight saving time
        dst = pd.Timestamp(index2, tz=timezone).dst()
        if dst == timedelta(0):
            index2 = index2 - timedelta(hours=1)
            index_list.append(index2)
        else:
            index_list.append(index2)

df_m15['resistant_point'] = m15_h4_resistant_level_list
df_m15['is_resistant'] = m15_is_resistants_list
df_m15['valid_breakout_resistant_levels'] = m15_is_below_resistant_list

df_m15['support_point'] = m15_h4_support_level_list
df_m15['is_support'] = m15_is_supports_list
df_m15['valid_breakout_support_levels'] = m15_is_above_support_list

df_m15.index = index_list

df_m15

,Open,High,Low,Close,Tickvol,is_swing_high,is_swing_low,market_state,ATR,resistant_point,is_resistant,valid_breakout_resistant_levels,support_point,is_support,valid_breakout_support_levels
2021-01-03 23:00:00,140.944,141.110,140.944,141.100,2767,False,True,NaN,0.000000,NaN,False,[207.258],NaN,False,[]
2021-01-03 23:15:00,141.099,141.204,141.070,141.186,1223,False,False,NaN,0.000000,NaN,False,[207.258],NaN,False,[]
2021-01-03 23:30:00,141.186,141.304,141.158,141.282,1042,True,False,NaN,0.000000,NaN,False,[207.258],NaN,False,[]
2021-01-03 23:45:00,141.278,141.301,141.218,141.244,1886,False,False,NaN,0.000000,NaN,False,[207.258],NaN,False,[]
2021-01-04 00:00:00,141.247,141.275,140.988,141.007,3577,False,False,BEARISH,0.000000,NaN,False,[207.258],NaN,False,[]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2026-09-15 23:00:00,208.895,209.029,208.895,209.018,1853,True,False,BEARISH,0.084410,NaN,False,[],NaN,False,[]
2026-09-15 23:15:00,209.020,209.027,208.982,208.996,1268,False,False,BEARISH,0.081595,NaN,False,[],NaN,False,[]
2026-09-15 23:30:00,208.997,209.013,208.926,208.953,1279,False,False,BEARISH,0.081981,NaN,False,[],NaN,False,[]
2026-09-15 23:45:00,208.951,209.021,208.923,209.019,1261,False,False,BEARISH,0.083126,NaN,False,[],NaN,False,[]
2026-09-16 00:00:00,209.018,209.108,209.007,209.075,2780,False,False,BULLISH,0.084402,NaN,False,[],NaN,False,[]

In [7]:
def is_existed(list, value):
    for i in range(len(list)):
        if list[i] == value:
            return True
    return False

In [28]:
# using m15 market structure for entry
def apply_total_signal(df, key_level_lookback_candle = 150, gap=1, breakout_candles_lookback = 30, start_trade_hour=8, stop_trade_hour=19):
    # Initialize the 'TotalSignal' column
    df_signal_list = []
    valid_support_levels_list = []
    valid_resistant_levels_list = []
    current_day = None

    # short variables
    is_resistant_level_touched = False
    is_below_resistant_levels = False
    high_tf_condition_short_satisfied = False
    high_tf_condition_short_candle = None
    m15_market_state_bearish = False

    # long variables
    is_support_level_touched = False
    is_above_support_levels = False
    high_tf_condition_long_satisfied = False
    high_tf_condition_long_candle = None
    m15_market_state_bullish = False

    # we want market structure to switch from bearish to bullish when htf conditions are met
    # if market structure is already bullish we need to wait
    previous_market_structure = None

    resistants_levels_touched = []
    supports_levels_touched = []

    for i in range(0, len(df)):
        current_bar_date = df.index[i]
        signal = 0
        # valid resistants levels are when valid breakout and levels touched
        valid_resistant_levels = []
        valid_support_levels = []

        if current_day != current_bar_date.date() or current_bar_date.time().hour >= stop_trade_hour:
            current_day = current_bar_date.date()
            # short
            high_tf_condition_short_satisfied = False
            resistants_levels_touched = []
            is_resistant_level_touched = False
            valid_breakout_resistant_levels = []
            is_below_resistant_levels = False

            # long
            high_tf_condition_long_satisfied = False
            supports_levels_touched = []
            is_support_level_touched = False
            valid_breakout_support_levels = []
            is_above_support_levels = False

        # short
        c_m15_ms_bearish = df['market_state'].iloc[i] == 'BEARISH'

        # h4 key level conditions
        resistants_levels = Util.get_resistant_list(df, i, key_level_lookback_candle, gap, Util.TimeFrame.M15)
        for level in resistants_levels:
            if df['High'].iloc[i-1] > level:
                is_resistant_level_touched = True
                if not is_existed(resistants_levels_touched, level):
                    resistants_levels_touched.append(level)
        
        # Combine conditions
        if (is_resistant_level_touched and
            not high_tf_condition_short_satisfied):
            high_tf_condition_short_satisfied = True
            high_tf_condition_short_candle = current_bar_date
            previous_market_structure = df['market_state'].iloc[i]
            print(f"{current_bar_date} {i}")

        if (high_tf_condition_short_satisfied == True and
            c_m15_ms_bearish and
            high_tf_condition_short_candle < current_bar_date and
            previous_market_structure == 'BULLISH'):
            m15_market_state_bearish = True

        # breakout_candles_below candle needs to be below resistant level for the breakout to be valid
        valid_breakout_resistant_levels = Util.get_valid_breakout_resistant_level(df, i, breakout_candles_lookback)
        
        for valid_level in valid_breakout_resistant_levels:
            for level_touched in resistants_levels_touched:
                if valid_level == level_touched:
                    valid_resistant_levels.append(valid_level)
                    is_below_resistant_levels = True

        c_time_trade = start_trade_hour <= current_bar_date.hour and current_bar_date.hour <= stop_trade_hour
        if c_time_trade:
            if (high_tf_condition_short_satisfied == True and
                m15_market_state_bearish and
                is_below_resistant_levels):
                signal = 1

        # long
        c_m15_ms_bullish = df['market_state'].iloc[i] == 'BULLISH'
        
        # h4 support level conditions
        supports_levels = Util.get_support_list(df, i, key_level_lookback_candle, gap, Util.TimeFrame.M15)
        for level in supports_levels:
            if df['Low'].iloc[i-1] < level:
                is_support_level_touched = True
                if not is_existed(supports_levels_touched, level):
                    supports_levels_touched.append(level)

        # Combine conditions
        if (is_support_level_touched and
            not high_tf_condition_long_satisfied):
            high_tf_condition_long_satisfied = True
            m15_market_state_bullish = False
            high_tf_condition_long_candle = current_bar_date
            previous_market_structure = df['market_state'].iloc[i]
            # print(f"high_tf_condition_long_satisfied {current_bar_date} {i}")

        if (high_tf_condition_long_satisfied and
            c_m15_ms_bullish and
            high_tf_condition_long_candle < current_bar_date and
            previous_market_structure == 'BEARISH'):
            # print(f"m15_market_state_bullish {current_bar_date} {i}")
            m15_market_state_bullish = True

        # breakout_candles_above candle needs to be above support level for the breakout to be valid
        valid_breakout_support_levels = Util.get_valid_breakout_support_level(df, i, breakout_candles_lookback)
        for valid_level in valid_breakout_support_levels:
            for level_touched in supports_levels_touched:
                if valid_level == level_touched:
                    valid_support_levels.append(valid_level)
                    is_above_support_levels = True

        c_time_trade = start_trade_hour <= current_bar_date.hour and current_bar_date.hour <= stop_trade_hour
        if c_time_trade:
            if (high_tf_condition_long_satisfied == True and
                m15_market_state_bullish and
                is_above_support_levels):
                print(f"signal {current_bar_date} {i}")
                signal = 2

        if previous_market_structure != df['market_state'].iloc[i]:
            if df['market_state'].iloc[i] == 'BULLISH':
                m15_market_state_bearish = False
            if df['market_state'].iloc[i] == 'BEARISH':
                m15_market_state_bullish = False
            previous_market_structure = df['market_state'].iloc[i]    

        df_signal_list.append(signal)
        valid_resistant_levels_list.append(valid_resistant_levels)
        valid_support_levels_list.append(valid_support_levels)

    return df_signal_list, valid_resistant_levels_list, valid_support_levels_list

df_m15['TotalSignal'], df_m15['valid_resistant_levels'], df_m15['valid_support_levels'] = apply_total_signal(df=df_m15, key_level_lookback_candle=key_level_lookback_candle, gap=gap_look_ahead,
                                                                            breakout_candles_lookback=breakout_candles_lookback, start_trade_hour=start_trade_hour, stop_trade_hour=stop_trade_hour)

2021-01-03 23:00:00 0
2021-04-16 05:45:00 7055
2021-04-16 19:00:00 7108
2021-04-16 19:15:00 7109
2021-04-16 19:30:00 7110
2021-04-16 19:45:00 7111
2021-04-16 20:00:00 7112
2021-04-16 20:15:00 7113
2021-04-16 20:30:00 7114
2021-04-16 20:45:00 7115
2021-04-16 21:00:00 7116
2021-04-16 21:15:00 7117
2021-04-16 21:30:00 7118
2021-04-16 21:45:00 7119
2021-04-19 00:00:00 7120
2021-04-19 19:00:00 7196
2021-04-19 19:15:00 7197
2021-04-19 19:30:00 7198
2021-04-19 19:45:00 7199
2021-04-19 20:00:00 7200
2021-04-19 20:15:00 7201
2021-04-19 20:30:00 7202
2021-04-19 20:45:00 7203
2021-04-19 21:00:00 7204
2021-04-19 21:15:00 7205
2021-04-19 21:30:00 7206
2021-04-19 21:45:00 7207
2021-04-19 22:00:00 7208
2021-04-19 22:15:00 7209
2021-04-19 22:30:00 7210
2021-04-19 22:45:00 7211
2021-04-19 23:00:00 7212
2021-04-19 23:15:00 7213
2021-04-19 23:30:00 7214
2021-04-19 23:45:00 7215
2021-04-20 00:00:00 7216
2021-04-20 19:00:00 7292
2021-04-20 19:15:00 7293
2021-04-20 19:30:00 7294
2021-04-20 19:45:00 7295
2021-04-20 20:00:00 7296
2021-04-20 20:15:00 7297
2021-04-20 20:30:00 7298
2021-04-20 20:45:00 7299
2021-04-20 21:00:00 7300
2021-04-20 21:15:00 7301
2021-04-20 21:30:00 7302
2021-04-20 21:45:00 7303
2021-04-20 22:00:00 7304
2021-04-20 22:15:00 7305
2021-04-20 22:30:00 7306
2021-04-20 22:45:00 7307
2021-04-20 23:00:00 7308
2021-04-20 23:15:00 7309
2021-04-20 23:30:00 7310
2021-04-20 23:45:00 7311
2021-04-21 00:00:00 7312
2021-04-21 19:00:00 7388
2021-04-21 19:15:00 7389
2021-04-21 19:30:00 7390
2021-04-21 19:45:00 7391
2021-04-21 20:00:00 7392
2021-04-21 20:15:00 7393
2021-04-21 20:30:00 7394
2021-04-21 20:45:00 7395
2021-04-21 21:00:00 7396
2021-04-21 21:15:00 7397
2021-04-21 21:30:00 7398
2021-04-21 21:45:00 7399
2021-04-21 22:00:00 7400
2021-04-21 22:15:00 7401
2021-04-21 22:30:00 7402
2021-04-21 22:45:00 7403
2021-04-21 23:00:00 7404
2021-04-21 23:15:00 7405
2021-04-21 23:30:00 7406
2021-04-21 23:45:00 7407
2021-04-22 00:00:00 7408
2021-04-22 19:00:00 7484
2021-04-22 19:15:00 7485
2021-04-22 19:30:00 7486
2021-04-22 19:45:00 7487
2021-04-22 20:00:00 7488
2021-04-22 20:15:00 7489
2021-04-22 20:30:00 7490
2021-04-22 20:45:00 7491
2021-04-22 21:00:00 7492
2021-04-23 02:45:00 7515
2021-04-23 19:00:00 7580
2021-04-23 19:15:00 7581
2021-04-23 19:30:00 7582
2021-04-23 19:45:00 7583
2021-04-23 20:00:00 7584
2021-04-23 20:15:00 7585
2021-04-23 20:30:00 7586
2021-04-23 20:45:00 7587
2021-04-23 21:00:00 7588
2021-04-23 21:15:00 7589
2021-04-23 21:30:00 7590
2021-04-23 21:45:00 7591
2021-04-26 00:00:00 7592
2021-04-26 19:00:00 7668
2021-04-26 19:15:00 7669
2021-04-26 19:30:00 7670
2021-04-26 19:45:00 7671
2021-04-26 20:00:00 7672
2021-04-26 20:15:00 7673
2021-04-26 20:30:00 7674
2021-04-26 20:45:00 7675
2021-04-26 21:00:00 7676
2021-04-26 21:15:00 7677
2021-04-26 21:30:00 7678
2021-04-26 21:45:00 7679
2021-04-26 22:00:00 7680
2021-04-26 22:15:00 7681
2021-04-26 22:30:00 7682
2021-04-26 22:45:00 7683
2021-04-26 23:00:00 7684
2021-04-26 23:15:00 7685
2021-04-26 23:30:00 7686
2021-04-26 23:45:00 7687
2021-04-27 00:00:00 7688
2021-04-27 19:00:00 7764
2021-04-27 19:15:00 7765
2021-04-27 19:30:00 7766
2021-04-27 19:45:00 7767
2021-04-27 20:00:00 7768
2021-04-27 20:15:00 7769
2021-04-27 20:30:00 7770
2021-04-27 20:45:00 7771
2021-04-27 21:00:00 7772
2021-04-27 21:15:00 7773
2021-04-27 21:30:00 7774
2021-04-27 21:45:00 7775
2021-04-27 22:00:00 7776
2021-04-27 22:15:00 7777
2021-04-27 22:30:00 7778
2021-04-27 22:45:00 7779
2021-04-27 23:00:00 7780
2021-04-27 23:15:00 7781
2021-04-27 23:30:00 7782
2021-04-27 23:45:00 7783
2021-04-28 00:00:00 7784
2021-04-28 19:00:00 7860
2021-04-28 19:15:00 7861
2021-04-28 19:30:00 7862
2021-04-28 19:45:00 7863
2021-04-28 20:00:00 7864
2021-04-28 20:15:00 7865
2021-04-28 20:30:00 7866
2021-04-28 20:45:00 7867
2021-04-28 21:00:00 7868
2021-04-28 21:15:00 7869
2021-04-28 21:30:00 7870
2021-04-28 21:45:00 7871
2021-04-28 22:00:00 7872
2021-04-28 22:15:00 7873
2021-04-28 22:30:00 7874
2021-04-28 22:45:00 7875
2021-04-28 23:00:00 7876
2021-04-28 23:15:00 7877
2021-04-28 23:30:00 7878
2021-04-28 23:45:00 7879
2021-04-29 00:00:00 7880
2021-04-29 19:00:00 7956
2021-04-29 19:15:00 7957
2021-04-29 19:30:00 7958
2021-04-29 19:45:00 7959
2021-04-29 20:00:00 7960
2021-04-29 20:15:00 7961
2021-04-29 20:30:00 7962
2021-04-29 20:45:00 7963
2021-04-29 21:00:00 7964
2021-04-29 21:15:00 7965
2021-04-29 21:30:00 7966
2021-04-29 21:45:00 7967
2021-04-29 22:00:00 7968
2021-04-29 22:15:00 7969
2021-04-29 22:30:00 7970
2021-04-29 22:45:00 7971
2021-04-29 23:00:00 7972
2021-04-29 23:15:00 7973
2021-04-29 23:30:00 7974
2021-04-29 23:45:00 7975
2021-04-30 00:00:00 7976
2021-04-30 19:00:00 8052
2021-04-30 19:15:00 8053
2021-04-30 19:30:00 8054
2021-04-30 19:45:00 8055
2021-04-30 20:00:00 8056
2021-04-30 20:15:00 8057
2021-04-30 20:30:00 8058
2021-04-30 20:45:00 8059
2021-04-30 21:00:00 8060
2021-04-30 21:15:00 8061
2021-04-30 21:30:00 8062
2021-04-30 21:45:00 8063
2021-05-03 00:00:00 8064
2021-05-03 19:00:00 8140
2021-05-03 19:15:00 8141
2021-05-03 19:30:00 8142
2021-05-03 19:45:00 8143
2021-05-03 20:00:00 8144
2021-05-03 20:15:00 8145
2021-05-03 20:30:00 8146
2021-05-03 20:45:00 8147
2021-05-03 21:00:00 8148
2021-05-03 21:15:00 8149
2021-05-03 21:30:00 8150
2021-05-03 21:45:00 8151
2021-05-03 22:00:00 8152
2021-05-03 22:15:00 8153
2021-05-03 22:30:00 8154
2021-05-03 22:45:00 8155
2021-05-03 23:00:00 8156
2021-05-03 23:15:00 8157
2021-05-03 23:30:00 8158
2021-05-03 23:45:00 8159
2021-05-04 00:00:00 8160
2021-05-04 19:00:00 8236
2021-05-04 19:15:00 8237
2021-05-04 19:30:00 8238
2021-05-04 19:45:00 8239
2021-05-04 20:00:00 8240
2021-05-04 20:15:00 8241
2021-05-04 20:30:00 8242
2021-05-04 20:45:00 8243
2021-05-04 21:00:00 8244
2021-05-04 21:15:00 8245
2021-05-04 21:30:00 8246
2021-05-04 21:45:00 8247
2021-05-04 22:00:00 8248
2021-05-04 22:15:00 8249
2021-05-04 22:30:00 8250
2021-05-04 22:45:00 8251
2021-05-04 23:00:00 8252
2021-05-04 23:15:00 8253
2021-05-04 23:30:00 8254
2021-05-04 23:45:00 8255
2021-05-05 00:00:00 8256
2021-05-05 19:00:00 8332
2021-05-05 19:15:00 8333
2021-05-05 19:30:00 8334
2021-05-05 19:45:00 8335
2021-05-05 20:00:00 8336
2021-05-05 20:15:00 8337
2021-05-05 20:30:00 8338
2021-05-05 20:45:00 8339
2021-05-05 21:00:00 8340
2021-05-05 21:15:00 8341
2021-05-05 21:30:00 8342
2021-05-05 21:45:00 8343
2021-05-05 22:00:00 8344
2021-05-05 22:15:00 8345
2021-05-05 22:30:00 8346
2021-05-05 22:45:00 8347
2021-05-05 23:00:00 8348
2021-05-05 23:15:00 8349
2021-05-05 23:30:00 8350
2021-05-05 23:45:00 8351
2021-05-06 00:00:00 8352
2021-05-06 19:00:00 8428
2021-05-06 19:15:00 8429
2021-05-06 19:30:00 8430
2021-05-06 19:45:00 8431
2021-05-06 20:00:00 8432
2021-05-06 20:15:00 8433
2021-05-06 20:30:00 8434
2021-05-06 20:45:00 8435
2021-05-06 21:00:00 8436
2021-05-06 21:15:00 8437
2021-05-06 21:30:00 8438
2021-05-06 21:45:00 8439
2021-05-06 22:00:00 8440
2021-05-06 22:15:00 8441
2021-05-06 22:30:00 8442
2021-05-06 22:45:00 8443
2021-05-06 23:00:00 8444
2021-05-06 23:15:00 8445
2021-05-06 23:30:00 8446
2021-05-06 23:45:00 8447
2021-05-07 00:00:00 8448
2021-05-07 19:00:00 8524
2021-05-07 19:15:00 8525
2021-05-07 19:30:00 8526
2021-05-07 19:45:00 8527
2021-05-07 20:00:00 8528
2021-05-07 20:15:00 8529
2021-05-07 20:30:00 8530
2021-05-07 20:45:00 8531
2021-05-07 21:00:00 8532
2021-05-07 21:15:00 8533
2021-05-07 21:30:00 8534
2021-05-07 21:45:00 8535
2021-05-10 00:00:00 8536
2021-05-10 19:00:00 8612
2021-05-10 19:15:00 8613
2021-05-10 19:30:00 8614
2021-05-10 19:45:00 8615
2021-05-10 20:00:00 8616
2021-05-10 20:15:00 8617
2021-05-10 20:30:00 8618
2021-05-10 20:45:00 8619
2021-05-10 21:00:00 8620
2021-05-10 21:15:00 8621
2021-05-10 21:30:00 8622
2021-05-10 21:45:00 8623
2021-05-10 22:00:00 8624
2021-05-10 22:15:00 8625
2021-05-10 22:30:00 8626
2021-05-10 22:45:00 8627
2021-05-10 23:00:00 8628
2021-05-10 23:15:00 8629
2021-05-10 23:30:00 8630
2021-05-10 23:45:00 8631
2021-05-11 00:00:00 8632
2021-05-19 13:45:00 9255
2021-05-19 19:00:00 9276
2021-05-19 19:15:00 9277
2021-05-19 19:30:00 9278
2021-05-19 19:45:00 9279
2021-05-19 20:00:00 9280
2021-05-19 20:15:00 9281
2021-05-19 20:30:00 9282
2021-05-19 20:45:00 9283
2021-05-19 21:00:00 9284
2021-05-19 21:15:00 9285
2021-05-19 21:30:00 9286
2021-05-19 21:45:00 9287
2021-05-19 22:00:00 9288
2021-05-19 22:15:00 9289
2021-05-19 22:30:00 9290
2021-05-19 22:45:00 9291
2021-05-19 23:00:00 9292
2021-05-19 23:15:00 9293
2021-05-19 23:30:00 9294
2021-05-19 23:45:00 9295
2021-05-20 00:00:00 9296
2021-05-20 19:00:00 9372
2021-05-20 19:15:00 9373
2021-05-20 19:30:00 9374
2021-05-20 19:45:00 9375
2021-05-20 20:00:00 9376
2021-05-20 20:15:00 9377
2021-05-20 20:30:00 9378
2021-05-20 20:45:00 9379
2021-05-20 21:00:00 9380
2021-05-20 21:15:00 9381
2021-05-20 21:30:00 9382
2021-05-20 21:45:00 9383
2021-05-20 22:00:00 9384
2021-05-20 22:15:00 9385
2021-05-20 22:30:00 9386
2021-05-20 22:45:00 9387
2021-05-20 23:00:00 9388
2021-05-20 23:15:00 9389
2021-05-20 23:30:00 9390
2021-05-20 23:45:00 9391
2021-05-21 00:00:00 9392
2021-05-21 19:00:00 9468
2021-05-21 19:15:00 9469
2021-05-21 19:30:00 9470
2021-05-21 19:45:00 9471
2021-05-21 20:00:00 9472
2021-05-21 20:15:00 9473
2021-05-21 20:30:00 9474
2021-05-21 20:45:00 9475
2021-05-21 21:00:00 9476
2021-05-21 21:15:00 9477
2021-05-21 21:30:00 9478
2021-05-21 21:45:00 9479
2021-05-24 00:00:00 9480
2021-05-24 19:00:00 9556
2021-05-24 19:15:00 9557
2021-05-24 19:30:00 9558
2021-05-24 19:45:00 9559
2021-05-24 20:00:00 9560
2021-05-24 20:15:00 9561
2021-05-24 20:30:00 9562
2021-05-24 20:45:00 9563
2021-05-24 21:00:00 9564
2021-05-24 21:15:00 9565
2021-05-24 21:30:00 9566
2021-05-24 21:45:00 9567
2021-05-24 22:00:00 9568
2021-05-24 22:15:00 9569
2021-05-24 22:30:00 9570
2021-05-24 22:45:00 9571
2021-05-24 23:00:00 9572
2021-05-24 23:15:00 9573
2021-05-24 23:30:00 9574
2021-05-24 23:45:00 9575
2021-05-25 00:00:00 9576
2021-05-25 19:00:00 9652
2021-05-25 19:15:00 9653
2021-05-25 19:30:00 9654
2021-05-25 19:45:00 9655
2021-05-25 20:00:00 9656
2021-05-25 20:15:00 9657
2021-05-25 20:30:00 9658
2021-05-25 20:45:00 9659
2021-05-25 21:00:00 9660
2021-05-25 21:15:00 9661
2021-05-25 21:30:00 9662
2021-05-25 21:45:00 9663
2021-05-25 22:00:00 9664
2021-05-25 22:15:00 9665
2021-05-25 22:30:00 9666
2021-05-25 22:45:00 9667
2021-05-25 23:00:00 9668
2021-05-25 23:15:00 9669
2021-05-25 23:30:00 9670
2021-05-25 23:45:00 9671
2021-05-26 00:00:00 9672
2021-05-26 19:00:00 9748
2021-05-26 19:15:00 9749
2021-05-26 19:30:00 9750
2021-05-26 19:45:00 9751
2021-05-26 20:00:00 9752
2021-05-26 20:15:00 9753
2021-05-26 20:30:00 9754
2021-05-26 20:45:00 9755
2021-05-26 21:00:00 9756
2021-05-26 21:15:00 9757
2021-05-26 21:30:00 9758
2021-05-26 21:45:00 9759
2021-05-26 22:00:00 9760
2021-05-26 22:15:00 9761
2021-05-26 22:30:00 9762
2021-05-26 22:45:00 9763
2021-05-26 23:00:00 9764
2021-05-26 23:15:00 9765
2021-05-26 23:30:00 9766
2021-05-26 23:45:00 9767
2021-05-27 00:00:00 9768
2021-05-27 19:00:00 9844
2021-05-27 19:15:00 9845
2021-05-27 19:30:00 9846
2021-05-27 19:45:00 9847
2021-05-27 20:00:00 9848
2021-05-27 20:15:00 9849
2021-05-27 20:30:00 9850
2021-05-27 20:45:00 9851
2021-05-27 21:00:00 9852
2021-05-27 21:15:00 9853
2021-05-27 21:30:00 9854
2021-05-27 21:45:00 9855
2021-05-27 22:00:00 9856
2021-05-27 22:15:00 9857
2021-05-27 22:30:00 9858
2021-05-27 22:45:00 9859
2021-05-27 23:00:00 9860
2021-05-27 23:15:00 9861
2021-05-27 23:30:00 9862
2021-05-27 23:45:00 9863
2021-05-28 00:00:00 9864
2021-05-28 19:00:00 9940
2021-05-28 19:15:00 9941
2021-05-28 19:30:00 9942
2021-05-28 19:45:00 9943
2021-05-28 20:00:00 9944
2021-05-28 20:15:00 9945
2021-05-28 20:30:00 9946
2021-05-28 20:45:00 9947
2021-05-28 21:00:00 9948
2021-05-28 21:15:00 9949
2021-05-28 21:30:00 9950
2021-05-28 21:45:00 9951
2021-05-31 00:00:00 9952
2021-05-31 19:00:00 10028
2021-05-31 19:15:00 10029
2021-05-31 19:30:00 10030
2021-05-31 19:45:00 10031
2021-05-31 20:00:00 10032
2021-05-31 20:15:00 10033
2021-05-31 20:30:00 10034
2021-05-31 20:45:00 10035
2021-05-31 21:00:00 10036
2021-05-31 21:15:00 10037
2021-05-31 21:30:00 10038
2021-05-31 21:45:00 10039
2021-05-31 22:00:00 10040
2021-05-31 22:15:00 10041
2021-05-31 22:30:00 10042
2021-05-31 22:45:00 10043
2021-05-31 23:00:00 10044
2021-05-31 23:15:00 10045
2021-05-31 23:30:00 10046
2021-05-31 23:45:00 10047
2021-06-01 00:00:00 10048
2021-06-01 19:00:00 10124
2021-06-01 19:15:00 10125
2021-06-01 19:30:00 10126
2021-06-01 19:45:00 10127
2021-06-01 20:00:00 10128
2021-06-01 20:15:00 10129
2021-06-01 20:30:00 10130
2021-06-01 20:45:00 10131
2021-06-01 21:00:00 10132
2021-06-01 21:15:00 10133
2021-06-01 21:30:00 10134
2021-06-01 21:45:00 10135
2021-06-01 22:00:00 10136
2021-06-01 22:15:00 10137
2021-06-01 22:30:00 10138
2021-06-01 22:45:00 10139
2021-06-01 23:00:00 10140
2021-06-01 23:15:00 10141
2021-06-01 23:30:00 10142
2021-06-01 23:45:00 10143
2021-06-02 00:00:00 10144
2021-06-02 19:00:00 10220
2021-06-02 19:15:00 10221
2021-06-02 19:30:00 10222
2021-06-02 19:45:00 10223
2021-06-02 20:00:00 10224
2021-06-02 20:15:00 10225
2021-06-02 20:30:00 10226
2021-06-02 20:45:00 10227
2021-06-02 21:00:00 10228
2021-06-02 21:15:00 10229
2021-06-02 21:30:00 10230
2021-06-02 21:45:00 10231
2021-06-02 22:00:00 10232
2021-06-02 22:15:00 10233
2021-06-02 22:30:00 10234
2021-06-02 22:45:00 10235
2021-06-02 23:00:00 10236
2021-06-02 23:15:00 10237
2021-06-02 23:30:00 10238
2021-06-02 23:45:00 10239
2021-06-03 00:00:00 10240
2021-06-03 19:00:00 10316
2021-06-03 19:15:00 10317
2021-06-03 19:30:00 10318
2021-06-03 19:45:00 10319
2021-06-03 20:00:00 10320
2021-06-03 20:15:00 10321
2021-06-03 20:30:00 10322
2021-06-03 20:45:00 10323
2021-06-03 21:00:00 10324
2021-06-03 21:15:00 10325
2021-06-03 21:30:00 10326
2021-06-03 21:45:00 10327
2021-06-03 22:00:00 10328
2021-06-03 22:15:00 10329
2021-06-03 22:30:00 10330
2021-06-03 22:45:00 10331
2021-06-03 23:00:00 10332
2021-06-03 23:15:00 10333
2021-06-03 23:30:00 10334
2021-06-03 23:45:00 10335
2021-06-04 00:00:00 10336
2021-06-04 19:00:00 10412
2021-06-04 19:15:00 10413
2021-06-04 19:30:00 10414
2021-06-04 19:45:00 10415
2021-06-04 20:00:00 10416
2021-06-04 20:15:00 10417
2021-06-04 20:30:00 10418
2021-06-04 20:45:00 10419
2021-06-04 21:00:00 10420
2021-06-04 21:15:00 10421
2021-06-04 21:30:00 10422
2021-06-04 21:45:00 10423
2021-06-07 00:00:00 10424
signal 2021-06-07 12:00:00 10472
signal 2021-06-07 12:15:00 10473
signal 2021-06-07 12:30:00 10474
signal 2021-06-07 12:45:00 10475
signal 2021-06-07 13:00:00 10476
signal 2021-06-07 13:15:00 10477
signal 2021-06-07 13:30:00 10478
signal 2021-06-07 13:45:00 10479
signal 2021-06-07 14:00:00 10480
signal 2021-06-07 14:15:00 10481
signal 2021-06-07 17:00:00 10492
signal 2021-06-07 17:15:00 10493
signal 2021-06-07 17:30:00 10494
signal 2021-06-07 17:45:00 10495
signal 2021-06-07 18:00:00 10496
signal 2021-06-07 18:15:00 10497
signal 2021-06-07 18:30:00 10498
signal 2021-06-07 18:45:00 10499
2021-06-07 19:00:00 10500
2021-06-07 19:15:00 10501
2021-06-07 19:30:00 10502
2021-06-07 19:45:00 10503
2021-06-07 20:00:00 10504
2021-06-07 20:15:00 10505
2021-06-07 20:30:00 10506
2021-06-07 20:45:00 10507
2021-06-07 21:00:00 10508
2021-06-07 21:15:00 10509
2021-06-07 21:30:00 10510
2021-06-07 21:45:00 10511
2021-06-07 22:00:00 10512
2021-06-07 22:15:00 10513
2021-06-07 22:30:00 10514
2021-06-07 22:45:00 10515
2021-06-07 23:00:00 10516
2021-06-07 23:15:00 10517
2021-06-07 23:30:00 10518
2021-06-07 23:45:00 10519
2021-06-08 00:00:00 10520
signal 2021-06-08 15:45:00 10583
signal 2021-06-08 16:00:00 10584
signal 2021-06-08 16:15:00 10585
signal 2021-06-08 16:30:00 10586
signal 2021-06-08 16:45:00 10587
signal 2021-06-08 17:00:00 10588
signal 2021-06-08 17:15:00 10589
signal 2021-06-08 17:30:00 10590
signal 2021-06-08 17:45:00 10591
signal 2021-06-08 18:00:00 10592
signal 2021-06-08 18:15:00 10593
signal 2021-06-08 18:30:00 10594
signal 2021-06-08 18:45:00 10595
2021-06-08 19:00:00 10596
2021-06-08 19:15:00 10597
2021-06-08 19:30:00 10598
2021-06-08 19:45:00 10599
2021-06-08 20:00:00 10600
2021-06-08 20:15:00 10601
2021-06-08 20:30:00 10602
2021-06-08 20:45:00 10603
2021-06-08 21:00:00 10604
2021-06-08 21:15:00 10605
2021-06-08 21:30:00 10606
2021-06-08 21:45:00 10607
2021-06-08 22:00:00 10608
2021-06-08 22:15:00 10609
2021-06-08 22:30:00 10610
2021-06-08 22:45:00 10611
2021-06-08 23:00:00 10612
2021-06-08 23:15:00 10613
2021-06-08 23:30:00 10614
2021-06-08 23:45:00 10615
2021-06-09 00:00:00 10616
2021-06-09 19:00:00 10692
2021-06-09 19:15:00 10693
2021-06-09 19:30:00 10694
2021-06-09 19:45:00 10695
2021-06-09 20:00:00 10696
2021-06-09 20:15:00 10697
2021-06-09 20:30:00 10698
2021-06-09 20:45:00 10699
2021-06-09 21:00:00 10700
2021-06-09 21:15:00 10701
2021-06-09 21:30:00 10702
2021-06-09 21:45:00 10703
2021-06-09 22:00:00 10704
2021-06-09 22:15:00 10705
2021-06-09 22:30:00 10706
2021-06-09 22:45:00 10707
2021-06-09 23:00:00 10708
2021-06-09 23:15:00 10709
2021-06-09 23:30:00 10710
2021-06-09 23:45:00 10711
2021-06-10 00:00:00 10712
signal 2021-06-10 12:30:00 10762
signal 2021-06-10 12:45:00 10763
signal 2021-06-10 13:00:00 10764
signal 2021-06-10 13:15:00 10765
signal 2021-06-10 13:30:00 10766
signal 2021-06-10 13:45:00 10767
signal 2021-06-10 14:00:00 10768
signal 2021-06-10 14:15:00 10769
signal 2021-06-10 14:30:00 10770
signal 2021-06-10 14:45:00 10771
signal 2021-06-10 15:00:00 10772
signal 2021-06-10 15:15:00 10773
signal 2021-06-10 15:30:00 10774
signal 2021-06-10 15:45:00 10775
signal 2021-06-10 16:00:00 10776
2021-06-10 19:00:00 10788
2021-06-10 19:15:00 10789
2021-06-10 19:30:00 10790
2021-06-10 19:45:00 10791
2021-06-10 20:00:00 10792
2021-06-10 20:15:00 10793
2021-06-10 20:30:00 10794
2021-06-10 20:45:00 10795
2021-06-10 21:00:00 10796
2021-06-10 21:15:00 10797
2021-06-10 21:30:00 10798
2021-06-10 21:45:00 10799
2021-06-10 22:00:00 10800
2021-06-10 22:15:00 10801
2021-06-10 22:30:00 10802
2021-06-10 22:45:00 10803
2021-06-10 23:00:00 10804
2021-06-10 23:15:00 10805
2021-06-10 23:30:00 10806
2021-06-10 23:45:00 10807
2021-06-11 00:00:00 10808
2021-06-11 19:00:00 10884
2021-06-11 19:15:00 10885
2021-06-11 19:30:00 10886
2021-06-11 19:45:00 10887
2021-06-11 20:00:00 10888
2021-06-11 20:15:00 10889
2021-06-11 20:30:00 10890
2021-06-11 20:45:00 10891
2021-06-11 21:00:00 10892
2021-06-11 21:15:00 10893
2021-06-11 21:30:00 10894
2021-06-11 21:45:00 10895
2021-06-14 00:00:00 10896
signal 2021-06-14 12:45:00 10947
signal 2021-06-14 13:00:00 10948
signal 2021-06-14 13:15:00 10949
signal 2021-06-14 13:30:00 10950
signal 2021-06-14 13:45:00 10951
signal 2021-06-14 14:00:00 10952
signal 2021-06-14 14:15:00 10953
signal 2021-06-14 14:30:00 10954
signal 2021-06-14 14:45:00 10955
signal 2021-06-14 15:00:00 10956
signal 2021-06-14 15:15:00 10957
signal 2021-06-14 15:30:00 10958
signal 2021-06-14 15:45:00 10959
signal 2021-06-14 16:00:00 10960
signal 2021-06-14 16:15:00 10961
signal 2021-06-14 16:30:00 10962
signal 2021-06-14 16:45:00 10963
signal 2021-06-14 17:00:00 10964
signal 2021-06-14 17:15:00 10965
signal 2021-06-14 17:30:00 10966
signal 2021-06-14 17:45:00 10967
signal 2021-06-14 18:00:00 10968
signal 2021-06-14 18:15:00 10969
signal 2021-06-14 18:30:00 10970
signal 2021-06-14 18:45:00 10971
2021-06-14 19:00:00 10972
2021-06-14 19:15:00 10973
2021-06-14 19:30:00 10974
2021-06-14 19:45:00 10975
2021-06-14 20:00:00 10976
2021-06-14 20:15:00 10977
2021-06-14 20:30:00 10978
2021-06-14 20:45:00 10979
2021-06-14 21:00:00 10980
2021-06-14 21:15:00 10981
2021-06-14 21:30:00 10982
2021-06-14 21:45:00 10983
2021-06-14 22:00:00 10984
2021-06-14 22:15:00 10985
2021-06-14 22:30:00 10986
2021-06-14 22:45:00 10987
2021-06-14 23:00:00 10988
2021-06-14 23:15:00 10989
2021-06-14 23:30:00 10990
2021-06-14 23:45:00 10991
2021-06-15 00:00:00 10992
2021-06-15 19:00:00 11068
2021-06-15 19:15:00 11069
2021-06-15 19:30:00 11070
2021-06-15 19:45:00 11071
2021-06-15 20:00:00 11072
2021-06-15 20:15:00 11073
2021-06-15 20:30:00 11074
2021-06-15 20:45:00 11075
2021-06-15 21:00:00 11076
2021-06-15 21:15:00 11077
2021-06-15 21:30:00 11078
2021-06-15 21:45:00 11079
2021-06-15 22:00:00 11080

In [29]:
len(df_m15[df_m15.TotalSignal != 0])

3358

In [30]:
df_m15['pointpos'] = df_m15.apply(lambda row: Util.pointpos(row), axis=1)

In [20]:
start_date_chart = '2023-1-1 00:00'
end_date_chart = '2023-6-30 00:00'
dfpl = df_m15.loc[start_date_chart : end_date_chart]#.set_index("Gmt time")

# Create a plot with 2 rows
fig = make_subplots(rows=1, cols=1)

# Add candlestick plot on the first row
fig.add_trace(go.Candlestick(x=dfpl.index,
                             open=dfpl['Open'],
                             high=dfpl['High'],
                             low=dfpl['Low'],
                             close=dfpl['Close']),
              row=1, col=1)

# Add markers for entry point m15
fig.add_trace(go.Scatter(x=dfpl.index, y=dfpl['pointpos'], mode="markers",
                         marker=dict(size=12, color="MediumPurple"),
                         name="entry"),
              row=1, col=1)

fig.update_layout(width=1500, height=800, sliders=[])
fig.show()

In [19]:
start_date_chart = '2023-1-1 00:00'
end_date_chart = '2023-12-30 00:00'
dfpl = df_h4.loc[start_date_chart : end_date_chart]#.set_index("Gmt time")

# Create a plot with 2 rows
fig = make_subplots(rows=1, cols=1)

# Add candlestick plot on the first row
fig.add_trace(go.Candlestick(x=dfpl.index,
                             open=dfpl['Open'],
                             high=dfpl['High'],
                             low=dfpl['Low'],
                             close=dfpl['Close']),
              row=1, col=1)

#Add markers for trade entry points on the same subplot
fig.add_trace(go.Scatter(x=dfpl.index, y=dfpl['support_point'], mode="markers",
                         marker=dict(size=8, color="green"),
                         name="support point"),
              row=1, col=1)

#Add markers for trade entry points on the same subplot
fig.add_trace(go.Scatter(x=dfpl.index, y=dfpl['resistant_point'], mode="markers",
                         marker=dict(size=8, color="red"),
                         name="resistant point"),
              row=1, col=1)

fig.update_layout(width=1200, height=800, sliders=[])
fig.show()

In [31]:
class KeyLevelChochStrat(Strategy):
    mysize = 0.5
    slcoef = 2
    TPcoef = 2
    risk_percent = 0.01
    last_swing_low = None
    last_swing_high = None
    previous_swing_low = None
    previous_swing_high = None
    entry_gap_multiplier = 0.8
    last_trade_index = 0
    dfopt = None

    stoploss_info_list = []
    valid_resistant_level = None
    valid_support_level = None

    setup_duration_gap = 60
    stoploss_window = 150
    
    def init(self):
        self.current_day = None
        self.order_placed_time = None
        self.setup_duration = None
        
        self.stoploss_info_list = []
        self.valid_resistant_level = None
        self.valid_support_level = None

        super().init()

    def reset_order(self):
        # delete placed order at the end of the day if not executed
        if self.order_placed_time:
            for order in self.orders:
                order_executed= False
                for trade in self.trades:
                    if trade.tag == order.tag:
                        order_executed = True

                if order_executed == False:
                    order.cancel()

        self.order_placed_time = None
        self.setup_duration = None
        self.valid_resistant_level = None
        self.valid_support_level = None

    def get_highest_high(self):
        return self.data.High[len(self.data.High) - self.stoploss_window : len(self.data.High)].max()

    def get_lowest_low(self):
        return self.data.Low[len(self.data.Low) - self.stoploss_window  : len(self.data.Low)].min()

    def is_entry_in_valid_short_zone(self, valid_resistant_list):
        return self.data.Close[-1] < max(valid_resistant_list) + self.data['ATR'][-1] * self.entry_gap_multiplier

    def is_entry_in_valid_long_zone(self, valid_support_list):
        return self.data.Close[-1] > min(valid_support_list) - self.data['ATR'][-1] * self.entry_gap_multiplier

    def add_stoploss_info_list(self, info):
        is_added = False
        for stoploss_info in self.stoploss_info_list:
            if stoploss_info[0] == info[0] and stoploss_info[1] == info[1]:
                is_added = True
                stoploss_info[2] = info[2]

        if is_added == False:
            self.stoploss_info_list.append(info)

    def get_stoploss_info(self, key_level_type, key_level_value):
        for stoploss_info in self.stoploss_info_list:
            if stoploss_info[0] == key_level_type and stoploss_info[1] == key_level_value:
                return stoploss_info
        return None

    def dynamic_stoploss(self):
        # delete placed order at the end of the day if not executed
        if self.order_placed_time:
            for order in self.orders:
                order_executed= False
                for trade in self.trades:
                    if trade.tag == order.tag:
                        order_executed = True
                        if order.stop is not None:
                            # in long trade, short order is for sl and inverse for short trade
                            # so we identify short order for long trade to identify sl
                            if order.is_short:
                                self.add_stoploss_info_list([Util.KeyLevel.SUPPORT, self.valid_support_level, order.stop])
                            else:
                                self.add_stoploss_info_list([Util.KeyLevel.RESISTANT, self.valid_resistant_level, order.stop])


                if order_executed == False:
                    order.cancel()
                    if order.is_short:
                        sl = abs(order.stop - self.get_highest_high())
                        tp = order.stop - self.TPcoef * sl
                        position_size = int((self.risk_percent * self.equity) / sl)
                        self.sell(sl = self.get_highest_high(), tp = tp, size=position_size, stop=order.stop)
                    else:
                        sl = abs(order.stop - self.get_lowest_low())
                        tp = order.stop + self.TPcoef * sl
                        position_size = int((self.risk_percent * self.equity) / sl)
                        order = self.buy(sl = self.get_lowest_low(), tp = tp, size=position_size, stop=order.stop)

    def get_tag(self):
        return f"{self.order_placed_time}"

    def wait_3_candles_before_new_trade(self):
        return self.last_trade_index + 3
    
    def next(self):
        super().next()
        index = len(self.data.index)

        # when an order is placed, it will be valable for 12h
        if self.setup_duration is not None and index >= self.setup_duration:
            self.reset_order()

        # place sl to the lowest/highest
        self.dynamic_stoploss()

        if len(self.trades) > 0:
            self.last_trade_index = index

        if len(self.orders)==0 and index >= self.wait_3_candles_before_new_trade():
            if self.data['TotalSignal'][-1]==1:
                valid_resistant_list = Util.get_valid_resistant_level(self.dfopt, index, breakout_candles_lookback)
                if len(valid_resistant_list) > 0:
                    valid_resistant_level = max(valid_resistant_list)
                    is_entry_in_valid_zone = self.is_entry_in_valid_short_zone(valid_resistant_list)
                    planned_entry_price = 0
                    sl = 0

                    if is_entry_in_valid_zone: 
                        planned_entry_price = self.data.Close[-1]
                        sl = abs(planned_entry_price - self.get_highest_high())
                    else :
                        planned_entry_price = valid_resistant_level + self.data['ATR'][-1] * self.entry_gap_multiplier
                        sl = abs(planned_entry_price - self.get_highest_high())
    
                    sl1 = planned_entry_price + sl
                    stoploss_info = self.get_stoploss_info(Util.KeyLevel.RESISTANT, valid_resistant_level)
                    if stoploss_info is None or sl1 > stoploss_info[2]:
                        tp = self.TPcoef * sl
                        position_size = int((self.risk_percent * self.equity) / sl)
                        tp1 = planned_entry_price - tp

                        self.valid_resistant_level = valid_resistant_level
                        self.setup_duration = len(self.data.index) + self.setup_duration_gap
                        self.order_placed_time = self.data.index[-1]

                        if is_entry_in_valid_zone: 
                            self.sell(sl=sl1, tp=tp1, size=position_size, tag=self.get_tag())
                            # print(f"short {self.data.index[-1]} sl = {sl1} & sgnal = {self.signal1[-1]} & valid_resistant_level = {valid_resistant_level} & entry_price = {planned_entry_price}")
                        else:
                            self.sell(sl=sl1, tp=tp1, size=position_size, stop=planned_entry_price, tag=self.get_tag())
                            # print(f"short {self.data.index[-1]} sl = {sl1} & sgnal = {self.signal1[-1]} & valid_resistant_level = {valid_resistant_level} & planned_entry_price = {planned_entry_price}")

            if self.data['TotalSignal'][-1]==2:
                valid_support_list = Util.get_valid_support_level(self.dfopt, index, breakout_candles_lookback)
                if len(valid_support_list) > 0:
                    valid_support_level = min(valid_support_list)
                    is_entry_in_valid_zone = self.is_entry_in_valid_long_zone(valid_support_list)
                    planned_entry_price = 0
                    sl = 0
                    
                    if is_entry_in_valid_zone: 
                        planned_entry_price = self.data.Close[-1]
                        sl = abs(planned_entry_price - self.get_lowest_low())
                    else :
                        planned_entry_price = valid_support_level - self.data['ATR'][-1] * self.entry_gap_multiplier
                        sl = abs(planned_entry_price - self.get_lowest_low())

                    sl1 = planned_entry_price - sl
                    stoploss_info = self.get_stoploss_info(Util.KeyLevel.SUPPORT, valid_support_level)
                    # print(f"{stoploss_info} {valid_support_level}")
                    if stoploss_info is None or sl1 < stoploss_info[2]:
                        tp = self.TPcoef * sl
                        position_size = int((self.risk_percent * self.equity) / sl)
                        tp1 = planned_entry_price + tp

                        self.valid_support_level = valid_support_level
                        self.setup_duration = len(self.data.index) + self.setup_duration_gap
                        self.order_placed_time = self.data.index[-1]

                        if is_entry_in_valid_zone: 
                            self.buy(sl=sl1, tp=tp1, size=position_size, tag=self.get_tag())
                            # print(f"long {self.data.index[-1]} sl = {sl1} & sgnal = {self.signal1[-1]} & valid_support_level = {valid_support_level} & entry_price = {planned_entry_price}")
                        else:
                            self.buy(sl=sl1, tp=tp1, size=position_size, stop=planned_entry_price, tag=self.get_tag())
                            # print(f"long {self.data.index[-1]} sl = {sl1} & sgnal = {self.signal1[-1]} & valid_support_level = {valid_support_level} & planned_entry_price = {planned_entry_price}")

In [33]:
start_date_chart = '2021-1-1 00:00'
end_date_chart = '2026-12-30 00:00'
global_dfopt = df_m15.loc[start_date_chart : end_date_chart]

bt = Backtest(global_dfopt, KeyLevelChochStrat, cash=10000, margin=0.005, finalize_trades=True) #0.0002
stats = bt.run(dfopt=global_dfopt)

print(stats)
bt.plot()

Start                     2021-01-03 23:00:00
End                       2026-09-16 00:00:00
Duration                   2081 days 01:00:00
Exposure Time [%]                     9.54743
Equity Final [$]                   14906.1541
Equity Peak [$]                    14906.1541
Return [%]                           49.06154
Buy & Hold Return [%]                48.17505
Return (Ann.) [%]                     6.46823
Volatility (Ann.) [%]                 5.01186
CAGR [%]                              7.25756
Sharpe Ratio                          1.29058
Sortino Ratio                          2.5352
Calmar Ratio                          1.07431
Alpha [%]                            47.53308
Beta                                  0.03173
Max. Drawdown [%]                    -6.02085
Avg. Drawdown [%]                    -0.37078
Max. Drawdown Duration      542 days 08:30:00
Avg. Drawdown Duration        4 days 21:53:00
# Trades                                   68
Win Rate [%]                         54.41176
Best Trade [%]                        2.92389
Worst Trade [%]                      -1.64002
Avg. Trade [%]                        0.32524
Max. Trade Duration          27 days 23:15:00
Avg. Trade Duration           2 days 22:14:00
Profit Factor                         2.49846
Expectancy [%]                        0.32898
SQN                                    3.1075
Kelly Criterion                       0.29888
_strategy                 KeyLevelChochStr...
_equity_curve                             ...
_trades                       Size  EntryB...
dtype: object

c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\_plotting.py:141: UserWarning: Data contains too many candlesticks to plot; downsampling to '8h'. See `Backtest.plot(resample=...)`
  warnings.warn(f"Data contains too many candlesticks to plot; downsampling to {freq!r}. "

GridPlot(id='p1545', ...)

In [40]:
# add some sl tp management

class RandomStrat(Strategy):
    mysize = 0.5
    slcoef = 2
    TPcoef = 2
    risk_percent = 0.01
    trades_list = None
    stoploss_window = 150

    def is_signal(self, date):
        for i in range(0, len(self.trades_list)):
            if self.trades_list[i] == date:
                return True
        return False

    def get_highest_high(self):
        return self.data.High[len(self.data.High) - self.stoploss_window : len(self.data.High)].max()
    
    def get_lowest_low(self):
        return self.data.Low[len(self.data.Low) - self.stoploss_window : len(self.data.Low)].min()
    
    def init(self):
        super().init()

    def next(self):
        super().next()
        if self.is_signal(self.data.index[-1]) and len(self.trades) == 0 and len(self.closed_trades) < 68:
            direction = randint(1,2)
            if direction == 1:
                planned_entry_price = self.data.Close[-1]
                sl = abs(planned_entry_price - self.get_lowest_low())
                if sl == 0:
                    sl = round(random.uniform(0.3,1), 1)
                tp = self.TPcoef * sl

                sl1 = planned_entry_price - sl
                tp1 = planned_entry_price + tp
                position_size = int((self.risk_percent * self.equity) / sl)
                # max_affordable_size = int((self.equity * 0.99) / planned_entry_price)
                # print(f'{position_size} {max_affordable_size}')

                self.buy(sl=sl1, tp=tp1, size=position_size)
            else:
                planned_entry_price = self.data.Close[-1]
                sl = abs(planned_entry_price - self.get_highest_high())
                if sl == 0:
                    sl = round(random.uniform(0.3,1), 1)
                tp = self.TPcoef * sl

                sl1 = planned_entry_price + sl
                tp1 = planned_entry_price - tp
                position_size = int((self.risk_percent * self.equity) / sl)
                # max_affordable_size = int((self.equity * 0.99) / planned_entry_price)
                # print(f'{position_size} {max_affordable_size}')

                self.sell(sl=sl1, tp=tp1, size=position_size)

In [57]:
trades_list = []
while len(trades_list) != 85:
    random_index = randint(0, len(df_m15))
    candle = df_m15.iloc[random_index]
    # exclu Saturday and Sunday
    if candle.name.weekday() < 5:
        if 9 <= candle.name.hour and candle.name.hour <= 19:
            trades_list.append(candle.name)
trades_list.sort()

bt = Backtest(df_m15, RandomStrat, cash=10000, margin=0.005, finalize_trades=True) #0.0002
stats = bt.run(trades_list=trades_list)

print(stats)

bt.plot()

Start                     2021-01-03 23:00:00
End                       2026-09-16 00:00:00
Duration                   2081 days 01:00:00
Exposure Time [%]                    10.38285
Equity Final [$]                    11018.183
Equity Peak [$]                     11472.187
Return [%]                           10.18183
Buy & Hold Return [%]                48.17505
Return (Ann.) [%]                     1.53404
Volatility (Ann.) [%]                 4.92753
CAGR [%]                              1.71637
Sharpe Ratio                          0.31132
Sortino Ratio                         0.52646
Calmar Ratio                          0.21219
Alpha [%]                            10.35212
Beta                                 -0.00353
Max. Drawdown [%]                    -7.22959
Avg. Drawdown [%]                    -0.51568
Max. Drawdown Duration      490 days 10:30:00
Avg. Drawdown Duration       20 days 07:25:00
# Trades                                   68
Win Rate [%]                         38.23529
Best Trade [%]                        2.82309
Worst Trade [%]                      -3.89824
Avg. Trade [%]                       -0.06567
Max. Trade Duration          16 days 15:15:00
Avg. Trade Duration           3 days 05:44:00
Profit Factor                         0.84655
Expectancy [%]                       -0.06064
SQN                                   0.79727
Kelly Criterion                       0.07125
_strategy                 RandomStrat(trad...
_equity_curve                             ...
_trades                       Size  EntryB...
dtype: object

c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\_plotting.py:141: UserWarning: Data contains too many candlesticks to plot; downsampling to '8h'. See `Backtest.plot(resample=...)`
  warnings.warn(f"Data contains too many candlesticks to plot; downsampling to {freq!r}. "

GridPlot(id='p7793', ...)

In [59]:
i = 0
expectancy_list = []
winrate_list = []
number_trades = []

while len(expectancy_list) < 1000:
    trades_list = []
    while len(trades_list) != 85:
        random_index = randint(0, len(df_m15)-1)
        candle = df_m15.iloc[random_index -1]
        # exclu Saturday and Sunday
        if candle.name.weekday() < 5:
            if 9 <= candle.name.hour and candle.name.hour <= 19:
                trades_list.append(candle.name)
    trades_list.sort()

    bt = Backtest(df_m15, RandomStrat, cash=10000, margin=0.0009, finalize_trades=True) #0.0002
    stats = bt.run(trades_list=trades_list)
    if stats['# Trades'] == 68:
        expectancy_list.append(stats['Expectancy [%]'])
        winrate_list.append(stats['Win Rate [%]'])
        number_trades.append(stats['# Trades'])
        print(f'{i} {len(expectancy_list)} {stats['Expectancy [%]']} Done')
    i += 1

print(expectancy_list)

1 1 0.1338511744532744 Done
2 2 -0.027928070341676867 Done
3 3 -0.06421879441695938 Done
4 4 -0.31374650108007845 Done
6 5 -0.14118677160772836 Done
7 6 -0.1672963351495313 Done
8 7 -0.04180133916797766 Done
9 8 0.017526245190933303 Done
10 9 0.09508020974072186 Done
11 10 -0.1567160104736083 Done
13 11 0.05273608493646778 Done
15 12 0.019846029142899367 Done
16 13 -0.0024988751630584866 Done
18 14 0.15380798201866125 Done
20 15 0.0013815197455534305 Done
21 16 -0.1397611250291462 Done
22 17 0.26851214083391706 Done
25 18 -0.004419943622208427 Done
26 19 0.2225647109612682 Done
29 20 -0.03589317865829738 Done
30 21 0.24748613659334043 Done
31 22 -0.12146117240192573 Done
34 23 -0.08691213637097915 Done
35 24 0.22434704413467815 Done
36 25 -0.1415496724398993 Done
38 26 -0.19929909719326472 Done
39 27 0.11121005483295777 Done
40 28 -0.09754298208199821 Done
43 29 0.006925741627377103 Done
44 30 0.13474609936346757 Done
45 31 0.09698091267414045 Done
47 32 -0.049832365328441174 Done
48 33 -0.10845267972676381 Done
50 34 0.10220434666743579 Done
52 35 0.1144289418288898 Done
53 36 0.10359841878080302 Done
54 37 -0.002169349370936824 Done
55 38 0.005339999451783872 Done
57 39 0.06517847973493777 Done
58 40 0.06929398839081478 Done
59 41 0.3040891392008499 Done
60 42 0.09792789477448957 Done
61 43 0.06845729426684802 Done
62 44 -0.033683345020390235 Done
63 45 0.059189798372151575 Done
64 46 -0.12731239982268314 Done
65 47 0.054257357355150575 Done
67 48 -0.062242209717955195 Done
70 49 0.17308319312012205 Done
71 50 -0.018810774776826668 Done
72 51 0.275629998311383 Done
74 52 0.03635844449177009 Done
75 53 0.06374334605265607 Done
76 54 -0.002383380584067938 Done
78 55 -0.020346853096879093 Done
79 56 0.1843585591308483 Done
80 57 0.04041422127870636 Done
81 58 0.01983279250357406 Done
82 59 0.006513482508803649 Done
83 60 -0.17817306141415196 Done
84 61 0.2759223096534356 Done
85 62 -0.06365834261977073 Done
86 63 0.16267736203619787 Done
87 64 -0.19387418476430704 Done
88 65 -0.11663091833641157 Done
89 66 0.10650331114428234 Done

c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\backtesting.py:1009: UserWarning: time=23829: Broker canceled the order due to insufficient margin (equity=9987.49, margin_available=9987.49).
  warnings.warn(

91 67 -0.18708311946503148 Done
92 68 0.28056631515031066 Done
93 69 0.01098611617581415 Done
94 70 0.23595513832975692 Done
97 71 0.01591967948126066 Done
98 72 0.03819899959483851 Done
99 73 0.14669545034820444 Done
100 74 -0.05487707762305283 Done
101 75 -0.01793472466748436 Done
102 76 -0.014961357080448481 Done
104 77 -0.045686261572412595 Done
105 78 0.19859117996748935 Done
106 79 -0.09687830619947532 Done
107 80 -0.161145846108919 Done
108 81 -0.14777134566321812 Done
111 82 -0.12785230088361527 Done
112 83 -0.056809407972697276 Done
116 84 0.11400643934069667 Done
117 85 0.1674283216813396 Done
119 86 -0.02750496900052158 Done
120 87 -0.09941370924903352 Done
123 88 0.3289502968762126 Done
124 89 -0.2582697407782755 Done
125 90 0.026708322364953317 Done
127 91 0.034722284958493346 Done
128 92 -0.24884666172515926 Done
129 93 0.00037966571491704023 Done
131 94 -0.05049174521737872 Done
132 95 -0.09411709651972744 Done
133 96 -0.032532825396592725 Done
135 97 0.0716390120053467 Done
136 98 0.06494901581892666 Done
137 99 -0.17347586978422902 Done
138 100 -0.1148160650335636 Done

c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\backtesting.py:1009: UserWarning: time=27040: Broker canceled the order due to insufficient margin (equity=10295.41, margin_available=10295.41).
  warnings.warn(

139 101 0.05845060813117427 Done
140 102 0.2122023067245553 Done
141 103 0.1270721381267192 Done
143 104 -0.29299316552203797 Done
144 105 -0.0170922334320029 Done
145 106 -0.04397500030527282 Done
147 107 -0.02492880917842398 Done
149 108 -0.06566489786491844 Done
153 109 0.28740280024288534 Done
155 110 0.127955874184884 Done
159 111 0.1733486324235181 Done
161 112 -0.017066111470572538 Done
162 113 0.09092047534737965 Done
163 114 0.08205844359984318 Done
165 115 0.12326326331064724 Done
166 116 0.09955107217595345 Done
167 117 0.14320734756316725 Done
169 118 -0.05824133249889514 Done
170 119 0.12751255466764128 Done
171 120 0.22893502913394675 Done
172 121 -0.11752226522213818 Done
173 122 0.04617940787928765 Done
174 123 -0.10435058743251989 Done
175 124 0.03368950199761486 Done
177 125 0.0831025050715484 Done
178 126 0.11350130242259954 Done
180 127 -0.13100473886347505 Done
181 128 0.12128265477490963 Done
182 129 -0.0900915532882425 Done
186 130 0.17341942434911922 Done
187 131 -0.20173023072683907 Done

c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\backtesting.py:1009: UserWarning: time=65673: Broker canceled the order due to insufficient margin (equity=10015.24, margin_available=10015.24).
  warnings.warn(

190 132 -0.119386588428194 Done
191 133 -0.1324870797229422 Done
192 134 -0.03914020540159142 Done
193 135 0.1849304144563555 Done

c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\backtesting.py:1009: UserWarning: time=94165: Broker canceled the order due to insufficient margin (equity=11415.06, margin_available=11415.06).
  warnings.warn(
c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\backtesting.py:1009: UserWarning: time=98231: Broker canceled the order due to insufficient margin (equity=11668.49, margin_available=11668.49).
  warnings.warn(

196 136 0.03614679334594659 Done
197 137 0.015417014134833259 Done
198 138 -0.09604914042350421 Done

c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\backtesting.py:1009: UserWarning: time=51390: Broker canceled the order due to insufficient margin (equity=10492.37, margin_available=10492.37).
  warnings.warn(

199 139 0.007841855203946646 Done
200 140 0.10018819569507281 Done

c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\backtesting.py:1009: UserWarning: time=35667: Broker canceled the order due to insufficient margin (equity=9883.93, margin_available=9883.93).
  warnings.warn(

201 141 0.14259395724813942 Done
202 142 0.07699965040422213 Done
204 143 0.06908715722557704 Done
205 144 -0.014920756326343022 Done
206 145 0.19904887040968552 Done
207 146 -0.05421143484848149 Done
208 147 0.1352851398321707 Done
209 148 -0.017036957575580606 Done
210 149 0.1580570826197532 Done
211 150 -0.2101037348800735 Done
214 151 0.04076944746505763 Done
215 152 -0.028802707185813663 Done
216 153 -0.16611211366335565 Done
217 154 0.11579513303000685 Done
218 155 -0.027852521316603224 Done
219 156 -0.03607669642429985 Done
221 157 0.10773001813154022 Done
222 158 -0.018952571242734997 Done

c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\backtesting.py:1009: UserWarning: time=63758: Broker canceled the order due to insufficient margin (equity=10186.79, margin_available=10186.79).
  warnings.warn(

223 159 0.0536924537865062 Done
224 160 -0.23511545717770413 Done
225 161 -0.20178723405368656 Done
226 162 0.0041303647597820846 Done
227 163 0.046295339280863816 Done
229 164 -0.16337589590242682 Done
230 165 -0.21065709462164015 Done
231 166 -0.14850648097860894 Done
232 167 -0.09151916767445835 Done
233 168 -0.08546461814631416 Done
234 169 -0.07211232080813021 Done
236 170 -0.10845860375189505 Done
237 171 0.14440533934785316 Done
238 172 -0.2061048013247129 Done
239 173 -0.0032603537627862497 Done
240 174 0.07022287489720257 Done
241 175 0.007826693481248726 Done
244 176 0.14615645352243828 Done
245 177 0.11907595603892125 Done
247 178 0.08107477839680005 Done
248 179 0.30272381609513754 Done
249 180 -0.14645764898047867 Done
250 181 -0.041130206289327294 Done
251 182 -0.014332553889820845 Done
252 183 0.053631353884186564 Done
253 184 0.10134223995745979 Done
255 185 -0.042441387716692994 Done
257 186 0.057757923430189616 Done
259 187 0.05286642929865082 Done
260 188 0.046210174936092537 Done
261 189 0.1023744235464094 Done
262 190 -0.24129995795113776 Done
263 191 0.15875012363364777 Done
264 192 0.1863816465039933 Done
266 193 -0.06029987462046471 Done
267 194 -0.22652370140764344 Done

c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\backtesting.py:1009: UserWarning: time=28587: Broker canceled the order due to insufficient margin (equity=11268.47, margin_available=11268.47).
  warnings.warn(

270 195 -0.17075813546872246 Done
271 196 -0.14650090129183665 Done
272 197 -0.03305942986324107 Done
275 198 0.10650994537070807 Done
276 199 -0.1501723407339932 Done
278 200 0.08161203698907996 Done
279 201 0.3763432761304558 Done
280 202 0.06849303856341524 Done
282 203 -0.08530445253468401 Done
283 204 0.015792310612609255 Done
284 205 0.008080422170150325 Done
285 206 -0.07255733381436395 Done
286 207 0.06815523080722544 Done
287 208 -0.12088462151797763 Done
289 209 0.28364376744897585 Done
291 210 0.16532261688625574 Done
292 211 0.1520356633779139 Done
294 212 -0.06887395442009836 Done
295 213 0.18888100799533583 Done
296 214 -0.018817628645927856 Done
297 215 0.023325336798677692 Done
298 216 -0.09117880441498291 Done
299 217 0.05576586187154972 Done
301 218 -0.07957757594000595 Done
302 219 0.16346123362374002 Done
304 220 0.15894698788639575 Done
305 221 0.13492553044593042 Done
306 222 0.05783645444326716 Done
307 223 0.1565588738623383 Done
310 224 -0.17591364110678048 Done
312 225 0.12061676748195106 Done
317 226 -0.06465069448866176 Done
318 227 0.012627764553932278 Done
319 228 0.16565858953941998 Done
320 229 -0.06789766503411415 Done
321 230 -0.1535075885539725 Done

c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\backtesting.py:1009: UserWarning: time=10290: Broker canceled the order due to insufficient margin (equity=10076.77, margin_available=10076.77).
  warnings.warn(

325 231 0.030884176863562825 Done
327 232 0.16304512888097084 Done
328 233 0.11862513105371836 Done
329 234 -0.14207034088351472 Done
330 235 -0.1447996039108488 Done
331 236 0.26505503639148426 Done
332 237 -0.021338285801578476 Done
333 238 -0.09511865908032732 Done
335 239 -0.07372937778507446 Done
336 240 0.1671455674624557 Done
337 241 0.0916427721457664 Done
338 242 -0.04880665884784223 Done
339 243 0.016978298525042113 Done
340 244 -0.2117374475044584 Done
342 245 -0.05172876090173842 Done
343 246 0.22115967667439757 Done
344 247 -0.05678771861353613 Done
345 248 -0.1071002936145918 Done
348 249 0.13176844715822883 Done
350 250 -0.06642098585911302 Done
351 251 0.070733065114813 Done
352 252 0.11804001767609748 Done

c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\backtesting.py:1009: UserWarning: time=98207: Broker canceled the order due to insufficient margin (equity=10354.90, margin_available=10354.90).
  warnings.warn(

353 253 -0.09456354655404707 Done
354 254 0.0017846249563566992 Done
355 255 0.19019736707605317 Done

c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\backtesting.py:1009: UserWarning: time=98207: Broker canceled the order due to insufficient margin (equity=10598.30, margin_available=10598.30).
  warnings.warn(

358 256 -0.02057374043577711 Done
359 257 0.11730902028985485 Done
360 258 -0.23666057674725616 Done
361 259 0.06800630133103874 Done
362 260 -0.09353206196368248 Done
363 261 0.046430578900333794 Done
364 262 -0.04121408923965623 Done

c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\backtesting.py:1009: UserWarning: time=52136: Broker canceled the order due to insufficient margin (equity=11250.85, margin_available=11250.85).
  warnings.warn(

365 263 -0.00032956296008350834 Done
366 264 0.12805690944698578 Done
367 265 0.036410124475090976 Done
368 266 0.18820497761162577 Done
369 267 0.11291074929955726 Done
372 268 0.07637827872718723 Done
375 269 0.05694602866026146 Done
376 270 -0.048478217314981045 Done
377 271 0.30939235640860346 Done
378 272 0.01201941505487009 Done
379 273 0.11059794852862838 Done
380 274 -0.10352812652091575 Done
381 275 0.020391097050336718 Done
382 276 -0.041343411951237884 Done

c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\backtesting.py:1009: UserWarning: time=9821: Broker canceled the order due to insufficient margin (equity=9707.92, margin_available=9707.92).
  warnings.warn(

385 277 -0.1543011089550272 Done
386 278 0.06021868375369153 Done
387 279 0.1909113454644629 Done
388 280 0.26694638353161537 Done
389 281 0.14638421723780917 Done
391 282 -0.04812789424749706 Done
392 283 0.20771922604932877 Done
393 284 -0.11273693442575446 Done
394 285 0.1080456685789787 Done
395 286 0.02254399942104742 Done
397 287 0.17770057131511718 Done
399 288 -0.1288968818801716 Done
402 289 -0.053337899467670154 Done
403 290 -0.18582090162676257 Done
404 291 0.10384390904572614 Done

c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\backtesting.py:1009: UserWarning: time=27040: Broker canceled the order due to insufficient margin (equity=10815.55, margin_available=10815.55).
  warnings.warn(

405 292 0.13378084892274128 Done
406 293 -0.14291945205947973 Done
407 294 0.05693836615505351 Done
408 295 0.15561940672028993 Done
409 296 0.1535990904495526 Done
411 297 0.007568925097724359 Done
412 298 -0.012035390052699399 Done
413 299 0.012002713381499797 Done
414 300 -0.03187886188252194 Done
415 301 -0.12070700209483406 Done
417 302 0.07913949182927352 Done
418 303 0.06589532405206798 Done
419 304 -0.04446051320761162 Done
420 305 0.21414035180090973 Done
421 306 0.06134056097820776 Done

c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\backtesting.py:1009: UserWarning: time=28587: Broker canceled the order due to insufficient margin (equity=10386.10, margin_available=10386.10).
  warnings.warn(

423 307 0.2847129505058915 Done
425 308 0.09924386675391977 Done
426 309 0.057270286336008454 Done
428 310 0.1073533062222633 Done
429 311 0.1050956644109235 Done
431 312 0.26201940785181943 Done
432 313 -0.2546333535750423 Done
433 314 -0.029021949599086445 Done
434 315 0.07644433193835819 Done
436 316 -0.052849164013129786 Done
437 317 0.2825364626399752 Done
439 318 0.041832983163500266 Done
440 319 0.32705396751663923 Done
441 320 -0.1539413169754267 Done
443 321 0.0965311858808413 Done
444 322 0.04214795276010437 Done
445 323 0.0848546594659298 Done
446 324 0.19000381878582331 Done
447 325 -0.08560957262717644 Done
448 326 -0.028764386598234222 Done
449 327 -0.03790350932335889 Done
450 328 -0.21861950085252557 Done
453 329 -0.031100527622637493 Done
454 330 0.1231618807994421 Done
457 331 -0.026845789104546425 Done
458 332 -0.018815467189279712 Done
459 333 -0.11836301625400673 Done
460 334 -0.037554133833815374 Done
462 335 0.22021145384206234 Done
464 336 -0.023340730845340253 Done
466 337 0.06909658703954674 Done
467 338 -0.04754174204702379 Done
468 339 -0.11223998472316926 Done
469 340 -0.1135157443126889 Done
472 341 -0.054371328557673175 Done
473 342 -0.12307263068548592 Done
476 343 0.11063402763784183 Done
477 344 -0.0759326210240284 Done
478 345 0.006942433216902525 Done
482 346 0.15900969779438812 Done
484 347 0.103169981166469 Done
485 348 0.2830160636868234 Done
486 349 -0.09755406113971178 Done
487 350 -0.09724018460053281 Done

c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\backtesting.py:1009: UserWarning: time=79072: Broker canceled the order due to insufficient margin (equity=10368.34, margin_available=10368.34).
  warnings.warn(

489 351 0.1342637895315909 Done
490 352 0.24325050111412674 Done
491 353 -0.1748857189613667 Done
492 354 -0.08857685932434013 Done
493 355 0.045674940499598096 Done
494 356 -0.026712952512706268 Done
495 357 0.3164419025344077 Done
497 358 -0.10702205991978506 Done
498 359 0.20006817149885872 Done
499 360 0.06807879214001503 Done
500 361 0.00522073312372731 Done
504 362 0.2299621798814152 Done
505 363 0.23312613473851757 Done
506 364 -0.041866034339796736 Done
508 365 -0.12515339678364296 Done
509 366 0.043566054063241905 Done
511 367 -0.07009087013014043 Done
512 368 0.14247209790504717 Done
513 369 0.2460039755517938 Done
514 370 -0.06339958448314384 Done
515 371 0.1962282333656289 Done
516 372 0.1066913633383608 Done
517 373 0.10087649765373709 Done
519 374 -0.1670868034407802 Done
520 375 -0.061589406827448 Done
524 376 -0.1002886685782312 Done
526 377 -0.1316033355577617 Done
527 378 -0.07649014229340416 Done
528 379 -0.18942830608870256 Done
530 380 0.06322435238131754 Done
531 381 -0.2080148762369761 Done
532 382 0.09366379391097034 Done
533 383 0.19836336860509915 Done
534 384 0.18424602043347796 Done
535 385 -0.10816133660169137 Done
537 386 0.17799201106132556 Done

c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\backtesting.py:1009: UserWarning: time=85285: Broker canceled the order due to insufficient margin (equity=10710.08, margin_available=10710.08).
  warnings.warn(

539 387 -0.08288341756308927 Done
541 388 -0.007681309104162432 Done
542 389 0.005046100180263648 Done
543 390 -0.13966266768203878 Done
544 391 0.18391770820022862 Done
545 392 0.1746730376426116 Done
546 393 -0.17299774845487983 Done
548 394 -0.07194615044129572 Done
550 395 0.1597917939603267 Done
551 396 0.05948598230650833 Done

c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\backtesting.py:1009: UserWarning: time=67628: Broker canceled the order due to insufficient margin (equity=9973.08, margin_available=9973.08).
  warnings.warn(

553 397 -0.024657581220404637 Done

c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\backtesting.py:1009: UserWarning: time=23923: Broker canceled the order due to insufficient margin (equity=9134.47, margin_available=9134.47).
  warnings.warn(

560 398 0.09518208952677491 Done
561 399 0.143633317419365 Done
562 400 0.2850913484505608 Done

c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\backtesting.py:1009: UserWarning: time=67525: Broker canceled the order due to insufficient margin (equity=10082.58, margin_available=10082.58).
  warnings.warn(

567 401 0.03024194537295113 Done
568 402 0.011257562307257756 Done
569 403 -0.04299971668089316 Done
570 404 0.10485677977267477 Done
573 405 -0.0640997641915014 Done
575 406 0.1729834192716448 Done
576 407 0.06390068936812279 Done
578 408 -0.21569757243351104 Done
581 409 0.3503432708023546 Done
584 410 -0.089049498090168 Done
586 411 -0.08435485931044426 Done
588 412 0.006843715216778127 Done
589 413 -0.0291380769213498 Done
590 414 0.11985268076193493 Done
591 415 -0.15903304899534038 Done
594 416 0.02167715070978339 Done
595 417 0.023016192201527456 Done
597 418 -0.12254045195698694 Done
598 419 0.12380108839025478 Done
600 420 0.007226300919740806 Done
601 421 -0.15533410871630224 Done
602 422 -0.10182865357582602 Done
603 423 -0.023804665452364274 Done
604 424 0.007961509356410275 Done
605 425 0.162920623641545 Done
606 426 0.1239302637545341 Done
607 427 0.02644874754881549 Done
608 428 0.039340490950143574 Done
614 429 0.15032175598359893 Done
615 430 -0.02614431591022119 Done
616 431 0.21600749729833316 Done

c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\backtesting.py:1009: UserWarning: time=85285: Broker canceled the order due to insufficient margin (equity=10889.59, margin_available=10889.59).
  warnings.warn(

621 432 0.03791405068263685 Done
623 433 -0.10092551720484146 Done
624 434 -0.041284288309939576 Done
625 435 -0.08120541381771461 Done
626 436 0.03774109711332078 Done
627 437 -0.07391959400827156 Done
628 438 0.32827416864637216 Done
629 439 -0.02566901245036335 Done

c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\backtesting.py:1009: UserWarning: time=90295: Broker canceled the order due to insufficient margin (equity=10454.77, margin_available=10454.77).
  warnings.warn(

630 440 0.12474094966721495 Done
631 441 -0.003218101673570963 Done
636 442 0.03804601085311816 Done
637 443 -0.10600625599273092 Done
641 444 -0.1671274460243904 Done
642 445 -0.04782263971734003 Done
643 446 0.022681910699627685 Done
644 447 -0.12698755014167418 Done
645 448 -0.02191266082758815 Done
646 449 -0.09015887851559458 Done
647 450 0.021622840044196522 Done
648 451 -0.01494367345587271 Done
650 452 0.006841118430749762 Done
652 453 0.1408765338290735 Done
653 454 0.13196659662559895 Done
654 455 -0.0881467919124014 Done
655 456 0.404475004907785 Done
656 457 -0.0370162953859048 Done
657 458 -0.043240474030638215 Done
658 459 0.0692134298333609 Done
659 460 -0.08655477946526322 Done
660 461 -0.07533554214792286 Done
661 462 0.10382203390720758 Done
662 463 0.1494057170191697 Done
663 464 -0.27199023825889374 Done
664 465 0.12819231924779406 Done
665 466 -0.06795601680231515 Done
666 467 -0.027886533091132683 Done
667 468 -0.04747942720265718 Done
669 469 0.1049124966962702 Done
670 470 -0.10250726709270601 Done
671 471 0.15754834508274915 Done
672 472 -0.1574206514243195 Done
673 473 -0.25154020520468 Done
674 474 -0.04075878311690471 Done
675 475 -0.02731728586142659 Done
676 476 0.16427889413113064 Done
678 477 -0.12064140359145854 Done
679 478 -0.10390414391509904 Done
680 479 -0.14121285898031272 Done
681 480 -0.15820523850206922 Done
682 481 -0.06775389739003497 Done
683 482 0.10220735542837946 Done
684 483 0.010754310798385304 Done
685 484 0.013303297561324567 Done
686 485 0.09128274243495392 Done
687 486 -0.05438676917537607 Done
688 487 -0.126472882389863 Done
689 488 0.010237897816807206 Done
690 489 0.06914226476844196 Done
691 490 0.06271728313690922 Done
693 491 0.28239563531030143 Done
694 492 0.06969527768604492 Done
695 493 0.09926120963639026 Done
696 494 -0.17559655693861004 Done
697 495 -0.10784564720664616 Done
698 496 0.1638306044243326 Done
699 497 -0.10582670630791546 Done
700 498 0.010039587350105893 Done
703 499 -0.02849588116992815 Done

c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\backtesting.py:1009: UserWarning: time=137617: Broker canceled the order due to insufficient margin (equity=10537.48, margin_available=10537.48).
  warnings.warn(

706 500 0.1440849032422988 Done
707 501 -0.016338134982810767 Done
708 502 0.011630972229503659 Done
709 503 -0.03663284960690085 Done
711 504 0.2136710553152234 Done
712 505 -0.10873876135155554 Done
713 506 0.1945277807313442 Done
714 507 0.16808462783125958 Done
715 508 -0.02729893390389795 Done
716 509 -0.04491363428877414 Done
717 510 0.151378545494962 Done
718 511 0.043077338766256086 Done
719 512 0.1123535967836586 Done
721 513 0.1107804536441161 Done
722 514 -0.0880863590036707 Done
723 515 -0.023467363304151688 Done
724 516 0.21207915529299134 Done
726 517 -0.09720442724574442 Done
727 518 0.10257326055667713 Done
728 519 -0.1081964112971925 Done
729 520 0.26559540783007185 Done
730 521 -0.1479751900200471 Done
731 522 0.16349409319534602 Done
732 523 0.021683006663188096 Done
734 524 -0.28041006400950313 Done

c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\backtesting.py:1009: UserWarning: time=72211: Broker canceled the order due to insufficient margin (equity=9207.01, margin_available=9207.01).
  warnings.warn(

735 525 -0.024939144215905033 Done
736 526 0.09768071503641977 Done
739 527 0.11000192687384786 Done
740 528 0.1552061767908815 Done

c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\backtesting.py:1009: UserWarning: time=27040: Broker canceled the order due to insufficient margin (equity=10487.50, margin_available=10487.50).
  warnings.warn(

741 529 0.15915351996562327 Done
742 530 0.24973724289577037 Done
743 531 0.03561202425615662 Done
744 532 -0.07217312492278802 Done
745 533 0.006690011196698843 Done
747 534 0.2572470145061234 Done
748 535 0.17955878848865142 Done
750 536 -0.18010299482733827 Done
751 537 -0.13208872016222672 Done
752 538 0.02722523676480907 Done
754 539 -0.058371204557883576 Done

c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\backtesting.py:1009: UserWarning: time=3299: Broker canceled the order due to insufficient margin (equity=9704.28, margin_available=9704.28).
  warnings.warn(

756 540 -0.19308766470242916 Done
757 541 0.02349138943806251 Done
758 542 0.09859011569531202 Done
762 543 0.15864834472545256 Done
763 544 0.04971758613004869 Done
764 545 0.2077224636824433 Done
765 546 0.20544325977811806 Done
766 547 -0.008538581268600175 Done
770 548 -0.02391534380299572 Done
771 549 0.2852273544168452 Done
772 550 -0.13953866073640825 Done
773 551 -0.07298693607917925 Done
775 552 -0.0421282893213459 Done
776 553 0.051865290803787385 Done
777 554 -0.06754422985823484 Done
778 555 -0.05842826180125052 Done
779 556 0.20862033127160154 Done
781 557 -0.09400459991359575 Done
782 558 0.018107524783884207 Done
783 559 0.1064488172132234 Done
785 560 0.09081195929255842 Done
787 561 0.18791970702236283 Done
788 562 -0.15300433175665373 Done
789 563 -0.0004750945161425693 Done
790 564 0.0352572811487376 Done
792 565 -0.04259310608628918 Done
793 566 0.14336869179263717 Done
794 567 0.16212167172897493 Done
795 568 -0.15808848230439335 Done
796 569 -0.03353259597630932 Done
797 570 -0.11552471976445262 Done
798 571 0.36748744948786344 Done
799 572 -0.11855873371185498 Done
800 573 0.15687431849649158 Done
801 574 0.23301758354485955 Done
802 575 -0.1217928952614406 Done
804 576 -0.1092525834171478 Done
805 577 -0.15974853332800276 Done
806 578 0.06938913130282573 Done
807 579 -0.07246076963979896 Done
808 580 -0.10383597246784253 Done
809 581 0.0642939568537633 Done
810 582 0.23818062195596623 Done
812 583 0.031245751279649774 Done
813 584 -0.051328666898930196 Done
814 585 -0.22160975241659545 Done
815 586 0.18424764663989993 Done
816 587 0.11866731554789214 Done
817 588 -0.11396403204220228 Done
821 589 0.022801997755372023 Done
822 590 0.11383430652176507 Done
823 591 0.05018889987781429 Done
824 592 -0.025831887895458316 Done
825 593 0.02971390435746947 Done
826 594 0.18921482323384609 Done
827 595 -0.19201789255593543 Done
829 596 0.11643296882525088 Done
830 597 0.02859810409989041 Done
831 598 -0.04149860650704339 Done
833 599 -0.04234026183005652 Done
834 600 0.08029597063553648 Done
838 601 0.20238356992674675 Done
840 602 -0.1272124519268323 Done
841 603 0.09994749570626532 Done
842 604 0.1966755206502039 Done
843 605 0.15978427065355993 Done
844 606 0.11263035075338695 Done
845 607 0.08449860772192525 Done
846 608 0.22856170980738266 Done
847 609 0.07933222564696722 Done
848 610 0.06506828915519243 Done
849 611 -0.04605337943374176 Done
850 612 -0.14585314453923764 Done
851 613 0.02153641411719456 Done
853 614 -0.026678034070579934 Done
854 615 -0.03434380023902202 Done
855 616 0.06605338980569939 Done
856 617 -0.04445279188736178 Done

c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\backtesting.py:1009: UserWarning: time=98207: Broker canceled the order due to insufficient margin (equity=9670.89, margin_available=9670.89).
  warnings.warn(

859 618 0.00674861546621056 Done
862 619 0.1063809975479309 Done
863 620 0.1901833095874746 Done
864 621 0.02611037876023227 Done
865 622 0.0748567875401115 Done
867 623 -0.13189818964888636 Done
868 624 -0.04469965728558087 Done
869 625 0.11621899161579957 Done
870 626 -0.03423393847642273 Done
871 627 -0.021516462837510818 Done
872 628 0.14071210422980504 Done
873 629 -0.024857582434114688 Done
874 630 -0.04526148588392382 Done
875 631 -0.16725791414275681 Done
876 632 0.02668526250145389 Done
877 633 0.23968683757136494 Done
879 634 0.2692866244099601 Done
880 635 -0.1039762015729045 Done
881 636 -0.07084584936073675 Done
882 637 0.17238752375239325 Done
885 638 0.23079463351525267 Done
886 639 0.10679944130724556 Done
887 640 0.10562108567336335 Done
890 641 -0.0662901427951826 Done
891 642 0.1296041673178424 Done
892 643 0.025293250793001487 Done
893 644 0.0677184210851822 Done
894 645 -0.058216891404534156 Done
895 646 0.1653544644544018 Done
896 647 0.21866384932547842 Done
898 648 -0.01779761036145806 Done
899 649 0.02039707810011145 Done

c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\backtesting.py:1009: UserWarning: time=70303: Broker canceled the order due to insufficient margin (equity=9682.00, margin_available=9682.00).
  warnings.warn(

900 650 0.010576115121891482 Done
901 651 -0.05796610865212601 Done
903 652 0.1355990183218695 Done
904 653 0.14197978595960337 Done
906 654 -0.0015421068766945508 Done
907 655 -0.05685239577357899 Done
908 656 0.06214264689446234 Done
909 657 -0.0517532794210033 Done
910 658 0.08555847025366048 Done
912 659 0.026328473129324088 Done
913 660 0.07733673157058082 Done
914 661 -0.04571463131583993 Done
916 662 -0.029220884447405573 Done
917 663 0.2535004521701087 Done
918 664 -0.03661151428026898 Done
919 665 -0.07678397466486667 Done
920 666 -0.023477290637022145 Done
921 667 0.17957660748584864 Done
922 668 0.02094831413743033 Done
923 669 0.04917868929331039 Done
924 670 0.12097821188926856 Done
925 671 -0.08243605859096112 Done
926 672 -0.3066480382540898 Done
927 673 0.11402988983835918 Done
928 674 0.0704416775064645 Done
929 675 0.05488891319208616 Done
932 676 0.03279443411393569 Done
933 677 0.0906868969750442 Done
935 678 -0.022567960168710523 Done
936 679 -0.13544168945433238 Done

c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\backtesting.py:1009: UserWarning: time=17576: Broker canceled the order due to insufficient margin (equity=9800.43, margin_available=9800.43).
  warnings.warn(

937 680 0.1333832958035692 Done
939 681 0.11163281651620897 Done
940 682 -0.09425542714016323 Done
941 683 -0.00892229815131207 Done
943 684 -0.060749753315856886 Done
944 685 0.01565183590209136 Done
945 686 0.10388210379800149 Done
946 687 0.15501157773191573 Done
947 688 -0.26753585875490915 Done
948 689 -0.02244930329803297 Done
949 690 0.18092835668493254 Done
950 691 0.05555294929128893 Done
951 692 -0.10268353803304783 Done
953 693 0.05912840156801034 Done
956 694 0.11727063620559183 Done
957 695 0.07120933445994684 Done
958 696 0.14557097002559866 Done
960 697 -0.11288481944137377 Done
961 698 -0.07827243302579054 Done
962 699 -0.029371239479730585 Done
964 700 -0.10274534323849432 Done
965 701 -0.09657530406733068 Done
966 702 -0.02376761055171232 Done
967 703 0.1306700151010528 Done
968 704 -0.018847230397647796 Done
970 705 0.09372557679465328 Done
971 706 -0.006479372924006303 Done
972 707 0.055065331247892896 Done
973 708 0.21535120330872531 Done
974 709 0.26225316941511595 Done
975 710 0.07386453924724812 Done
978 711 -0.010016787608787613 Done
979 712 0.16660677464876378 Done
980 713 0.1520743708316413 Done
981 714 0.11073658740286638 Done
983 715 -0.1180854867004931 Done
984 716 0.01710641481775619 Done
986 717 0.17163798051778034 Done
988 718 0.0033006908277487994 Done
989 719 0.1306678666360051 Done
990 720 0.14238064687581398 Done
991 721 0.06138393840121652 Done
992 722 0.044327214051193976 Done

c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\backtesting.py:1009: UserWarning: time=24203: Broker canceled the order due to insufficient margin (equity=10190.45, margin_available=10190.45).
  warnings.warn(

994 723 -0.13492185294364994 Done
995 724 0.26515577228611603 Done
996 725 0.1248239148832483 Done

c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\backtesting.py:1009: UserWarning: time=70303: Broker canceled the order due to insufficient margin (equity=11455.94, margin_available=11455.94).
  warnings.warn(

997 726 0.04396985429689572 Done
998 727 -0.2666434444034484 Done
999 728 0.2739595509313735 Done
1000 729 -0.022635430968861024 Done
1001 730 0.029567216465705932 Done
1002 731 0.22736953260144477 Done
1003 732 0.06656881872115036 Done
1005 733 -0.06665089343002453 Done
1006 734 -0.00675326266785106 Done
1007 735 0.046534151797567196 Done
1008 736 0.06045639666747966 Done

c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\backtesting.py:1009: UserWarning: time=67743: Broker canceled the order due to insufficient margin (equity=9969.48, margin_available=9969.48).
  warnings.warn(

1010 737 -0.029016061374705818 Done
1011 738 -0.12323397266629102 Done
1013 739 0.1527110873101279 Done
1014 740 -0.03835125976493655 Done
1015 741 0.1280301742009428 Done
1016 742 -0.09493016275533969 Done
1018 743 0.02920751075945292 Done
1019 744 -0.031880165730077355 Done
1020 745 -0.03598741216947836 Done
1021 746 0.038284881554964026 Done
1022 747 0.0884243987252734 Done
1023 748 0.06861073607475898 Done
1025 749 -0.1770334755501814 Done
1026 750 0.041476065114404645 Done
1028 751 -0.09201839722452722 Done
1029 752 -0.11744555628421134 Done
1030 753 0.267130550501982 Done
1032 754 0.24629405822351652 Done
1035 755 -0.15266741447245372 Done
1037 756 -0.06659678952236657 Done
1038 757 -0.040721741610719016 Done
1039 758 -0.1299996483852854 Done
1041 759 -0.06489339819480085 Done

c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\backtesting.py:1009: UserWarning: time=9821: Broker canceled the order due to insufficient margin (equity=9994.05, margin_available=9994.05).
  warnings.warn(

1043 760 0.14085761520666498 Done
1044 761 0.05208588868621979 Done
1045 762 -0.054094126900922565 Done
1047 763 -0.06232888155457923 Done

c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\backtesting.py:1009: UserWarning: time=9256: Broker canceled the order due to insufficient margin (equity=9895.22, margin_available=9895.22).
  warnings.warn(

1048 764 -0.11291864581138224 Done
1049 765 -0.1863306067404733 Done
1050 766 -0.027399669977111542 Done
1051 767 -0.021687754072390285 Done
1052 768 0.027351256510545614 Done

c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\backtesting.py:1009: UserWarning: time=94165: Broker canceled the order due to insufficient margin (equity=11431.55, margin_available=11431.55).
  warnings.warn(

1053 769 0.2661348986500353 Done
1054 770 0.014550344379715205 Done
1055 771 0.1832884869138869 Done
1056 772 0.17992516667598746 Done
1057 773 0.020139496806016812 Done
1060 774 0.3395190006659993 Done

c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\backtesting.py:1009: UserWarning: time=15032: Broker canceled the order due to insufficient margin (equity=9993.52, margin_available=9993.52).
  warnings.warn(

1061 775 0.0559774434075651 Done
1062 776 0.17357059668913816 Done
1063 777 -0.2159151940707611 Done
1064 778 0.29046463595948385 Done
1065 779 -0.0948912046900576 Done
1066 780 0.05507200398705232 Done
1067 781 -0.17629201862663418 Done
1068 782 -0.14366355629305402 Done
1070 783 -0.25614873603629873 Done
1072 784 0.09316319288138084 Done
1074 785 0.07928872839713924 Done
1075 786 0.01952965407834785 Done
1077 787 -0.008408895199960183 Done
1078 788 0.03269023327924911 Done
1079 789 0.1322306878914688 Done
1080 790 -0.057925108070070876 Done
1081 791 -0.08452882507603042 Done
1082 792 0.11705618870056272 Done
1085 793 -0.02341621315771562 Done
1086 794 -0.1526827209923177 Done
1088 795 0.14917908890151696 Done
1089 796 -0.09339245629262735 Done
1090 797 0.14347396267079685 Done
1091 798 -0.2572270033189347 Done
1092 799 -0.2426828483502369 Done
1093 800 0.18546875838355145 Done
1094 801 0.12015199262906738 Done
1095 802 -0.10535865160178186 Done
1096 803 0.01757498826304095 Done
1099 804 0.017293626333977907 Done
1101 805 -0.01725950957512134 Done
1103 806 -0.003174640086036857 Done
1105 807 -0.010447098502325117 Done
1107 808 -0.011516599486040035 Done
1108 809 0.15616907741745786 Done

c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\backtesting.py:1009: UserWarning: time=24412: Broker canceled the order due to insufficient margin (equity=9700.67, margin_available=9700.67).
  warnings.warn(

1110 810 0.019986194610879967 Done
1111 811 0.13317430004015918 Done
1112 812 0.20103220113703957 Done
1113 813 0.05574030390049271 Done
1114 814 -0.20042867376120652 Done
1115 815 -0.008127710560274764 Done
1117 816 -0.20523774811084627 Done
1118 817 0.4929891563669567 Done
1119 818 -0.22943450255142164 Done
1120 819 0.155498793039937 Done
1121 820 0.07245657936797466 Done
1124 821 0.1080245902855213 Done
1126 822 0.09268746149043275 Done
1127 823 0.0179820347218653 Done
1128 824 -0.10742405189975157 Done
1129 825 -0.031117891925250437 Done
1132 826 0.020301067837631935 Done
1133 827 -0.17870731226127715 Done
1134 828 -0.03196155878893485 Done
1136 829 0.0757153072872777 Done
1137 830 -0.03515760347737416 Done

c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\backtesting.py:1009: UserWarning: time=23923: Broker canceled the order due to insufficient margin (equity=10813.64, margin_available=10813.64).
  warnings.warn(

1138 831 0.03767459128606811 Done
1139 832 -0.049561095214041645 Done
1140 833 -0.04309314797408961 Done
1141 834 0.019809973037054243 Done
1142 835 0.025323236083082793 Done
1143 836 -0.08058694765030755 Done
1144 837 -0.09347111946378123 Done
1146 838 0.2449443594119997 Done
1148 839 -0.11392271090991636 Done
1149 840 0.003297062361034618 Done
1151 841 0.08392029792401494 Done
1152 842 -0.16336996613325996 Done
1153 843 -0.044829871966841205 Done
1154 844 0.06367688512921299 Done
1155 845 0.02813856313975274 Done
1156 846 -0.013734613193431701 Done
1158 847 0.1078278144658866 Done
1159 848 0.18729245363294902 Done
1160 849 0.025825902236250815 Done
1161 850 0.12215973543453006 Done
1162 851 0.18684523946762616 Done
1163 852 -0.007596332510923443 Done
1164 853 0.04961422033284505 Done
1165 854 -0.06567434369728588 Done
1166 855 0.05313574558383624 Done
1167 856 0.02950591095606917 Done

c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\backtesting.py:1009: UserWarning: time=94165: Broker canceled the order due to insufficient margin (equity=11116.90, margin_available=11116.90).
  warnings.warn(

1170 857 -0.019577603784809276 Done
1171 858 -0.07251299152784878 Done
1172 859 0.03088305460119678 Done
1173 860 -0.1301498853921248 Done
1174 861 -0.28608633472920086 Done
1176 862 0.19114719146442438 Done
1178 863 0.09948457473547394 Done
1179 864 0.29328835369458267 Done

c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\backtesting.py:1009: UserWarning: time=39797: Broker canceled the order due to insufficient margin (equity=10581.40, margin_available=10581.40).
  warnings.warn(

1180 865 0.0627501030156935 Done
1182 866 -0.06992895445165201 Done
1183 867 0.10741806985378563 Done
1185 868 -0.07581584317157536 Done

c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\backtesting.py:1009: UserWarning: time=98207: Broker canceled the order due to insufficient margin (equity=8953.58, margin_available=8953.58).
  warnings.warn(

1187 869 0.02675149449248244 Done
1188 870 0.042463756050623844 Done
1189 871 -0.045229407412491554 Done
1190 872 0.12763458687823245 Done
1191 873 0.044950710802589965 Done
1192 874 0.13834583305457943 Done
1193 875 0.26305946176305567 Done
1195 876 -0.13712558573304265 Done
1196 877 -0.06193594718773435 Done
1197 878 -0.04494209529006842 Done
1199 879 0.06447905032798015 Done
1201 880 -0.08538032751707532 Done

c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\backtesting.py:1009: UserWarning: time=79072: Broker canceled the order due to insufficient margin (equity=11020.98, margin_available=11020.98).
  warnings.warn(

1202 881 0.1779930478829786 Done
1203 882 0.27836873679438734 Done
1207 883 -0.17017418418686353 Done
1208 884 -0.09944483698461658 Done
1209 885 0.04844037465530915 Done
1213 886 0.08430251849408034 Done
1214 887 0.01980916053714996 Done
1215 888 0.11610738007745212 Done

c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\backtesting.py:1009: UserWarning: time=137617: Broker canceled the order due to insufficient margin (equity=9176.42, margin_available=9176.42).
  warnings.warn(

1216 889 -0.06296620915742512 Done
1218 890 0.08944551717550545 Done
1219 891 0.0386951269849324 Done
1221 892 -0.0960528890489992 Done
1222 893 -0.028312500785193487 Done

c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\backtesting.py:1009: UserWarning: time=67743: Broker canceled the order due to insufficient margin (equity=9217.10, margin_available=9217.10).
  warnings.warn(

1223 894 -0.15551608571292874 Done
1224 895 0.08151838064068664 Done
1226 896 -0.07227994542022831 Done
1228 897 -0.1826807826068518 Done
1231 898 -0.1487681482459883 Done
1232 899 -0.25390121571405966 Done
1233 900 -0.03734095220750493 Done
1234 901 -0.1933241020221704 Done
1236 902 0.23637011114337517 Done
1237 903 -0.006266091448578154 Done
1238 904 -0.03452717371538771 Done
1239 905 0.12246587805650924 Done
1240 906 0.1351325534067757 Done
1241 907 0.12099685801825498 Done
1243 908 0.15473513777708822 Done
1244 909 -0.2507550842372024 Done
1245 910 -0.006734078650380559 Done
1246 911 -0.09478654817578121 Done
1248 912 0.028050109425406533 Done
1250 913 -0.09735048493789603 Done
1251 914 0.018123733604462424 Done
1252 915 -0.014557514421111273 Done
1253 916 0.09482742820461583 Done
1255 917 0.015605884966791913 Done
1256 918 -0.09053449733630575 Done
1257 919 0.22309931106400996 Done
1258 920 -0.03549654646405821 Done
1260 921 -0.10581066559296502 Done
1261 922 0.06949332182088976 Done
1262 923 0.13715248661025048 Done
1266 924 -0.09171129470982439 Done
1267 925 0.00754986014628883 Done
1269 926 -0.12809270142070084 Done

c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\backtesting.py:1009: UserWarning: time=9256: Broker canceled the order due to insufficient margin (equity=9795.55, margin_available=9795.55).
  warnings.warn(

1270 927 0.02874959320603541 Done
1272 928 -0.03041943532160033 Done

c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\backtesting.py:1009: UserWarning: time=43140: Broker canceled the order due to insufficient margin (equity=9598.52, margin_available=9598.52).
  warnings.warn(

1275 929 -0.10884375039854066 Done
1276 930 0.21575253639129943 Done
1277 931 -0.18431384500620865 Done
1278 932 -0.11318273767352821 Done
1279 933 -0.055485663292014833 Done
1280 934 -0.09091934243811536 Done

c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\backtesting.py:1009: UserWarning: time=37547: Broker canceled the order due to insufficient margin (equity=11598.52, margin_available=11598.52).
  warnings.warn(

1281 935 0.20848134732610307 Done
1282 936 -0.1864537417147592 Done
1283 937 -0.2031365453533579 Done
1284 938 -0.060814217525190714 Done
1285 939 0.24878103971839333 Done
1286 940 0.12648080700237366 Done
1287 941 0.4524815154915392 Done
1288 942 0.19311534110810719 Done
1289 943 -0.24457755797451325 Done
1290 944 -0.05542930134369409 Done
1291 945 0.12960720250501329 Done
1293 946 -0.017896045553609664 Done
1295 947 0.2926856208546395 Done
1296 948 -0.09985179156641141 Done
1297 949 0.03186723254456854 Done
1300 950 0.12034151053931666 Done
1301 951 -0.011038165036240371 Done
1302 952 0.1640117487728351 Done
1303 953 0.08434194499520761 Done
1304 954 0.14881602727076865 Done
1305 955 0.003326351432163663 Done
1307 956 0.09177471607120301 Done
1308 957 -0.13655458902564918 Done
1309 958 0.06553202722761314 Done
1310 959 0.010285579436758126 Done
1313 960 0.1289908908753688 Done
1314 961 0.09263188670040857 Done
1315 962 -0.22900969066000187 Done
1317 963 0.11063771755595748 Done
1318 964 0.02329427241460608 Done
1319 965 -0.1997898240560403 Done
1321 966 0.08781762233968485 Done
1323 967 0.19289085661798663 Done
1324 968 0.028775238415519194 Done
1325 969 -0.012705809462327996 Done
1327 970 0.05679084789186606 Done
1328 971 0.0277803629791516 Done
1330 972 -0.24099484600293367 Done
1332 973 -0.06074129809066843 Done
1333 974 -0.11824845195106454 Done
1334 975 0.09712941638863506 Done
1335 976 0.12332034314063972 Done
1337 977 -0.011296687139226257 Done
1339 978 -0.09879950506831764 Done
1340 979 0.1039930590675529 Done
1342 980 -0.06891347268830209 Done
1344 981 0.06575798239822676 Done
1345 982 -0.3102621097875353 Done
1346 983 -0.01144419307000769 Done

c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\backtesting.py:1009: UserWarning: time=104579: Broker canceled the order due to insufficient margin (equity=9651.30, margin_available=9651.30).
  warnings.warn(

1349 984 0.007270710295339936 Done
1350 985 -0.12535093347231127 Done
1352 986 -0.09135749584769566 Done
1353 987 0.0014194515263696143 Done
1355 988 0.3163481687403367 Done
1356 989 0.034569215530182405 Done
1358 990 0.09507446512611872 Done
1359 991 0.08001604059942667 Done
1360 992 -0.15238567700901304 Done
1361 993 0.09924907841860701 Done
1362 994 0.1936668415147819 Done
1363 995 -0.07989444255040952 Done
1364 996 -0.01998574309835799 Done
1366 997 0.07842327874614693 Done
1367 998 0.0029068905336532606 Done
1369 999 -0.03569162973856533 Done
1371 1000 -0.09511022829354408 Done

In [60]:
print(len(expectancy_list))

p95 = np.percentile(expectancy_list, 95)                  # ngưỡng phân vị 95
print(f"p95 = {p95}")
# max_expectancy = max(expectancy_list_2)
print(f"max = {max(expectancy_list)}")
mean_expectancy = np.mean(expectancy_list)
print(f"mean = {mean_expectancy}")
print(f"min = {min(expectancy_list)}")
print(f"gap = {0.32898 - mean_expectancy}")

df_result = pd.DataFrame({'expectancy' : expectancy_list})
rank = (df_result['expectancy'] <= 0.32898).mean() * 100 
print(f"rank = {rank}")
p_value = ((df_result['expectancy'] >= 0.32898).sum() + 1) / (len(df_result['expectancy']) + 1)
print(f"p_value = {p_value}")

print(len(winrate_list))

p95_winrate = np.percentile(winrate_list, 95)                  # ngưỡng phân vị 95
print(f"p95 = {p95_winrate}")
# max_expectancy = max(expectancy_list_2)
print(f"max = {max(winrate_list)}")
mean_winrate = np.mean(winrate_list)
print(f"mean = {mean_winrate}")
print(f"min = {min(winrate_list)}")
print(f"gap = {54.41176 - mean_winrate}")

1000
p95 = 0.24333519402902032
max = 0.4929891563669567
mean = 0.021174371872601447
min = -0.31374650108007845
gap = 0.30780562812739853
rank = 99.3
p_value = 0.007992007992007992
1000
p95 = 45.588235294117645
max = 54.41176470588235
mean = 35.05882352941176
min = 20.588235294117645
gap = 19.35293647058824