In [1]:
from ta.volatility import AverageTrueRange
from ta.momentum import RSIIndicator
from ta.trend import EMAIndicator, SMAIndicator

import pandas as pd
import plotly.graph_objects as go
from plotly.subplots import make_subplots
from datetime import datetime
import numpy as np

import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd

from backtesting import Strategy
from backtesting import Backtest


from datetime import timedelta
import Util
import importlib
importlib.reload(Util)

c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\_plotting.py:55: UserWarning: Jupyter Notebook detected. Setting Bokeh output to notebook. This may not work in Jupyter clients without JavaScript support, such as old IDEs. Reset with `backtesting.set_bokeh_output(notebook=False)`.
  warnings.warn('Jupyter Notebook detected. '

In [2]:
pair = 'GBPJPY'

df_d1_raw = pd.read_csv(f"../Trading Data/{pair}_D1.csv",sep=',', parse_dates=['Date'], index_col='Date')
df_h4_raw = pd.read_csv(f"../Trading Data/{pair}_H4.csv",sep=',', parse_dates=['Date'], index_col='Date')
df_m15_raw = pd.read_csv(f"../Trading Data/{pair}_M15.csv",sep=',', parse_dates=['Date'], index_col='Date')

print(df_d1_raw)
print(df_h4_raw)
print(df_m15_raw)

               Open     High      Low    Close  Tickvol
Date
2010-09-10  129.605  130.065  128.995  129.255   172229
2010-09-13  129.565  130.115  128.780  129.090   215859
2010-09-14  129.105  129.430  127.640  129.015   226170
2010-09-15  129.015  134.070  128.555  133.975   252317
2010-09-16  133.975  134.260  132.970  134.150   222443
...             ...      ...      ...      ...      ...
2026-09-18  208.323  211.276  208.233  210.095   364707
2026-09-21  210.296  210.762  209.676  210.321   243731
2026-09-22  210.321  210.892  209.513  210.080   333200
2026-09-23  210.080  210.176  209.422  209.564   273936
2026-09-24  209.566  210.105  208.768  209.848   199988

[4183 rows x 5 columns]
                        Open     High      Low    Close  Tickvol
Date
2010-09-10 04:00:00  129.605  129.630  128.995  129.385    25539
2010-09-10 08:00:00  129.380  129.985  129.275  129.785    44503
2010-09-10 12:00:00  129.785  130.065  129.425  129.570    54127
2010-09-10 16:00:00  129.580  129.770  129.120  129.135    39740
2010-09-10 20:00:00  129.130  129.335  129.120  129.255     8320
...                      ...      ...      ...      ...      ...
2026-09-23 20:00:00  209.580  209.701  209.431  209.564    16661
2026-09-24 00:00:00  209.566  209.638  208.768  209.072    51880
2026-09-24 04:00:00  209.072  209.859  209.019  209.838    38121
2026-09-24 08:00:00  209.840  210.067  209.417  209.996    62442
2026-09-24 12:00:00  209.997  210.105  209.846  209.848    47545

[25029 rows x 5 columns]
                        Open     High      Low    Close  Tickvol
Date
2020-08-19 16:15:00  139.383  139.441  139.350  139.420    13401
2020-08-19 16:30:00  139.420  139.504  139.397  139.493     2033
2020-08-19 16:45:00  139.495  139.495  139.427  139.441     1798
2020-08-19 17:00:00  139.441  139.441  139.324  139.329     2242
2020-08-19 17:15:00  139.331  139.352  139.272  139.272     2696
...                      ...      ...      ...      ...      ...
2026-09-24 18:45:00  209.996  210.001  209.932  209.961     2550
2026-09-24 19:00:00  209.961  209.998  209.888  209.938     4040
2026-09-24 19:15:00  209.939  209.960  209.918  209.954     3388
2026-09-24 19:30:00  209.953  209.959  209.902  209.931     3296
2026-09-24 19:45:00  209.932  209.954  209.914  209.945     3174

[150000 rows x 5 columns]

In [3]:
structure_d1_window = 2
structure_m15_window = 2

date_format = '%Y-%m-%d %H:%M'
# start_date = '2023-1-1 00:00'
# end_date = '2024-3-29 00:00'
start_date = datetime.strptime('2022-1-1 00:00', date_format)
end_date = datetime.strptime('2022-12-30 00:00', date_format)
# start_date = '2022-01-1 00:00'
# end_date = '2026-9-16 00:00'

timezone = "Europe/London"

# nombre de jours pour les high.low
define_key_level_window = 90

gap_look_ahead = 6

# nombre de candle au dessus/ en desous de key level après breakout
breakout_candles = 9

# nombre de jours à chercher key level
key_level_lookback_candle = 100

# vérifier si 30 candle dans ke passé pour valider un valid breakout,
# un valid breakout doit avoir {breakout_candles} candles au dessus du resistant level
breakout_candles_lookback = 30

start_trade_hour = 9
stop_trade_hour = 19

atr_multiplier = 0.7
min_touched = 3

In [ ]:
# process D1 data
df_d1 = df_d1_raw.loc[start_date - timedelta(days=30) : end_date]

df_d1 = Util.implement_market_structure_states_fixed_pivots(df_d1, n=structure_d1_window)
df_d1["state_changed"] = df_d1["market_state"] != df_d1[
    "market_state"
].shift(1)
for state in df_d1[df_d1["state_changed"]][["Close", "market_state"]].iterrows():
    print(state)
df_d1 = df_d1.loc[start_date : end_date]

(Timestamp('2021-12-02 00:00:00'), Close           150.524
market_state        NaN
Name: 2021-12-02 00:00:00, dtype: object)
(Timestamp('2021-12-03 00:00:00'), Close           149.229
market_state        NaN
Name: 2021-12-03 00:00:00, dtype: object)
(Timestamp('2021-12-06 00:00:00'), Close           150.45
market_state       NaN
Name: 2021-12-06 00:00:00, dtype: object)
(Timestamp('2021-12-07 00:00:00'), Close           150.367
market_state        NaN
Name: 2021-12-07 00:00:00, dtype: object)
(Timestamp('2021-12-08 00:00:00'), Close           150.175
market_state        NaN
Name: 2021-12-08 00:00:00, dtype: object)
(Timestamp('2021-12-09 00:00:00'), Close           149.973
market_state        NaN
Name: 2021-12-09 00:00:00, dtype: object)
(Timestamp('2021-12-10 00:00:00'), Close           150.445
market_state        NaN
Name: 2021-12-10 00:00:00, dtype: object)
(Timestamp('2021-12-13 00:00:00'), Close           150.056
market_state        NaN
Name: 2021-12-13 00:00:00, dtype: object)
(Timestamp('2021-12-14 00:00:00'), Close           150.444
market_state        NaN
Name: 2021-12-14 00:00:00, dtype: object)
(Timestamp('2021-12-15 00:00:00'), Close           151.204
market_state        NaN
Name: 2021-12-15 00:00:00, dtype: object)
(Timestamp('2021-12-16 00:00:00'), Close           151.486
market_state        NaN
Name: 2021-12-16 00:00:00, dtype: object)
(Timestamp('2021-12-17 00:00:00'), Close           150.474
market_state        NaN
Name: 2021-12-17 00:00:00, dtype: object)
(Timestamp('2021-12-20 00:00:00'), Close           150.046
market_state        NaN
Name: 2021-12-20 00:00:00, dtype: object)
(Timestamp('2021-12-21 00:00:00'), Close           151.331
market_state        NaN
Name: 2021-12-21 00:00:00, dtype: object)
(Timestamp('2021-12-22 00:00:00'), Close           152.286
market_state        NaN
Name: 2021-12-22 00:00:00, dtype: object)
(Timestamp('2021-12-23 00:00:00'), Close           153.391
market_state        NaN
Name: 2021-12-23 00:00:00, dtype: object)
(Timestamp('2021-12-24 00:00:00'), Close           153.182
market_state        NaN
Name: 2021-12-24 00:00:00, dtype: object)
(Timestamp('2021-12-27 00:00:00'), Close           154.378
market_state        NaN
Name: 2021-12-27 00:00:00, dtype: object)
(Timestamp('2021-12-28 00:00:00'), Close           154.205
market_state        NaN
Name: 2021-12-28 00:00:00, dtype: object)
(Timestamp('2021-12-29 00:00:00'), Close           155.02
market_state       NaN
Name: 2021-12-29 00:00:00, dtype: object)
(Timestamp('2021-12-30 00:00:00'), Close           155.284
market_state        NaN
Name: 2021-12-30 00:00:00, dtype: object)
(Timestamp('2021-12-31 00:00:00'), Close           155.543
market_state        NaN
Name: 2021-12-31 00:00:00, dtype: object)
(Timestamp('2022-01-03 00:00:00'), Close           155.336
market_state        NaN
Name: 2022-01-03 00:00:00, dtype: object)
(Timestamp('2022-01-04 00:00:00'), Close           157.065
market_state        NaN
Name: 2022-01-04 00:00:00, dtype: object)
(Timestamp('2022-01-05 00:00:00'), Close           157.336
market_state        NaN
Name: 2022-01-05 00:00:00, dtype: object)
(Timestamp('2022-01-06 00:00:00'), Close           156.763
market_state        NaN
Name: 2022-01-06 00:00:00, dtype: object)
(Timestamp('2022-01-07 00:00:00'), Close           157.004
market_state        NaN
Name: 2022-01-07 00:00:00, dtype: object)
(Timestamp('2022-01-10 00:00:00'), Close           156.43
market_state       NaN
Name: 2022-01-10 00:00:00, dtype: object)
(Timestamp('2022-01-11 00:00:00'), Close           157.194
market_state        NaN
Name: 2022-01-11 00:00:00, dtype: object)
(Timestamp('2022-01-12 00:00:00'), Close           157.155
market_state        NaN
Name: 2022-01-12 00:00:00, dtype: object)
(Timestamp('2022-01-13 00:00:00'), Close           156.517
market_state        NaN
Name: 2022-01-13 00:00:00, dtype: object)
(Timestamp('2022-01-14 00:00:00'), Close           156.116
market_state        NaN
Name: 2022-01-14 00:00:00, dtype: object)
(Timestamp('2022-01-17 00:00:00'), Close           156.336
market_state        NaN
Name: 2022-01-17 00:00:00, dtype: object)
(Timestamp('2022-01-18 00:00:00'), Close           155.827
market_state        NaN
Name: 2022-01-18 00:00:00, dtype: object)
(Timestamp('2022-01-19 00:00:00'), Close           155.653
market_state        NaN
Name: 2022-01-19 00:00:00, dtype: object)
(Timestamp('2022-01-20 00:00:00'), Close           155.173
market_state    BEARISH
Name: 2022-01-20 00:00:00, dtype: object)
(Timestamp('2022-02-10 00:00:00'), Close           157.341
market_state    BULLISH
Name: 2022-02-10 00:00:00, dtype: object)
(Timestamp('2022-02-24 00:00:00'), Close           154.481
market_state    BEARISH
Name: 2022-02-24 00:00:00, dtype: object)
(Timestamp('2022-03-16 00:00:00'), Close           156.048
market_state    BULLISH
Name: 2022-03-16 00:00:00, dtype: object)
(Timestamp('2022-05-11 00:00:00'), Close           159.087
market_state    BEARISH
Name: 2022-05-11 00:00:00, dtype: object)
(Timestamp('2022-05-30 00:00:00'), Close           161.394
market_state    BULLISH
Name: 2022-05-30 00:00:00, dtype: object)
(Timestamp('2022-07-01 00:00:00'), Close           163.526
market_state    BEARISH
Name: 2022-07-01 00:00:00, dtype: object)
(Timestamp('2022-07-18 00:00:00'), Close           165.186
market_state    BULLISH
Name: 2022-07-18 00:00:00, dtype: object)
(Timestamp('2022-07-29 00:00:00'), Close           162.226
market_state    BEARISH
Name: 2022-07-29 00:00:00, dtype: object)
(Timestamp('2022-09-06 00:00:00'), Close           164.999
market_state    BULLISH
Name: 2022-09-06 00:00:00, dtype: object)
(Timestamp('2022-09-21 00:00:00'), Close           162.648
market_state    BEARISH
Name: 2022-09-21 00:00:00, dtype: object)
(Timestamp('2022-10-13 00:00:00'), Close           166.814
market_state    BULLISH
Name: 2022-10-13 00:00:00, dtype: object)
(Timestamp('2022-11-11 00:00:00'), Close           164.176
market_state    BEARISH
Name: 2022-11-11 00:00:00, dtype: object)
(Timestamp('2022-12-09 00:00:00'), Close           167.508
market_state    BULLISH
Name: 2022-12-09 00:00:00, dtype: object)
(Timestamp('2022-12-20 00:00:00'), Close           160.482
market_state    BEARISH
Name: 2022-12-20 00:00:00, dtype: object)

In [ ]:
# process h4 data
df_h4 = df_h4_raw.loc[start_date - timedelta(days=20) : end_date]
df_h4 = Util.implement_market_structure_states_fixed_pivots(df_h4, 5)
df_h4 = df_h4.loc[start_date : end_date]

h4_d1_direction_list = []
for i in range(len(df_d1)):
    row = df_d1.iloc[i]
    start_date_daily = row.name
    end_date_daily = start_date_daily + timedelta(hours=23, minutes=59)
    df_by_day = df_h4.loc[f'{start_date_daily}' : f'{end_date_daily}']

    for index2, row2 in df_by_day.iterrows():
        h4_d1_direction_list.append(df_d1.iloc[i-1]['market_state'])

df_h4['market_state_d1'] = h4_d1_direction_list

indicator_atr_14 = AverageTrueRange(df_h4['High'], df_h4['Low'], df_h4['Close'], window=14)
df_h4['ATR'] = indicator_atr_14._atr

df_h4

,Open,High,Low,Close,Tickvol,is_swing_high,is_swing_low,market_state,market_state_d1,ATR
Date,,,,,,,,,,
2022-01-03 00:00:00,155.676,155.916,155.642,155.668,16493,False,False,BULLISH,BEARISH,0.000000
2022-01-03 04:00:00,155.667,155.776,155.562,155.762,14930,False,False,BULLISH,BEARISH,0.000000
2022-01-03 08:00:00,155.765,155.868,155.482,155.484,20302,False,False,BULLISH,BEARISH,0.000000
2022-01-03 12:00:00,155.486,155.596,155.121,155.196,28248,False,False,BULLISH,BEARISH,0.000000
2022-01-03 16:00:00,155.199,155.459,154.883,155.381,24726,False,True,BULLISH,BEARISH,0.000000
...,...,...,...,...,...,...,...,...,...,...
2022-12-29 08:00:00,160.820,161.165,160.746,161.037,42059,False,False,BEARISH,BEARISH,0.610855
2022-12-29 12:00:00,161.040,161.051,160.134,160.209,63837,False,False,BEARISH,BEARISH,0.632723
2022-12-29 16:00:00,160.210,160.839,160.045,160.510,44256,False,False,BEARISH,BEARISH,0.644243
2022-12-29 20:00:00,160.508,160.571,160.104,160.273,24099,False,False,BEARISH,BEARISH,0.631582
2022-12-30 00:00:00,160.260,160.441,159.681,159.735,31513,False,False,BEARISH,BEARISH,0.640755

In [6]:
supports_list = Util.define_support_level_with_atr(df_h4, define_key_level_window, atr_multiplier=atr_multiplier, min_touched=min_touched)

supports_list

[[(Timestamp('2022-02-15 08:00:00'),
   Open               155.989
   High               156.824
   Low                155.962
   Close              156.701
   Tickvol              55067
   is_swing_high         True
   is_swing_low         False
   market_state       BEARISH
   market_state_d1    BULLISH
   ATR                0.53696
   Name: 2022-02-15 08:00:00, dtype: object),
  156.726],
 [(Timestamp('2022-02-16 08:00:00'),
   Open                156.731
   High                157.111
   Low                 156.688
   Close               156.971
   Tickvol               42609
   is_swing_high          True
   is_swing_low          False
   market_state        BULLISH
   market_state_d1     BULLISH
   ATR                0.465813
   Name: 2022-02-16 08:00:00, dtype: object),
  156.93],
 [(Timestamp('2022-02-23 08:00:00'),
   Open                156.387
   High                 156.77
   Low                 156.281
   Close               156.502
   Tickvol               42696
   is_swing_high          True
   is_swing_low          False
   market_state        BEARISH
   market_state_d1     BULLISH
   ATR                0.409336
   Name: 2022-02-23 08:00:00, dtype: object),
  156.737],
 [(Timestamp('2022-03-31 00:00:00'),
   Open                160.164
   High                160.873
   Low                 160.157
   Close               160.292
   Tickvol               61527
   is_swing_high          True
   is_swing_low          False
   market_state        BEARISH
   market_state_d1     BULLISH
   ATR                0.940839
   Name: 2022-03-31 00:00:00, dtype: object),
  161.152],
 [(Timestamp('2022-04-01 04:00:00'),
   Open                160.973
   High                161.181
   Low                 160.468
   Close               160.709
   Tickvol               39786
   is_swing_high          True
   is_swing_low          False
   market_state        BULLISH
   market_state_d1     BULLISH
   ATR                0.836543
   Name: 2022-04-01 04:00:00, dtype: object),
  161.16],
 [(Timestamp('2022-04-28 08:00:00'),
   Open                163.675
   High                164.246
   Low                  162.48
   Close               162.528
   Tickvol               94669
   is_swing_high          True
   is_swing_low          False
   market_state        BEARISH
   market_state_d1     BULLISH
   ATR                1.024866
   Name: 2022-04-28 08:00:00, dtype: object),
  164.311],
 [(Timestamp('2022-04-29 08:00:00'),
   Open                163.263
   High                163.983
   Low                 162.908
   Close               163.506
   Tickvol               72462
   is_swing_high          True
   is_swing_low          False
   market_state        BEARISH
   market_state_d1     BULLISH
   ATR                0.894836
   Name: 2022-04-29 08:00:00, dtype: object),
  164.023],
 [(Timestamp('2022-05-02 08:00:00'),
   Open                163.661
   High                163.823
   Low                 163.168
   Close               163.235
   Tickvol               62904
   is_swing_high          True
   is_swing_low          False
   market_state        BEARISH
   market_state_d1     BULLISH
   ATR                0.802011
   Name: 2022-05-02 08:00:00, dtype: object),
  163.973],
 [(Timestamp('2022-05-04 20:00:00'),
   Open                161.928
   High                163.567
   Low                 161.775
   Close               163.293
   Tickvol               56549
   is_swing_high          True
   is_swing_low          False
   market_state        BEARISH
   market_state_d1     BULLISH
   ATR                0.718895
   Name: 2022-05-04 20:00:00, dtype: object),
  163.695],
 [(Timestamp('2022-05-17 12:00:00'),
   Open               161.211
   High               161.846
   Low                160.802
   Close              161.215
   Tickvol              71522
   is_swing_high         True
   is_swing_low         False
   market_state       BEARISH
   market_state_d1    BEARISH
   ATR                0.96488
   Name: 2022-05-17 12:00:00, dtype: object),
  161.776],
 [(Timestamp('2022-05-26 00:00:00'),
   Open               160.147
   High               160.826
   Low                159.997
   Close              160.321
   Tickvol              41195
   is_swing_high         True
   is_swing_low         False
   market_state       BEARISH
   market_state_d1    BEARISH
   ATR                0.83533
   Name: 2022-05-26 00:00:00, dtype: object),
  161.044],
 [(Timestamp('2022-07-25 12:00:00'),
   Open                164.442
   High                165.085
   Low                 164.283
   Close               164.641
   Tickvol               90037
   is_swing_high          True
   is_swing_low          False
   market_state        BULLISH
   market_state_d1     BULLISH
   ATR                0.694496
   Name: 2022-07-25 12:00:00, dtype: object),
  165.181],
 [(Timestamp('2022-07-27 20:00:00'),
   Open                165.943
   High                 166.33
   Low                 165.823
   Close               165.868
   Tickvol               51385
   is_swing_high          True
   is_swing_low          False
   market_state        BULLISH
   market_state_d1     BULLISH
   ATR                0.614741
   Name: 2022-07-27 20:00:00, dtype: object),
  166.219],
 [(Timestamp('2022-08-09 12:00:00'),
   Open                  163.3
   High                163.663
   Low                 163.092
   Close               163.128
   Tickvol               76922
   is_swing_high          True
   is_swing_low          False
   market_state        BEARISH
   market_state_d1     BEARISH
   ATR                0.724145
   Name: 2022-08-09 12:00:00, dtype: object),
  163.809],
 [(Timestamp('2022-08-10 12:00:00'),
   Open                163.264
   High                 163.58
   Low                 161.671
   Close                161.94
   Tickvol              134184
   is_swing_high          True
   is_swing_low           True
   market_state        BEARISH
   market_state_d1     BEARISH
   ATR                0.679771
   Name: 2022-08-10 12:00:00, dtype: object),
  163.752],
 [(Timestamp('2022-08-17 12:00:00'),
   Open                163.332
   High                163.561
   Low                 162.781
   Close               163.146
   Tickvol               88084
   is_swing_high          True
   is_swing_low          False
   market_state        BULLISH
   market_state_d1     BEARISH
   ATR                0.629362
   Name: 2022-08-17 12:00:00, dtype: object),
  163.713],
 [(Timestamp('2022-08-26 12:00:00'),
   Open                162.023
   High                162.678
   Low                  161.64
   Close               161.882
   Tickvol              125618
   is_swing_high          True
   is_swing_low          False
   market_state        BULLISH
   market_state_d1     BEARISH
   ATR                0.560908
   Name: 2022-08-26 12:00:00, dtype: object),
  162.589],
 [(Timestamp('2022-08-29 16:00:00'),
   Open                162.197
   High                162.637
   Low                 162.121
   Close               162.437
   Tickvol               53676
   is_swing_high          True
   is_swing_low          False
   market_state        BULLISH
   market_state_d1     BEARISH
   ATR                0.549953
   Name: 2022-08-29 16:00:00, dtype: object),
  162.601],
 [(Timestamp('2022-09-02 08:00:00'),
   Open                 162.0
   High               162.485
   Low                161.925
   Close              162.298
   Tickvol              50347
   is_swing_high         True
   is_swing_low         False
   market_state       BEARISH
   market_state_d1    BEARISH
   ATR                0.47172
   Name: 2022-09-02 08:00:00, dtype: object),
  162.526],
 [(Timestamp('2022-10-21 12:00:00'),
   Open                168.326
   High                169.563
   Low                 166.858
   Close               167.566
   Tickvol              166383
   is_swing_high          True
   is_swing_low          False
   market_state        BULLISH
   market_state_d1     BULLISH
   ATR                0.994207
   Name: 2022-10-21 12:00:00, dtype: object),
  169.78],
 [(Timestamp('2022-11-25 08:00:00'),
   Open                167.813
   High                168.782
   Low                 167.704
   Close               168.695
   Tickvol               66737
   is_swing_high          True
   is_swing_low          False
   market_state        BULLISH
   market_state_d1     BEARISH
   ATR                0.616419
   Name: 2022-11-25 08:00:00, dtype: object),
  168.952],
 [(Timestamp('2022-11-30 16:00:00'),
   Open                167.208
   High                 167.39
   Low                 166.012
   Close               166.053
   Tickvol              121436
   is_swing_high          True
   is_swing_low          False
   market_state        BEARISH
   market_state_d1     BEARISH
   ATR                0.807858
   Name: 2022-11-30 16:00:00, dtype: object),
  167.381],
 [(Timestamp('2022-12-06 08:00:00'),
   Open               167.221
   High                167.48
   Low                166.247
   Close              166.344
   Tickvol              86600
   is_swing_high         True
   is_swing_low         False
   market_state       BEARISH
   market_state_d1    BEARISH
   ATR                0.80669
   Name: 2022-12-06 08:00:00, dtype: object),
  167.393],
 [(Timestamp('2022-12-07 08:00:00'),
   Open                166.727
   High                167.413
   Low                 166.618
   Close               167.322
   Tickvol               96877
   is_swing_high          True
   is_swing_low          False
   market_state        BEARISH
   market_state_d1     BEARISH
   ATR                0.762559
   Name: 2022-12-07 08:00:00, dtype: object),
  167.398],
 [(Timestamp('2022-12-15 12:00:00'),
   Open               168.663
   High               168.833
   Low                167.787
   Close              168.252
   Tickvol             102457
   is_swing_high         True
   is_swing_low         False
   market_state       BULLISH
   market_state_d1    BULLISH
   ATR                0.71012
   Name: 2022-12-15 12:00:00, dtype: object),
  168.961],
 [(Timestamp('2022-12-20 04:00:00'),
   Open                166.748
   High                167.009
   Low                 160.784
   Close               161.908
   Tickvol              124113
   is_swing_high          True
   is_swing_low          False
   market_state        BEARISH
   market_state_d1     BULLISH
   ATR                1.107088
   Name: 2022-12-20 04:00:00, dtype: object),
  167.323]]

In [7]:
df_h4['support_point'] = df_h4.apply(lambda row: Util.support_pos(supports_list, row), axis=1)
df_h4['is_support'] = df_h4.apply(lambda row: Util.is_support(supports_list, row), axis=1)

In [8]:
# df_h4['valid_breakout_support_levels'] = Util.is_candles_above_support_level_list(df_h4, breakout_candles, key_level_lookback_candle)
df_h4['valid_breakout_support_levels'] = Util.is_candles_above_support_level_list(df_h4, breakout_candles, key_level_lookback_candle)
df_h4['valid_breakout_support_levels']

Date
2022-01-03 00:00:00    [167.323, 168.961]
2022-01-03 04:00:00    [167.323, 168.961]
2022-01-03 08:00:00    [167.323, 168.961]
2022-01-03 12:00:00    [167.323, 168.961]
2022-01-03 16:00:00    [167.323, 168.961]
                              ...
2022-12-29 08:00:00                    []
2022-12-29 12:00:00                    []
2022-12-29 16:00:00                    []
2022-12-29 20:00:00                    []
2022-12-30 00:00:00                    []
Name: valid_breakout_support_levels, Length: 1555, dtype: object

In [ ]:
# process m15 data
df_m15 = df_m15_raw.loc[start_date - timedelta(hours=3): end_date]
df_m15 = Util.implement_market_structure_states_fixed_pivots(df_m15, n=structure_m15_window)

m15_daily_direction_list = []

m15_h4_resistant_level_list = []
m15_is_resistants_list = []
m15_is_below_resistant_list = []

m15_h4_support_level_list = []
m15_is_supports_list = []
m15_is_above_support_list = []

index_list = []

df_m15 = df_m15.loc[start_date : end_date]
for i in range(len(df_h4)):
    row = df_h4.iloc[i]
    start_date_h4 = row.name
    end_date_h4 = start_date_h4 + timedelta(hours=3, minutes=59)
    df_by_day = df_m15.loc[f'{start_date_h4}' : f'{end_date_h4}']

    for index2, row2 in df_by_day.iterrows():
        # affect current market states of H4 candle because the result is market state of previous D1 candle
        m15_daily_direction_list.append(df_h4.iloc[i]['market_state_d1'])

        m15_h4_support_level_list.append(df_h4.iloc[i]['support_point'])
        m15_is_supports_list.append(df_h4.iloc[i]['is_support'])
        m15_is_above_support_list.append(df_h4.iloc[i]['valid_breakout_support_levels'])

        # ajust to daylight saving time
        dst = pd.Timestamp(index2, tz=timezone).dst()
        if dst == timedelta(0):
            index2 = index2 - timedelta(hours=1)
            index_list.append(index2)
        else:
            index_list.append(index2)

df_m15['market_state_d1'] = m15_daily_direction_list

df_m15['support_point'] = m15_h4_support_level_list
df_m15['is_support'] = m15_is_supports_list
df_m15['valid_breakout_support_levels'] = m15_is_above_support_list

df_m15.index = index_list

df_m15

,Open,High,Low,Close,Tickvol,is_swing_high,is_swing_low,market_state,market_state_d1,support_point,is_support,valid_breakout_support_levels
2022-01-02 23:00:00,155.676,155.776,155.676,155.731,1032,True,False,NaN,BEARISH,NaN,False,"[167.323, 168.961]"
2022-01-02 23:15:00,155.731,155.754,155.707,155.715,412,False,False,NaN,BEARISH,NaN,False,"[167.323, 168.961]"
2022-01-02 23:30:00,155.715,155.731,155.672,155.680,577,False,False,NaN,BEARISH,NaN,False,"[167.323, 168.961]"
2022-01-02 23:45:00,155.680,155.704,155.669,155.688,351,False,False,NaN,BEARISH,NaN,False,"[167.323, 168.961]"
2022-01-03 00:00:00,155.684,155.710,155.664,155.674,517,False,True,NaN,BEARISH,NaN,False,"[167.323, 168.961]"
...,...,...,...,...,...,...,...,...,...,...,...,...
2022-12-29 22:00:00,160.236,160.299,160.231,160.236,109,False,False,BEARISH,BEARISH,NaN,False,[]
2022-12-29 22:15:00,160.238,160.298,160.104,160.140,78,False,True,BEARISH,BEARISH,NaN,False,[]
2022-12-29 22:30:00,160.141,160.322,160.141,160.283,3267,False,False,BEARISH,BEARISH,NaN,False,[]
2022-12-29 22:45:00,160.285,160.307,160.203,160.273,4788,False,False,BEARISH,BEARISH,NaN,False,[]
2022-12-29 23:00:00,160.260,160.353,160.190,160.335,2752,False,False,BEARISH,BEARISH,NaN,False,[]

In [10]:
print(Util.get_support_list(df_m15, 4193, key_level_lookback_candle, gap_look_ahead, Util.TimeFrame.M15))

support_point
156.726    156.726
156.737    156.737
156.930    156.930
Name: support_point, dtype: float64

In [11]:
# 2025-12-15 15:45:00 23438
print(Util.get_valid_breakout_support_level(df_m15, 4193, breakout_candles_lookback))

[]

In [12]:
def is_existed(list, value):
    for i in range(len(list)):
        if list[i] == value:
            return True
    return False

In [13]:
# using m15 market structure for entry
def apply_total_signal(df, key_level_lookback_candles = 120, gap=1, breakout_candles_lookback = 25, start_trade_hour=8, stop_trade_hour=19):
    # Initialize the 'TotalSignal' column
    df_signal_list = []
    valid_support_levels_list = []
    current_day = None

    # long variables
    is_key_level_touched = False
    is_above_support_levels = False

    high_tf_condition_long_satisfied = False
    # high_tf_condition_long_limit = 0
    # high_tf_condition_long_duration = 90
    high_tf_condition_long_candle = None
    m15_market_state_bullish = False

    # we want market structure to switch from bearish to bullish when htf conditions are met
    # if market structure is already bullish we need to wait
    previous_market_structure = None

    supports_levels_touched = []

    for i in range(0, len(df)):
        current_bar_date = df.index[i]
        signal = 0
        valid_support_levels = []

        if current_day != current_bar_date.date() or current_bar_date.time().hour >= stop_trade_hour:
            current_day = current_bar_date.date()
            # long
            is_key_level_touched = False
            valid_breakout_support_levels = []
            is_above_support_levels = False
            high_tf_condition_long_satisfied = False
            supports_levels_touched = []

        # if high_tf_condition_long_limit <= i:
        #     high_tf_condition_long_satisfied = False
        #     supports_levels_touched = []

        # h4 support level conditions
        supports_levels = Util.get_support_list(df, i, key_level_lookback_candles, gap, Util.TimeFrame.M15)
        for level in supports_levels:
            if df['Low'].iloc[i-1] < level:
                is_key_level_touched = True
                if not is_existed(supports_levels_touched, level):
                    supports_levels_touched.append(level)
        
        # long
        # d1 trending conditions
        c_long_daily_direction = df['market_state_d1'].iloc[i-1] == 'BULLISH'
        if c_long_daily_direction:
            c_m15_ms_bullish = df['market_state'].iloc[i] == 'BULLISH'

            # breakout_candles_above candle needs to be above support level for the breakout to be valid
            valid_breakout_support_levels = Util.get_valid_breakout_support_level(df, i, breakout_candles_lookback)

            for valid_level in valid_breakout_support_levels:
                for level_touched in supports_levels_touched:
                    if valid_level == level_touched:
                        valid_support_levels.append(valid_level)
                        is_above_support_levels = True

            # Combine conditions
            if (is_key_level_touched and
                not high_tf_condition_long_satisfied):
                high_tf_condition_long_satisfied = True
                # high_tf_condition_long_limit = i + high_tf_condition_long_duration
                m15_market_state_bullish = False
                high_tf_condition_long_candle = current_bar_date
                previous_market_structure = df['market_state'].iloc[i]
                print(f"high_tf_condition_long_satisfied {current_bar_date} {i}")

            if (high_tf_condition_long_satisfied and
                c_m15_ms_bullish and
                high_tf_condition_long_candle < current_bar_date and
                previous_market_structure == 'BEARISH'):
                m15_market_state_bullish = True
                print(f"m15_market_state_bullish {current_bar_date} {i}")

            # if i == 4193:
            #     print(supports_levels)
            #     print(supports_levels_touched)
            #     print(valid_breakout_support_levels)
            #     print(valid_support_levels)
            #     print(is_above_support_levels)

            c_time_trade = start_trade_hour <= current_bar_date.hour and current_bar_date.hour <= stop_trade_hour
            if c_time_trade:
                if (high_tf_condition_long_satisfied and
                    m15_market_state_bullish and
                    is_above_support_levels):
                    print(f"signal {current_bar_date} {i}")
                    signal = 2

        if previous_market_structure != df['market_state'].iloc[i]:
            if df['market_state'].iloc[i] == 'BEARISH':
                m15_market_state_bullish = False
            previous_market_structure = df['market_state'].iloc[i]    

        df_signal_list.append(signal)
        valid_support_levels_list.append(valid_support_levels)

    return df_signal_list, valid_support_levels_list

df_m15['TotalSignal'], df_m15['valid_support_levels'] = apply_total_signal(df=df_m15, key_level_lookback_candles=key_level_lookback_candle, gap=gap_look_ahead, 
                                                                           breakout_candles_lookback=breakout_candles_lookback, start_trade_hour=start_trade_hour, stop_trade_hour=stop_trade_hour)

high_tf_condition_long_satisfied 2022-02-15 08:45:00 2991
high_tf_condition_long_satisfied 2022-02-15 19:00:00 3032
high_tf_condition_long_satisfied 2022-02-15 19:15:00 3033
high_tf_condition_long_satisfied 2022-02-15 19:30:00 3034
high_tf_condition_long_satisfied 2022-02-15 19:45:00 3035
high_tf_condition_long_satisfied 2022-02-15 20:00:00 3036
high_tf_condition_long_satisfied 2022-02-15 20:15:00 3037
high_tf_condition_long_satisfied 2022-02-15 20:30:00 3038
high_tf_condition_long_satisfied 2022-02-15 20:45:00 3039
high_tf_condition_long_satisfied 2022-02-15 21:00:00 3040
high_tf_condition_long_satisfied 2022-02-15 21:15:00 3041
high_tf_condition_long_satisfied 2022-02-15 21:30:00 3042
high_tf_condition_long_satisfied 2022-02-15 21:45:00 3043
high_tf_condition_long_satisfied 2022-02-15 22:00:00 3044
high_tf_condition_long_satisfied 2022-02-15 22:15:00 3045
high_tf_condition_long_satisfied 2022-02-15 22:30:00 3046
high_tf_condition_long_satisfied 2022-02-15 22:45:00 3047
high_tf_condition_long_satisfied 2022-02-15 23:00:00 3048
high_tf_condition_long_satisfied 2022-02-15 23:15:00 3049
high_tf_condition_long_satisfied 2022-02-15 23:30:00 3050
high_tf_condition_long_satisfied 2022-02-15 23:45:00 3051
high_tf_condition_long_satisfied 2022-02-16 00:00:00 3052
m15_market_state_bullish 2022-02-16 18:15:00 3125
high_tf_condition_long_satisfied 2022-02-16 19:00:00 3128
high_tf_condition_long_satisfied 2022-02-16 19:15:00 3129
high_tf_condition_long_satisfied 2022-02-16 19:30:00 3130
high_tf_condition_long_satisfied 2022-02-16 19:45:00 3131
high_tf_condition_long_satisfied 2022-02-16 20:00:00 3132
high_tf_condition_long_satisfied 2022-02-16 20:15:00 3133
high_tf_condition_long_satisfied 2022-02-16 20:30:00 3134
high_tf_condition_long_satisfied 2022-02-16 20:45:00 3135
high_tf_condition_long_satisfied 2022-02-16 21:00:00 3136
high_tf_condition_long_satisfied 2022-02-16 21:15:00 3137
high_tf_condition_long_satisfied 2022-02-16 21:30:00 3138
high_tf_condition_long_satisfied 2022-02-16 21:45:00 3139
high_tf_condition_long_satisfied 2022-02-16 22:00:00 3140
high_tf_condition_long_satisfied 2022-02-16 22:15:00 3141
high_tf_condition_long_satisfied 2022-02-16 22:30:00 3142
high_tf_condition_long_satisfied 2022-02-16 22:45:00 3143
high_tf_condition_long_satisfied 2022-02-16 23:00:00 3144
high_tf_condition_long_satisfied 2022-02-16 23:15:00 3145
high_tf_condition_long_satisfied 2022-02-16 23:30:00 3146
high_tf_condition_long_satisfied 2022-02-16 23:45:00 3147
high_tf_condition_long_satisfied 2022-02-17 00:00:00 3148
m15_market_state_bullish 2022-02-17 01:15:00 3153
m15_market_state_bullish 2022-02-17 06:15:00 3173
high_tf_condition_long_satisfied 2022-02-17 19:00:00 3224
high_tf_condition_long_satisfied 2022-02-17 19:15:00 3225
high_tf_condition_long_satisfied 2022-02-17 19:30:00 3226
high_tf_condition_long_satisfied 2022-02-17 19:45:00 3227
high_tf_condition_long_satisfied 2022-02-17 20:00:00 3228
high_tf_condition_long_satisfied 2022-02-17 20:15:00 3229
high_tf_condition_long_satisfied 2022-02-17 20:30:00 3230
high_tf_condition_long_satisfied 2022-02-17 20:45:00 3231
high_tf_condition_long_satisfied 2022-02-17 21:00:00 3232
high_tf_condition_long_satisfied 2022-02-17 21:15:00 3233
high_tf_condition_long_satisfied 2022-02-17 21:30:00 3234
high_tf_condition_long_satisfied 2022-02-17 21:45:00 3235
high_tf_condition_long_satisfied 2022-02-17 22:00:00 3236
high_tf_condition_long_satisfied 2022-02-17 22:15:00 3237
high_tf_condition_long_satisfied 2022-02-17 22:30:00 3238
high_tf_condition_long_satisfied 2022-02-17 22:45:00 3239
high_tf_condition_long_satisfied 2022-02-17 23:00:00 3240
high_tf_condition_long_satisfied 2022-02-17 23:15:00 3241
high_tf_condition_long_satisfied 2022-02-17 23:30:00 3242
high_tf_condition_long_satisfied 2022-02-17 23:45:00 3243
high_tf_condition_long_satisfied 2022-02-18 00:00:00 3244
m15_market_state_bullish 2022-02-18 01:30:00 3250
m15_market_state_bullish 2022-02-18 18:45:00 3319
high_tf_condition_long_satisfied 2022-02-18 19:00:00 3320
high_tf_condition_long_satisfied 2022-02-18 19:15:00 3321
high_tf_condition_long_satisfied 2022-02-18 19:30:00 3322
high_tf_condition_long_satisfied 2022-02-18 19:45:00 3323
high_tf_condition_long_satisfied 2022-02-18 20:00:00 3324
high_tf_condition_long_satisfied 2022-02-18 20:15:00 3325
high_tf_condition_long_satisfied 2022-02-18 20:30:00 3326
high_tf_condition_long_satisfied 2022-02-18 20:45:00 3327
high_tf_condition_long_satisfied 2022-02-18 21:00:00 3328
high_tf_condition_long_satisfied 2022-02-18 21:15:00 3329
high_tf_condition_long_satisfied 2022-02-18 21:30:00 3330
high_tf_condition_long_satisfied 2022-02-18 21:45:00 3331
high_tf_condition_long_satisfied 2022-02-20 23:00:00 3332
high_tf_condition_long_satisfied 2022-02-20 23:15:00 3333
high_tf_condition_long_satisfied 2022-02-20 23:30:00 3334
high_tf_condition_long_satisfied 2022-02-20 23:45:00 3335
high_tf_condition_long_satisfied 2022-02-21 00:00:00 3336
m15_market_state_bullish 2022-02-21 00:45:00 3339
m15_market_state_bullish 2022-02-21 05:00:00 3356
high_tf_condition_long_satisfied 2022-02-21 19:00:00 3412
high_tf_condition_long_satisfied 2022-02-21 19:15:00 3413
high_tf_condition_long_satisfied 2022-02-21 19:30:00 3414
high_tf_condition_long_satisfied 2022-02-21 19:45:00 3415
high_tf_condition_long_satisfied 2022-02-21 20:00:00 3416
high_tf_condition_long_satisfied 2022-02-21 20:15:00 3417
high_tf_condition_long_satisfied 2022-02-21 20:30:00 3418
high_tf_condition_long_satisfied 2022-02-21 20:45:00 3419
high_tf_condition_long_satisfied 2022-02-21 21:00:00 3420
high_tf_condition_long_satisfied 2022-02-21 21:15:00 3421
high_tf_condition_long_satisfied 2022-02-21 21:30:00 3422
high_tf_condition_long_satisfied 2022-02-21 21:45:00 3423
high_tf_condition_long_satisfied 2022-02-21 22:00:00 3424
high_tf_condition_long_satisfied 2022-02-21 22:15:00 3425
high_tf_condition_long_satisfied 2022-02-21 22:30:00 3426
high_tf_condition_long_satisfied 2022-02-21 22:45:00 3427
high_tf_condition_long_satisfied 2022-02-21 23:00:00 3428
high_tf_condition_long_satisfied 2022-02-21 23:15:00 3429
high_tf_condition_long_satisfied 2022-02-21 23:30:00 3430
high_tf_condition_long_satisfied 2022-02-21 23:45:00 3431
high_tf_condition_long_satisfied 2022-02-22 00:00:00 3432
m15_market_state_bullish 2022-02-22 05:15:00 3453
m15_market_state_bullish 2022-02-22 10:15:00 3473
high_tf_condition_long_satisfied 2022-02-22 19:00:00 3508
high_tf_condition_long_satisfied 2022-02-22 19:15:00 3509
high_tf_condition_long_satisfied 2022-02-22 19:30:00 3510
high_tf_condition_long_satisfied 2022-02-22 19:45:00 3511
high_tf_condition_long_satisfied 2022-02-22 20:00:00 3512
high_tf_condition_long_satisfied 2022-02-22 20:15:00 3513
high_tf_condition_long_satisfied 2022-02-22 20:30:00 3514
high_tf_condition_long_satisfied 2022-02-22 20:45:00 3515
high_tf_condition_long_satisfied 2022-02-22 21:00:00 3516
high_tf_condition_long_satisfied 2022-02-22 21:15:00 3517
high_tf_condition_long_satisfied 2022-02-22 21:30:00 3518
high_tf_condition_long_satisfied 2022-02-22 21:45:00 3519
high_tf_condition_long_satisfied 2022-02-22 22:00:00 3520
high_tf_condition_long_satisfied 2022-02-22 22:15:00 3521
high_tf_condition_long_satisfied 2022-02-22 22:30:00 3522
high_tf_condition_long_satisfied 2022-02-22 22:45:00 3523
high_tf_condition_long_satisfied 2022-02-22 23:00:00 3524
high_tf_condition_long_satisfied 2022-02-22 23:15:00 3525
high_tf_condition_long_satisfied 2022-02-22 23:30:00 3526
high_tf_condition_long_satisfied 2022-02-22 23:45:00 3527
high_tf_condition_long_satisfied 2022-02-23 00:00:00 3528
m15_market_state_bullish 2022-02-23 07:30:00 3558
high_tf_condition_long_satisfied 2022-02-23 19:00:00 3604
high_tf_condition_long_satisfied 2022-02-23 19:15:00 3605
high_tf_condition_long_satisfied 2022-02-23 19:30:00 3606
high_tf_condition_long_satisfied 2022-02-23 19:45:00 3607
high_tf_condition_long_satisfied 2022-02-23 20:00:00 3608
high_tf_condition_long_satisfied 2022-02-23 20:15:00 3609
high_tf_condition_long_satisfied 2022-02-23 20:30:00 3610
high_tf_condition_long_satisfied 2022-02-23 20:45:00 3611
high_tf_condition_long_satisfied 2022-02-23 21:00:00 3612
high_tf_condition_long_satisfied 2022-02-23 21:15:00 3613
high_tf_condition_long_satisfied 2022-02-23 21:30:00 3614
high_tf_condition_long_satisfied 2022-02-23 21:45:00 3615
high_tf_condition_long_satisfied 2022-02-23 22:00:00 3616
high_tf_condition_long_satisfied 2022-02-23 22:15:00 3617
high_tf_condition_long_satisfied 2022-02-23 22:30:00 3618
high_tf_condition_long_satisfied 2022-02-23 22:45:00 3619
high_tf_condition_long_satisfied 2022-02-23 23:00:00 3620
high_tf_condition_long_satisfied 2022-02-23 23:15:00 3621
high_tf_condition_long_satisfied 2022-02-23 23:30:00 3622
high_tf_condition_long_satisfied 2022-02-23 23:45:00 3623
high_tf_condition_long_satisfied 2022-02-24 00:00:00 3624
m15_market_state_bullish 2022-02-24 01:45:00 3631
m15_market_state_bullish 2022-02-24 16:00:00 3688
high_tf_condition_long_satisfied 2022-02-24 19:00:00 3700
high_tf_condition_long_satisfied 2022-02-24 19:15:00 3701
high_tf_condition_long_satisfied 2022-02-24 19:30:00 3702
high_tf_condition_long_satisfied 2022-02-24 19:45:00 3703
high_tf_condition_long_satisfied 2022-02-24 20:00:00 3704
high_tf_condition_long_satisfied 2022-02-24 20:15:00 3705
high_tf_condition_long_satisfied 2022-02-24 20:30:00 3706
high_tf_condition_long_satisfied 2022-02-24 20:45:00 3707
high_tf_condition_long_satisfied 2022-02-24 21:00:00 3708
high_tf_condition_long_satisfied 2022-02-24 21:15:00 3709
high_tf_condition_long_satisfied 2022-02-24 21:30:00 3710
high_tf_condition_long_satisfied 2022-02-24 21:45:00 3711
high_tf_condition_long_satisfied 2022-02-24 22:00:00 3712
high_tf_condition_long_satisfied 2022-02-24 22:15:00 3713
high_tf_condition_long_satisfied 2022-02-24 22:30:00 3714
high_tf_condition_long_satisfied 2022-02-24 22:45:00 3715
high_tf_condition_long_satisfied 2022-02-24 23:00:00 3716
high_tf_condition_long_satisfied 2022-03-16 23:15:00 5049
high_tf_condition_long_satisfied 2022-03-16 23:30:00 5050
high_tf_condition_long_satisfied 2022-03-16 23:45:00 5051
high_tf_condition_long_satisfied 2022-03-17 00:00:00 5052
m15_market_state_bullish 2022-03-17 11:45:00 5099
m15_market_state_bullish 2022-03-17 15:30:00 5114
high_tf_condition_long_satisfied 2022-03-17 19:00:00 5128
high_tf_condition_long_satisfied 2022-03-17 19:15:00 5129
high_tf_condition_long_satisfied 2022-03-17 19:30:00 5130
high_tf_condition_long_satisfied 2022-03-17 19:45:00 5131
high_tf_condition_long_satisfied 2022-03-17 20:00:00 5132
high_tf_condition_long_satisfied 2022-03-17 20:15:00 5133
high_tf_condition_long_satisfied 2022-03-17 20:30:00 5134
high_tf_condition_long_satisfied 2022-03-17 20:45:00 5135
high_tf_condition_long_satisfied 2022-03-17 21:00:00 5136
high_tf_condition_long_satisfied 2022-03-17 21:15:00 5137
high_tf_condition_long_satisfied 2022-03-17 21:30:00 5138
high_tf_condition_long_satisfied 2022-03-17 21:45:00 5139
high_tf_condition_long_satisfied 2022-03-17 22:00:00 5140
high_tf_condition_long_satisfied 2022-03-17 22:15:00 5141
high_tf_condition_long_satisfied 2022-03-17 22:30:00 5142
high_tf_condition_long_satisfied 2022-03-17 22:45:00 5143
high_tf_condition_long_satisfied 2022-03-17 23:00:00 5144
high_tf_condition_long_satisfied 2022-03-17 23:15:00 5145
high_tf_condition_long_satisfied 2022-03-17 23:30:00 5146
high_tf_condition_long_satisfied 2022-03-17 23:45:00 5147
high_tf_condition_long_satisfied 2022-03-18 00:00:00 5148
m15_market_state_bullish 2022-03-18 05:45:00 5171
m15_market_state_bullish 2022-03-18 13:00:00 5200
high_tf_condition_long_satisfied 2022-03-31 01:45:00 5999
m15_market_state_bullish 2022-03-31 09:45:00 6031
high_tf_condition_long_satisfied 2022-03-31 19:00:00 6068
high_tf_condition_long_satisfied 2022-03-31 19:15:00 6069
high_tf_condition_long_satisfied 2022-03-31 19:30:00 6070
high_tf_condition_long_satisfied 2022-03-31 19:45:00 6071
high_tf_condition_long_satisfied 2022-03-31 20:00:00 6072
high_tf_condition_long_satisfied 2022-03-31 20:15:00 6073
high_tf_condition_long_satisfied 2022-03-31 20:30:00 6074
high_tf_condition_long_satisfied 2022-03-31 20:45:00 6075
high_tf_condition_long_satisfied 2022-03-31 21:00:00 6076
high_tf_condition_long_satisfied 2022-03-31 21:15:00 6077
high_tf_condition_long_satisfied 2022-03-31 21:30:00 6078
high_tf_condition_long_satisfied 2022-03-31 21:45:00 6079
high_tf_condition_long_satisfied 2022-03-31 22:00:00 6080
high_tf_condition_long_satisfied 2022-03-31 22:15:00 6081
high_tf_condition_long_satisfied 2022-03-31 22:30:00 6082
high_tf_condition_long_satisfied 2022-03-31 22:45:00 6083
high_tf_condition_long_satisfied 2022-03-31 23:00:00 6084
high_tf_condition_long_satisfied 2022-03-31 23:15:00 6085
high_tf_condition_long_satisfied 2022-03-31 23:30:00 6086
high_tf_condition_long_satisfied 2022-03-31 23:45:00 6087
high_tf_condition_long_satisfied 2022-04-01 00:00:00 6088
m15_market_state_bullish 2022-04-01 13:30:00 6142
high_tf_condition_long_satisfied 2022-04-01 19:00:00 6164
high_tf_condition_long_satisfied 2022-04-01 19:15:00 6165
high_tf_condition_long_satisfied 2022-04-01 19:30:00 6166
high_tf_condition_long_satisfied 2022-04-01 19:45:00 6167
high_tf_condition_long_satisfied 2022-04-01 20:00:00 6168
high_tf_condition_long_satisfied 2022-04-01 20:15:00 6169
high_tf_condition_long_satisfied 2022-04-01 20:30:00 6170
high_tf_condition_long_satisfied 2022-04-01 20:45:00 6171
high_tf_condition_long_satisfied 2022-04-01 21:00:00 6172
high_tf_condition_long_satisfied 2022-04-01 21:15:00 6173
high_tf_condition_long_satisfied 2022-04-01 21:30:00 6174
high_tf_condition_long_satisfied 2022-04-01 21:45:00 6175
high_tf_condition_long_satisfied 2022-04-04 00:00:00 6176
m15_market_state_bullish 2022-04-04 03:00:00 6188
m15_market_state_bullish 2022-04-04 15:00:00 6236
high_tf_condition_long_satisfied 2022-04-04 19:00:00 6252
high_tf_condition_long_satisfied 2022-04-04 19:15:00 6253
high_tf_condition_long_satisfied 2022-04-04 19:30:00 6254
high_tf_condition_long_satisfied 2022-04-04 19:45:00 6255
high_tf_condition_long_satisfied 2022-04-04 20:00:00 6256
high_tf_condition_long_satisfied 2022-04-04 20:15:00 6257
high_tf_condition_long_satisfied 2022-04-04 20:30:00 6258
high_tf_condition_long_satisfied 2022-04-04 20:45:00 6259
high_tf_condition_long_satisfied 2022-04-04 21:00:00 6260
high_tf_condition_long_satisfied 2022-04-04 21:15:00 6261
high_tf_condition_long_satisfied 2022-04-04 21:30:00 6262
high_tf_condition_long_satisfied 2022-04-04 21:45:00 6263
high_tf_condition_long_satisfied 2022-04-04 22:00:00 6264
high_tf_condition_long_satisfied 2022-04-04 22:15:00 6265
high_tf_condition_long_satisfied 2022-04-04 22:30:00 6266
high_tf_condition_long_satisfied 2022-04-04 22:45:00 6267
high_tf_condition_long_satisfied 2022-04-04 23:00:00 6268
high_tf_condition_long_satisfied 2022-04-04 23:15:00 6269
high_tf_condition_long_satisfied 2022-04-04 23:30:00 6270
high_tf_condition_long_satisfied 2022-04-04 23:45:00 6271
high_tf_condition_long_satisfied 2022-04-05 00:00:00 6272
m15_market_state_bullish 2022-04-05 05:30:00 6294
high_tf_condition_long_satisfied 2022-04-28 09:45:00 7919
m15_market_state_bullish 2022-04-28 15:15:00 7941
high_tf_condition_long_satisfied 2022-04-28 19:00:00 7956
high_tf_condition_long_satisfied 2022-04-28 19:15:00 7957
high_tf_condition_long_satisfied 2022-04-28 19:30:00 7958
high_tf_condition_long_satisfied 2022-04-28 19:45:00 7959
high_tf_condition_long_satisfied 2022-04-28 20:00:00 7960
high_tf_condition_long_satisfied 2022-04-28 20:15:00 7961
high_tf_condition_long_satisfied 2022-04-28 20:30:00 7962
high_tf_condition_long_satisfied 2022-04-28 20:45:00 7963
high_tf_condition_long_satisfied 2022-04-28 21:00:00 7964
high_tf_condition_long_satisfied 2022-04-28 21:15:00 7965
high_tf_condition_long_satisfied 2022-04-28 21:30:00 7966
high_tf_condition_long_satisfied 2022-04-28 21:45:00 7967
high_tf_condition_long_satisfied 2022-04-28 22:00:00 7968
high_tf_condition_long_satisfied 2022-04-28 22:15:00 7969
high_tf_condition_long_satisfied 2022-04-28 22:30:00 7970
high_tf_condition_long_satisfied 2022-04-28 22:45:00 7971
high_tf_condition_long_satisfied 2022-04-28 23:00:00 7972
high_tf_condition_long_satisfied 2022-04-28 23:15:00 7973
high_tf_condition_long_satisfied 2022-04-28 23:30:00 7974
high_tf_condition_long_satisfied 2022-04-28 23:45:00 7975
high_tf_condition_long_satisfied 2022-04-29 00:00:00 7976
m15_market_state_bullish 2022-04-29 01:15:00 7981
m15_market_state_bullish 2022-04-29 06:00:00 8000
m15_market_state_bullish 2022-04-29 18:30:00 8050
high_tf_condition_long_satisfied 2022-04-29 19:00:00 8052
high_tf_condition_long_satisfied 2022-04-29 19:15:00 8053
high_tf_condition_long_satisfied 2022-04-29 19:30:00 8054
high_tf_condition_long_satisfied 2022-04-29 19:45:00 8055
high_tf_condition_long_satisfied 2022-04-29 20:00:00 8056
high_tf_condition_long_satisfied 2022-04-29 20:15:00 8057
high_tf_condition_long_satisfied 2022-04-29 20:30:00 8058
high_tf_condition_long_satisfied 2022-04-29 20:45:00 8059
high_tf_condition_long_satisfied 2022-04-29 21:00:00 8060
high_tf_condition_long_satisfied 2022-04-29 21:15:00 8061
high_tf_condition_long_satisfied 2022-04-29 21:30:00 8062
high_tf_condition_long_satisfied 2022-04-29 21:45:00 8063
high_tf_condition_long_satisfied 2022-05-02 00:00:00 8064
high_tf_condition_long_satisfied 2022-05-02 19:00:00 8140
high_tf_condition_long_satisfied 2022-05-02 19:15:00 8141
high_tf_condition_long_satisfied 2022-05-02 19:30:00 8142
high_tf_condition_long_satisfied 2022-05-02 19:45:00 8143
high_tf_condition_long_satisfied 2022-05-02 20:00:00 8144
high_tf_condition_long_satisfied 2022-05-02 20:15:00 8145
high_tf_condition_long_satisfied 2022-05-02 20:30:00 8146
high_tf_condition_long_satisfied 2022-05-02 20:45:00 8147
high_tf_condition_long_satisfied 2022-05-02 21:00:00 8148
high_tf_condition_long_satisfied 2022-05-02 21:15:00 8149
high_tf_condition_long_satisfied 2022-05-02 21:30:00 8150
high_tf_condition_long_satisfied 2022-05-02 21:45:00 8151
high_tf_condition_long_satisfied 2022-05-02 22:00:00 8152
high_tf_condition_long_satisfied 2022-05-02 22:15:00 8153
high_tf_condition_long_satisfied 2022-05-02 22:30:00 8154
high_tf_condition_long_satisfied 2022-05-02 22:45:00 8155
high_tf_condition_long_satisfied 2022-05-02 23:00:00 8156
high_tf_condition_long_satisfied 2022-05-02 23:15:00 8157
high_tf_condition_long_satisfied 2022-05-02 23:30:00 8158
high_tf_condition_long_satisfied 2022-05-02 23:45:00 8159
high_tf_condition_long_satisfied 2022-05-03 00:00:00 8160
m15_market_state_bullish 2022-05-03 07:30:00 8190
high_tf_condition_long_satisfied 2022-05-03 19:00:00 8236
high_tf_condition_long_satisfied 2022-05-03 19:15:00 8237
high_tf_condition_long_satisfied 2022-05-03 19:30:00 8238
high_tf_condition_long_satisfied 2022-05-03 19:45:00 8239
high_tf_condition_long_satisfied 2022-05-03 20:00:00 8240
high_tf_condition_long_satisfied 2022-05-03 20:15:00 8241
high_tf_condition_long_satisfied 2022-05-03 20:30:00 8242
high_tf_condition_long_satisfied 2022-05-03 20:45:00 8243
high_tf_condition_long_satisfied 2022-05-03 21:00:00 8244
high_tf_condition_long_satisfied 2022-05-03 21:15:00 8245
high_tf_condition_long_satisfied 2022-05-03 21:30:00 8246
high_tf_condition_long_satisfied 2022-05-03 21:45:00 8247
high_tf_condition_long_satisfied 2022-05-03 22:00:00 8248
high_tf_condition_long_satisfied 2022-05-03 22:15:00 8249
high_tf_condition_long_satisfied 2022-05-03 22:30:00 8250
high_tf_condition_long_satisfied 2022-05-03 22:45:00 8251
high_tf_condition_long_satisfied 2022-05-03 23:00:00 8252
high_tf_condition_long_satisfied 2022-05-03 23:15:00 8253
high_tf_condition_long_satisfied 2022-05-03 23:30:00 8254
high_tf_condition_long_satisfied 2022-05-03 23:45:00 8255
high_tf_condition_long_satisfied 2022-05-04 00:00:00 8256
m15_market_state_bullish 2022-05-04 08:00:00 8288
high_tf_condition_long_satisfied 2022-05-04 19:00:00 8332
high_tf_condition_long_satisfied 2022-05-04 19:15:00 8333

In [14]:
len(df_m15[df_m15.TotalSignal != 0])

126

In [15]:
df_m15['pointpos'] = df_m15.apply(lambda row: Util.pointpos(row), axis=1)

In [16]:
# add some sl tp management
def SIGNAL():
    return dfopt.TotalSignal

class MyStrat(Strategy):
    mysize = 0.5
    slcoef = 2
    TPcoef = 2
    risk_percent = 0.01
    last_swing_low = None
    last_swing_high = None
    previous_swing_low = None
    previous_swing_high = None
    key_level_gap = 0.2
    last_trade_index = 0

    stoploss_info_list = []
    valid_support_level = None

    setup_duration_gap = 60
    stoploss_window = 150
    
    def init(self):
        self.current_day = None
        self.order_placed_time = None
        self.setup_duration = None

        self.stoploss_info_list = []
        self.valid_support_level = None

        super().init()
        self.signal1 = self.I(SIGNAL)

    def reset_order(self):
        # delete placed order at the end of the day if not executed
        if self.order_placed_time:
            for order in self.orders:
                order_executed= False
                for trade in self.trades:
                    if trade.tag == order.tag:
                        order_executed = True

                if order_executed == False:
                    order.cancel()

        self.order_placed_time = None
        self.setup_duration = None
        self.valid_support_level = None

    def get_lowest_low(self):
        return self.data.Low[len(self.data.Low) - self.stoploss_window : len(self.data.Low)].min()

    def is_entry_in_valid_zone(self, valid_support_list):
        return self.data.Close[-1] > min(valid_support_list) - self.key_level_gap

    def add_stoploss_info_list(self, info):
        is_added = False
        for stoploss_info in self.stoploss_info_list:
            if stoploss_info[0] == info[0]:
                is_added = True
                stoploss_info[1] = info[1]

        if is_added == False:
            self.stoploss_info_list.append([info[0], info[1]])

    def get_stoploss_info(self, support_level):
        for stoploss_info in self.stoploss_info_list:
            if stoploss_info[0] == support_level:
                return stoploss_info

        return None

    def dynamic_stoploss(self):
        # delete placed order at the end of the day if not executed
        if self.order_placed_time:
            for order in self.orders:
                order_executed= False
                for trade in self.trades:
                    if trade.tag == order.tag:
                        order_executed = True
                        if order.stop is not None:
                            self.add_stoploss_info_list([self.valid_support_level, order.stop])

                if order_executed == False:
                    order.cancel()
                    if order.is_long:
                        sl = order.stop - self.get_lowest_low()
                        tp = order.stop + self.TPcoef * sl
                        position_size = int((self.risk_percent * self.equity) / sl)
                        order = self.buy(sl = self.get_lowest_low(), tp = tp, size=position_size, stop=order.stop)
        
    def get_tag(self):
        return f"{self.order_placed_time}"

    def wait_3_candles_before_new_trade(self):
            return self.last_trade_index + 3
    
    def next(self):
        super().next()
        index = len(self.data.index)

        # when an order is placed, it will be valable for 12h
        if self.setup_duration is not None and index >= self.setup_duration:
            self.reset_order()

        # place sl to the lowest/highest
        self.dynamic_stoploss()

        if len(self.trades) > 0:
            self.last_trade_index = index

        if len(self.orders)==0 and index >= self.wait_3_candles_before_new_trade():
            if self.signal1[-1]==2:
                valid_support_list = Util.get_valid_support_level(dfopt, index, breakout_candles_lookback)
                if len(valid_support_list) > 0:

                    valid_support_level = min(valid_support_list)
                    is_entry_in_valid_zone = self.is_entry_in_valid_zone(valid_support_list)
                    planned_entry_price = 0
                    sl = 0
                    
                    if is_entry_in_valid_zone: 
                        planned_entry_price = self.data.Close[-1]
                        sl = abs(planned_entry_price - self.get_lowest_low())
                    else :
                        planned_entry_price = valid_support_level - self.key_level_gap
                        sl = abs(planned_entry_price - self.get_lowest_low())

                    sl1 = planned_entry_price - sl
                    stoploss_info = self.get_stoploss_info(valid_support_level)
                    # print(f"{self.data.index[-1]} {stoploss_info} {valid_support_level}")
                    if stoploss_info is None or sl1 < stoploss_info[1]:
                        tp = self.TPcoef * sl
                        position_size = int((self.risk_percent * self.equity) / sl)
                        tp1 = planned_entry_price + tp

                        self.valid_support_level = valid_support_level
                        self.setup_duration = len(self.data.index) + self.setup_duration_gap
                        self.order_placed_time = self.data.index[-1]

                        order = None
                        if is_entry_in_valid_zone: 
                            order = self.buy(sl=sl1, tp=tp1, size=position_size, tag=self.get_tag())
                            print(f"short {self.data.index[-1]} sl = {sl1} & sgnal = {self.signal1[-1]} & valid_resistant_level = {valid_support_level} & entry_price = {planned_entry_price}")
                        else:
                            order = self.buy(sl=sl1, tp=tp1, size=position_size, stop=planned_entry_price, tag=self.get_tag())
                            print(f"short {self.data.index[-1]} sl = {sl1} & sgnal = {self.signal1[-1]} & valid_resistant_level = {valid_support_level} & planned_entry_price = {planned_entry_price}")

In [18]:
start_date_chart = '2022-1-1 00:00'
end_date_chart = '2022-12-30 00:00'
dfopt = df_m15.loc[start_date_chart : end_date_chart]
# dfopt = df_m15

# bt = Backtest(dfopt, MyStrat, cash=10000, margin=0.02, commission=0.0002)
bt = Backtest(dfopt, MyStrat, cash=10000, margin=0.02) #0.0002
stats = bt.run()

print(stats)

bt.plot()

short 2022-06-16 13:30:00 sl = 159.983 & sgnal = 2 & valid_resistant_level = 161.044 & entry_price = 162.355
short 2022-09-21 09:30:00 sl = 162.304 & sgnal = 2 & valid_resistant_level = 162.526 & entry_price = 163.065
short 2022-11-01 13:45:00 sl = 169.654 & sgnal = 2 & valid_resistant_level = 169.78 & entry_price = 170.26
short 2022-11-01 17:45:00 sl = 169.469 & sgnal = 2 & valid_resistant_level = 169.78 & entry_price = 170.236
short 2022-11-04 14:00:00 sl = 165.08 & sgnal = 2 & valid_resistant_level = 169.78 & planned_entry_price = 169.58
short 2022-11-07 09:00:00 sl = 165.08 & sgnal = 2 & valid_resistant_level = 169.78 & planned_entry_price = 169.58
short 2022-11-08 15:15:00 sl = 166.56 & sgnal = 2 & valid_resistant_level = 169.78 & planned_entry_price = 169.58
Start                     2022-01-02 23:00:00
End                       2022-12-29 23:00:00
Duration                    361 days 00:00:00
Exposure Time [%]                     1.45584
Equity Final [$]                     9897.662
Equity Peak [$]                     10254.314
Return [%]                           -1.02338
Buy & Hold Return [%]                 2.95638
Return (Ann.) [%]                     -0.9248
Volatility (Ann.) [%]                  1.9608
CAGR [%]                             -1.03537
Sharpe Ratio                         -0.47164
Sortino Ratio                        -0.53795
Calmar Ratio                          -0.2659
Alpha [%]                            -1.07896
Beta                                   0.0188
Max. Drawdown [%]                    -3.47807
Avg. Drawdown [%]                    -0.34462
Max. Drawdown Duration       99 days 10:45:00
Avg. Drawdown Duration        5 days 19:09:00
# Trades                                    4
Win Rate [%]                             25.0
Best Trade [%]                        2.92389
Worst Trade [%]                      -0.46485
Avg. Trade [%]                        0.40293
Max. Trade Duration           4 days 23:15:00
Avg. Trade Duration           1 days 10:38:00
Profit Factor                         2.30093
Expectancy [%]                        0.41329
SQN                                  -0.34119
Kelly Criterion                      -0.12832
_strategy                             MyStrat
_equity_curve                             ...
_trades                      Size  EntryBa...
dtype: object

c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\_plotting.py:141: UserWarning: Data contains too many candlesticks to plot; downsampling to '1h'. See `Backtest.plot(resample=...)`
  warnings.warn(f"Data contains too many candlesticks to plot; downsampling to {freq!r}. "

GridPlot(id='p1308', ...)

In [ ]:
start_date_chart = '2026-1-1 00:00'
end_date_chart = '2026-2-28 00:00'
dfpl = df_m15.loc[start_date_chart : end_date_chart]#.set_index("Gmt time")

# Create a plot with 2 rows
fig = make_subplots(rows=1, cols=1)

# Add candlestick plot on the first row
fig.add_trace(go.Candlestick(x=dfpl.index,
                             open=dfpl['Open'],
                             high=dfpl['High'],
                             low=dfpl['Low'],
                             close=dfpl['Close']),
              row=1, col=1)

#Add markers for trade entry points on the same subplot
# fig.add_trace(go.Scatter(x=dfpl.index, y=dfpl['support_point'], mode="markers",
#                          marker=dict(size=8, color="green"),
#                          name="support point"),
#               row=1, col=1)

# Add markers for entry point m15
fig.add_trace(go.Scatter(x=dfpl.index, y=dfpl['pointpos'], mode="markers",
                         marker=dict(size=12, color="MediumPurple"),
                         name="entry"),
              row=1, col=1)

# # Add markers for market structure daily = bullish
# fig.add_trace(go.Scatter(x=dfpl.index, y=dfpl['mk_bullish_pos'], mode="markers",
#                          marker=dict(size=8, color="green"),
#                          name="bullish"),
#               row=1, col=1)

# # Add markers for market structure daily = bearish
# fig.add_trace(go.Scatter(x=dfpl.index, y=dfpl['mk_bearish_pos'], mode="markers",
#                          marker=dict(size=8, color="red"),
#                          name="bearish"),
#               row=1, col=1)

fig.update_layout(width=1500, height=800, sliders=[])
fig.show()

In [19]:
start_date_chart = '2022-1-1 00:00'
end_date_chart = '2022-12-30 00:00'
dfpl = df_h4.loc[start_date_chart : end_date_chart]#.set_index("Gmt time")

# Create a plot with 2 rows
fig = make_subplots(rows=1, cols=1)

# Add candlestick plot on the first row
fig.add_trace(go.Candlestick(x=dfpl.index,
                             open=dfpl['Open'],
                             high=dfpl['High'],
                             low=dfpl['Low'],
                             close=dfpl['Close']),
              row=1, col=1)

#Add markers for trade entry points on the same subplot
fig.add_trace(go.Scatter(x=dfpl.index, y=dfpl['support_point'], mode="markers",
                         marker=dict(size=8, color="green"),
                         name="support point"),
              row=1, col=1)

fig.update_layout(width=1200, height=800, sliders=[])
fig.show()